/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Answer,
  Query,
} from '../models/index.js';
import {
    AnswerFromJSON,
    AnswerToJSON,
    QueryFromJSON,
    QueryToJSON,
} from '../models/index.js';

export interface LspApiPostLspCompleteRequest {
    query: Query;
}

export interface LspApiPostLspDiagnosticsRequest {
    query: Query;
}

export interface LspApiPostLspHoverRequest {
    query: Query;
}

export interface LspApiPostLspLocateRequest {
    query: Query;
}

export interface LspApiPostLspSymbolsRequest {
    query: Query;
}

/**
 * 
 */
export class LspApi extends runtime.BaseAPI {

    /**
     * Offers the candidates a language server has at a position, typed and resolved through the repository\'s dependencies rather than guessed from text.
     * Offers the candidates a language server has at a position, typed and resolved through the repository\'s dependencies rather than guessed from text.
     */
    async postLspCompleteRaw(requestParameters: LspApiPostLspCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Answer>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling postLspComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lsp/complete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters['query']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerFromJSON(jsonValue));
    }

    /**
     * Offers the candidates a language server has at a position, typed and resolved through the repository\'s dependencies rather than guessed from text.
     * Offers the candidates a language server has at a position, typed and resolved through the repository\'s dependencies rather than guessed from text.
     */
    async postLspComplete(requestParameters: LspApiPostLspCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Answer> {
        const response = await this.postLspCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reports every problem the language server finds in one file — compile errors, type errors and lints, each with its span and its severity (1 error, 2 warning, 3 information, 4 hint). The position is ignored.
     * Reports every problem the language server finds in one file — compile errors, type errors and lints, each with its span and its severity (1 error, 2 warning, 3 information, 4 hint).
     */
    async postLspDiagnosticsRaw(requestParameters: LspApiPostLspDiagnosticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Answer>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling postLspDiagnostics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lsp/diagnostics`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters['query']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerFromJSON(jsonValue));
    }

    /**
     * Reports every problem the language server finds in one file — compile errors, type errors and lints, each with its span and its severity (1 error, 2 warning, 3 information, 4 hint). The position is ignored.
     * Reports every problem the language server finds in one file — compile errors, type errors and lints, each with its span and its severity (1 error, 2 warning, 3 information, 4 hint).
     */
    async postLspDiagnostics(requestParameters: LspApiPostLspDiagnosticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Answer> {
        const response = await this.postLspDiagnosticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Renders the type and documentation of the symbol at a position, as the language server itself renders it.  Positions are the LSP\'s: line and character are 0-BASED and character counts UTF-16 code units, so an editor\'s 1-based line must have 1 subtracted before it is sent. The repository is named by slug and is always one in the caller\'s own org; rev pins a branch, tag or commit sha, and empty means the default branch.
     * Renders the type and documentation of the symbol at a position, as the language server itself renders it.
     */
    async postLspHoverRaw(requestParameters: LspApiPostLspHoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Answer>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling postLspHover().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lsp/hover`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters['query']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerFromJSON(jsonValue));
    }

    /**
     * Renders the type and documentation of the symbol at a position, as the language server itself renders it.  Positions are the LSP\'s: line and character are 0-BASED and character counts UTF-16 code units, so an editor\'s 1-based line must have 1 subtracted before it is sent. The repository is named by slug and is always one in the caller\'s own org; rev pins a branch, tag or commit sha, and empty means the default branch.
     * Renders the type and documentation of the symbol at a position, as the language server itself renders it.
     */
    async postLspHover(requestParameters: LspApiPostLspHoverRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Answer> {
        const response = await this.postLspHoverRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finds where a symbol lives: its definition, its references, its type or its implementations, chosen by relation (definition, reference, type, implementation — empty means definition).  It resolves THROUGH dependencies. An answer whose external flag is set left the repository, and its path is then the module coordinate it landed in — which is the question a static index cannot answer and this service exists for.
     * Finds where a symbol lives: its definition, its references, its type or its implementations, chosen by relation (definition, reference, type, implementation — empty means definition).
     */
    async postLspLocateRaw(requestParameters: LspApiPostLspLocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Answer>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling postLspLocate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lsp/locate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters['query']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerFromJSON(jsonValue));
    }

    /**
     * Finds where a symbol lives: its definition, its references, its type or its implementations, chosen by relation (definition, reference, type, implementation — empty means definition).  It resolves THROUGH dependencies. An answer whose external flag is set left the repository, and its path is then the module coordinate it landed in — which is the question a static index cannot answer and this service exists for.
     * Finds where a symbol lives: its definition, its references, its type or its implementations, chosen by relation (definition, reference, type, implementation — empty means definition).
     */
    async postLspLocate(requestParameters: LspApiPostLspLocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Answer> {
        const response = await this.postLspLocateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Outlines one file: every declaration in it, with its kind and its span. The position is ignored — the answer is the whole file.
     * Outlines one file: every declaration in it, with its kind and its span.
     */
    async postLspSymbolsRaw(requestParameters: LspApiPostLspSymbolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Answer>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling postLspSymbols().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/lsp/symbols`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryToJSON(requestParameters['query']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnswerFromJSON(jsonValue));
    }

    /**
     * Outlines one file: every declaration in it, with its kind and its span. The position is ignored — the answer is the whole file.
     * Outlines one file: every declaration in it, with its kind and its span.
     */
    async postLspSymbols(requestParameters: LspApiPostLspSymbolsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Answer> {
        const response = await this.postLspSymbolsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
