/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ActivityRow
 */
export interface ActivityRow {
    /**
     * 
     * @type {string}
     * @memberof ActivityRow
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityRow
     */
    actor?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityRow
     */
    at?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityRow
     */
    detail?: string;
    /**
     * 
     * @type {number}
     * @memberof ActivityRow
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityRow
     */
    key?: string;
}

/**
 * Check if a given object implements the ActivityRow interface.
 */
export function instanceOfActivityRow(value: object): value is ActivityRow {
    return true;
}

export function ActivityRowFromJSON(json: any): ActivityRow {
    return ActivityRowFromJSONTyped(json, false);
}

export function ActivityRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityRow {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'actor': json['actor'] == null ? undefined : json['actor'],
        'at': json['at'] == null ? undefined : json['at'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function ActivityRowToJSON(json: any): ActivityRow {
    return ActivityRowToJSONTyped(json, false);
}

export function ActivityRowToJSONTyped(value?: ActivityRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'actor': value['actor'],
        'at': value['at'],
        'detail': value['detail'],
        'id': value['id'],
        'key': value['key'],
    };
}

