/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ActivityRow } from './ActivityRow.js';
import {
    ActivityRowFromJSON,
    ActivityRowFromJSONTyped,
    ActivityRowToJSON,
    ActivityRowToJSONTyped,
} from './ActivityRow.js';

/**
 * 
 * @export
 * @interface ActivityOut
 */
export interface ActivityOut {
    /**
     * Data is the change log newest-first: who created, updated or deleted which key, when.
     * @type {Array<ActivityRow>}
     * @memberof ActivityOut
     */
    data?: Array<ActivityRow>;
}

/**
 * Check if a given object implements the ActivityOut interface.
 */
export function instanceOfActivityOut(value: object): value is ActivityOut {
    return true;
}

export function ActivityOutFromJSON(json: any): ActivityOut {
    return ActivityOutFromJSONTyped(json, false);
}

export function ActivityOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ActivityRowFromJSON)),
    };
}

export function ActivityOutToJSON(json: any): ActivityOut {
    return ActivityOutToJSONTyped(json, false);
}

export function ActivityOutToJSONTyped(value?: ActivityOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ActivityRowToJSON)),
    };
}

