/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PeriodEarningView } from './PeriodEarningView.js';
import {
    PeriodEarningViewFromJSON,
    PeriodEarningViewFromJSONTyped,
    PeriodEarningViewToJSON,
    PeriodEarningViewToJSONTyped,
} from './PeriodEarningView.js';
import type { OrgEarningView } from './OrgEarningView.js';
import {
    OrgEarningViewFromJSON,
    OrgEarningViewFromJSONTyped,
    OrgEarningViewToJSON,
    OrgEarningViewToJSONTyped,
} from './OrgEarningView.js';

/**
 * 
 * @export
 * @interface AffiliateEarnings
 */
export interface AffiliateEarnings {
    /**
     * AccruedCents is lifetime commission accrued, in cents.
     * @type {number}
     * @memberof AffiliateEarnings
     */
    accruedCents?: number;
    /**
     * ByPeriod is the per-period ledger: the margin earned against and the
     * commission taken from it.
     * @type {Array<PeriodEarningView>}
     * @memberof AffiliateEarnings
     */
    byPeriod?: Array<PeriodEarningView>;
    /**
     * ByReferredOrg is each referral's aggregate contribution — the affiliate's
     * OWN share, never the referred org's spend.
     * @type {Array<OrgEarningView>}
     * @memberof AffiliateEarnings
     */
    byReferredOrg?: Array<OrgEarningView>;
    /**
     * IsAffiliate says whether the caller org has an affiliate record. On false it
     * is the ONLY field present — there is no ledger to report, and the zeros you
     * might expect are absent rather than reported as earnings of nothing.
     * @type {boolean}
     * @memberof AffiliateEarnings
     */
    isAffiliate?: boolean;
    /**
     * MarginBps is the platform gross-margin fraction commission is a rate OF.
     * @type {number}
     * @memberof AffiliateEarnings
     */
    marginBps?: number;
    /**
     * PaidCents is lifetime commission already paid out, in cents.
     * @type {number}
     * @memberof AffiliateEarnings
     */
    paidCents?: number;
    /**
     * PendingCents is accrued minus paid — what the platform still owes.
     * @type {number}
     * @memberof AffiliateEarnings
     */
    pendingCents?: number;
}

/**
 * Check if a given object implements the AffiliateEarnings interface.
 */
export function instanceOfAffiliateEarnings(value: object): value is AffiliateEarnings {
    return true;
}

export function AffiliateEarningsFromJSON(json: any): AffiliateEarnings {
    return AffiliateEarningsFromJSONTyped(json, false);
}

export function AffiliateEarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliateEarnings {
    if (json == null) {
        return json;
    }
    return {
        
        'accruedCents': json['accruedCents'] == null ? undefined : json['accruedCents'],
        'byPeriod': json['byPeriod'] == null ? undefined : ((json['byPeriod'] as Array<any>).map(PeriodEarningViewFromJSON)),
        'byReferredOrg': json['byReferredOrg'] == null ? undefined : ((json['byReferredOrg'] as Array<any>).map(OrgEarningViewFromJSON)),
        'isAffiliate': json['isAffiliate'] == null ? undefined : json['isAffiliate'],
        'marginBps': json['marginBps'] == null ? undefined : json['marginBps'],
        'paidCents': json['paidCents'] == null ? undefined : json['paidCents'],
        'pendingCents': json['pendingCents'] == null ? undefined : json['pendingCents'],
    };
}

export function AffiliateEarningsToJSON(json: any): AffiliateEarnings {
    return AffiliateEarningsToJSONTyped(json, false);
}

export function AffiliateEarningsToJSONTyped(value?: AffiliateEarnings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accruedCents': value['accruedCents'],
        'byPeriod': value['byPeriod'] == null ? undefined : ((value['byPeriod'] as Array<any>).map(PeriodEarningViewToJSON)),
        'byReferredOrg': value['byReferredOrg'] == null ? undefined : ((value['byReferredOrg'] as Array<any>).map(OrgEarningViewToJSON)),
        'isAffiliate': value['isAffiliate'],
        'marginBps': value['marginBps'],
        'paidCents': value['paidCents'],
        'pendingCents': value['pendingCents'],
    };
}

