/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentRunView
 */
export interface AgentRunView {
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    actor?: string;
    /**
     * What an operator needs to answer "what ran, for whom, and what did it do" —
     * and, through traceId, to leave this record for the waterfall of the very
     * same run rather than a search that hopefully lands near it.
     * 
     * Agent is on the row because the org-wide feed lists runs across agents, and
     * a run that cannot name its agent is an orphan in exactly the view built to
     * make sense of many of them. Every field is omitempty: a run recorded before
     * these columns existed reports absence rather than a zero it never measured.
     * @type {string}
     * @memberof AgentRunView
     */
    agent?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentRunView
     */
    completionTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentRunView
     */
    durationMs?: number;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    input?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    output?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentRunView
     */
    promptTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentRunView
     */
    toolCalls?: number;
    /**
     * 
     * @type {string}
     * @memberof AgentRunView
     */
    traceId?: string;
}

/**
 * Check if a given object implements the AgentRunView interface.
 */
export function instanceOfAgentRunView(value: object): value is AgentRunView {
    return true;
}

export function AgentRunViewFromJSON(json: any): AgentRunView {
    return AgentRunViewFromJSONTyped(json, false);
}

export function AgentRunViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRunView {
    if (json == null) {
        return json;
    }
    return {
        
        'actor': json['actor'] == null ? undefined : json['actor'],
        'agent': json['agent'] == null ? undefined : json['agent'],
        'completionTokens': json['completionTokens'] == null ? undefined : json['completionTokens'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'error': json['error'] == null ? undefined : json['error'],
        'id': json['id'] == null ? undefined : json['id'],
        'input': json['input'] == null ? undefined : json['input'],
        'model': json['model'] == null ? undefined : json['model'],
        'output': json['output'] == null ? undefined : json['output'],
        'promptTokens': json['promptTokens'] == null ? undefined : json['promptTokens'],
        'status': json['status'] == null ? undefined : json['status'],
        'toolCalls': json['toolCalls'] == null ? undefined : json['toolCalls'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function AgentRunViewToJSON(json: any): AgentRunView {
    return AgentRunViewToJSONTyped(json, false);
}

export function AgentRunViewToJSONTyped(value?: AgentRunView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor': value['actor'],
        'agent': value['agent'],
        'completionTokens': value['completionTokens'],
        'createdAt': value['createdAt'],
        'durationMs': value['durationMs'],
        'error': value['error'],
        'id': value['id'],
        'input': value['input'],
        'model': value['model'],
        'output': value['output'],
        'promptTokens': value['promptTokens'],
        'status': value['status'],
        'toolCalls': value['toolCalls'],
        'traceId': value['traceId'],
    };
}

