/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AiCostStats
 */
export interface AiCostStats {
    /**
     * 
     * @type {string}
     * @memberof AiCostStats
     */
    baselineModel?: string;
    /**
     * 
     * @type {number}
     * @memberof AiCostStats
     */
    counterfactualIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCostStats
     */
    cumulativeSavedIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCostStats
     */
    pricedEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCostStats
     */
    routedIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCostStats
     */
    savedPct?: number;
}

/**
 * Check if a given object implements the AiCostStats interface.
 */
export function instanceOfAiCostStats(value: object): value is AiCostStats {
    return true;
}

export function AiCostStatsFromJSON(json: any): AiCostStats {
    return AiCostStatsFromJSONTyped(json, false);
}

export function AiCostStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiCostStats {
    if (json == null) {
        return json;
    }
    return {
        
        'baselineModel': json['baseline_model'] == null ? undefined : json['baseline_model'],
        'counterfactualIndex': json['counterfactual_index'] == null ? undefined : json['counterfactual_index'],
        'cumulativeSavedIndex': json['cumulative_saved_index'] == null ? undefined : json['cumulative_saved_index'],
        'pricedEvents': json['priced_events'] == null ? undefined : json['priced_events'],
        'routedIndex': json['routed_index'] == null ? undefined : json['routed_index'],
        'savedPct': json['saved_pct'] == null ? undefined : json['saved_pct'],
    };
}

export function AiCostStatsToJSON(json: any): AiCostStats {
    return AiCostStatsToJSONTyped(json, false);
}

export function AiCostStatsToJSONTyped(value?: AiCostStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseline_model': value['baselineModel'],
        'counterfactual_index': value['counterfactualIndex'],
        'cumulative_saved_index': value['cumulativeSavedIndex'],
        'priced_events': value['pricedEvents'],
        'routed_index': value['routedIndex'],
        'saved_pct': value['savedPct'],
    };
}

