/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ApplicationEvent
 */
export interface ApplicationEvent {
    /**
     * 
     * @type {number}
     * @memberof ApplicationEvent
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    firstTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    involvedObject?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    lastTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationEvent
     */
    type?: string;
}

/**
 * Check if a given object implements the ApplicationEvent interface.
 */
export function instanceOfApplicationEvent(value: object): value is ApplicationEvent {
    return true;
}

export function ApplicationEventFromJSON(json: any): ApplicationEvent {
    return ApplicationEventFromJSONTyped(json, false);
}

export function ApplicationEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'firstTime': json['firstTime'] == null ? undefined : json['firstTime'],
        'involvedObject': json['involvedObject'] == null ? undefined : json['involvedObject'],
        'lastTime': json['lastTime'] == null ? undefined : json['lastTime'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'] == null ? undefined : json['name'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'source': json['source'] == null ? undefined : json['source'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ApplicationEventToJSON(json: any): ApplicationEvent {
    return ApplicationEventToJSONTyped(json, false);
}

export function ApplicationEventToJSONTyped(value?: ApplicationEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'firstTime': value['firstTime'],
        'involvedObject': value['involvedObject'],
        'lastTime': value['lastTime'],
        'message': value['message'],
        'name': value['name'],
        'reason': value['reason'],
        'source': value['source'],
        'type': value['type'],
    };
}

