/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ArgoProjectSpec } from './ArgoProjectSpec.js';
import {
    ArgoProjectSpecFromJSON,
    ArgoProjectSpecFromJSONTyped,
    ArgoProjectSpecToJSON,
    ArgoProjectSpecToJSONTyped,
} from './ArgoProjectSpec.js';
import type { ArgoMeta } from './ArgoMeta.js';
import {
    ArgoMetaFromJSON,
    ArgoMetaFromJSONTyped,
    ArgoMetaToJSON,
    ArgoMetaToJSONTyped,
} from './ArgoMeta.js';

/**
 * 
 * @export
 * @interface ArgoProject
 */
export interface ArgoProject {
    /**
     * 
     * @type {string}
     * @memberof ArgoProject
     */
    apiVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ArgoProject
     */
    kind?: string;
    /**
     * 
     * @type {ArgoMeta}
     * @memberof ArgoProject
     */
    metadata?: ArgoMeta;
    /**
     * 
     * @type {ArgoProjectSpec}
     * @memberof ArgoProject
     */
    spec?: ArgoProjectSpec;
    /**
     * 
     * @type {object}
     * @memberof ArgoProject
     */
    status?: object;
}

/**
 * Check if a given object implements the ArgoProject interface.
 */
export function instanceOfArgoProject(value: object): value is ArgoProject {
    return true;
}

export function ArgoProjectFromJSON(json: any): ArgoProject {
    return ArgoProjectFromJSONTyped(json, false);
}

export function ArgoProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArgoProject {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : ArgoMetaFromJSON(json['metadata']),
        'spec': json['spec'] == null ? undefined : ArgoProjectSpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ArgoProjectToJSON(json: any): ArgoProject {
    return ArgoProjectToJSONTyped(json, false);
}

export function ArgoProjectToJSONTyped(value?: ArgoProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'metadata': ArgoMetaToJSON(value['metadata']),
        'spec': ArgoProjectSpecToJSON(value['spec']),
        'status': value['status'],
    };
}

