/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ResearchArtifact } from './ResearchArtifact.js';
import {
    ResearchArtifactFromJSON,
    ResearchArtifactFromJSONTyped,
    ResearchArtifactToJSON,
    ResearchArtifactToJSONTyped,
} from './ResearchArtifact.js';

/**
 * 
 * @export
 * @interface ArtifactsOut
 */
export interface ArtifactsOut {
    /**
     * Data are the artifacts, newest first. Content bytes are never returned here.
     * @type {Array<ResearchArtifact>}
     * @memberof ArtifactsOut
     */
    data?: Array<ResearchArtifact>;
    /**
     * Total is len(data).
     * @type {number}
     * @memberof ArtifactsOut
     */
    total?: number;
}

/**
 * Check if a given object implements the ArtifactsOut interface.
 */
export function instanceOfArtifactsOut(value: object): value is ArtifactsOut {
    return true;
}

export function ArtifactsOutFromJSON(json: any): ArtifactsOut {
    return ArtifactsOutFromJSONTyped(json, false);
}

export function ArtifactsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ResearchArtifactFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ArtifactsOutToJSON(json: any): ArtifactsOut {
    return ArtifactsOutToJSONTyped(json, false);
}

export function ArtifactsOutToJSONTyped(value?: ArtifactsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ResearchArtifactToJSON)),
        'total': value['total'],
    };
}

