/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * Trial is the experiment that was evaluated.
     * @type {string}
     * @memberof Assignment
     */
    experiment?: string;
    /**
     * On is false when the flag returned nothing for this subject, which means the
     * subject is not enrolled — not an error.
     * @type {boolean}
     * @memberof Assignment
     */
    on?: boolean;
    /**
     * 
     * @type {any}
     * @memberof Assignment
     */
    payload?: any | null;
    /**
     * Subject is the unit that was bucketed.
     * @type {string}
     * @memberof Assignment
     */
    subject?: string;
    /**
     * Arm is the arm the subject falls in, empty when the flag enrolled it in
     * none.
     * @type {string}
     * @memberof Assignment
     */
    variant?: string;
}

/**
 * Check if a given object implements the Assignment interface.
 */
export function instanceOfAssignment(value: object): value is Assignment {
    return true;
}

export function AssignmentFromJSON(json: any): Assignment {
    return AssignmentFromJSONTyped(json, false);
}

export function AssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assignment {
    if (json == null) {
        return json;
    }
    return {
        
        'experiment': json['experiment'] == null ? undefined : json['experiment'],
        'on': json['on'] == null ? undefined : json['on'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'variant': json['variant'] == null ? undefined : json['variant'],
    };
}

export function AssignmentToJSON(json: any): Assignment {
    return AssignmentToJSONTyped(json, false);
}

export function AssignmentToJSONTyped(value?: Assignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experiment': value['experiment'],
        'on': value['on'],
        'payload': value['payload'],
        'subject': value['subject'],
        'variant': value['variant'],
    };
}

