/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ReadingView } from './ReadingView.js';
import {
    ReadingViewFromJSON,
    ReadingViewFromJSONTyped,
    ReadingViewToJSON,
    ReadingViewToJSONTyped,
} from './ReadingView.js';

/**
 * 
 * @export
 * @interface BoardResp
 */
export interface BoardResp {
    /**
     * Account is the account the series narrows to, when one was named.
     * @type {string}
     * @memberof BoardResp
     */
    account?: string;
    /**
     * Available reports whether the warehouse answered; false is an honest "we
     * have no data", NOT zero usage.
     * @type {boolean}
     * @memberof BoardResp
     */
    available?: boolean;
    /**
     * Current is the live state of each lane — the dash headline.
     * @type {Array<ReadingView>}
     * @memberof BoardResp
     */
    current?: Array<ReadingView>;
    /**
     * From is when the resolved window opens, RFC 3339 UTC.
     * @type {string}
     * @memberof BoardResp
     */
    from?: string;
    /**
     * Provider is the provider whose meter answered.
     * @type {string}
     * @memberof BoardResp
     */
    provider?: string;
    /**
     * Range is the resolved period label.
     * @type {string}
     * @memberof BoardResp
     */
    range?: string;
    /**
     * Scope is always "user": the caller's own linked accounts.
     * @type {string}
     * @memberof BoardResp
     */
    scope?: string;
    /**
     * Source is always "account": the provider's own meter, not a Hanzo charge.
     * @type {string}
     * @memberof BoardResp
     */
    source?: string;
    /**
     * To is where it closes, EXCLUSIVE, RFC 3339 UTC — the instant the read was
     * served, so the window walks forward with the clock and two reads a minute
     * apart do not cover the same period.
     * @type {string}
     * @memberof BoardResp
     */
    to?: string;
    /**
     * Windows is every window instance in range, newest first.
     * @type {Array<ReadingView>}
     * @memberof BoardResp
     */
    windows?: Array<ReadingView>;
}

/**
 * Check if a given object implements the BoardResp interface.
 */
export function instanceOfBoardResp(value: object): value is BoardResp {
    return true;
}

export function BoardRespFromJSON(json: any): BoardResp {
    return BoardRespFromJSONTyped(json, false);
}

export function BoardRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardResp {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'available': json['available'] == null ? undefined : json['available'],
        'current': json['current'] == null ? undefined : ((json['current'] as Array<any>).map(ReadingViewFromJSON)),
        'from': json['from'] == null ? undefined : json['from'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'range': json['range'] == null ? undefined : json['range'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'source': json['source'] == null ? undefined : json['source'],
        'to': json['to'] == null ? undefined : json['to'],
        'windows': json['windows'] == null ? undefined : ((json['windows'] as Array<any>).map(ReadingViewFromJSON)),
    };
}

export function BoardRespToJSON(json: any): BoardResp {
    return BoardRespToJSONTyped(json, false);
}

export function BoardRespToJSONTyped(value?: BoardResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'available': value['available'],
        'current': value['current'] == null ? undefined : ((value['current'] as Array<any>).map(ReadingViewToJSON)),
        'from': value['from'],
        'provider': value['provider'],
        'range': value['range'],
        'scope': value['scope'],
        'source': value['source'],
        'to': value['to'],
        'windows': value['windows'] == null ? undefined : ((value['windows'] as Array<any>).map(ReadingViewToJSON)),
    };
}

