/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * Posted is true when this call wrote the voucher, false when the same scan had
     * already booked and nothing was written.
     * @type {boolean}
     * @memberof BookResponse
     */
    posted?: boolean;
    /**
     * ScanID echoes the scan that was booked.
     * @type {string}
     * @memberof BookResponse
     */
    scanId?: string;
}

/**
 * Check if a given object implements the BookResponse interface.
 */
export function instanceOfBookResponse(value: object): value is BookResponse {
    return true;
}

export function BookResponseFromJSON(json: any): BookResponse {
    return BookResponseFromJSONTyped(json, false);
}

export function BookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'posted': json['posted'] == null ? undefined : json['posted'],
        'scanId': json['scanId'] == null ? undefined : json['scanId'],
    };
}

export function BookResponseToJSON(json: any): BookResponse {
    return BookResponseToJSONTyped(json, false);
}

export function BookResponseToJSONTyped(value?: BookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'posted': value['posted'],
        'scanId': value['scanId'],
    };
}

