/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BuildRow
 */
export interface BuildRow {
    /**
     * Commit is the short git ref the build pinned.
     * @type {string}
     * @memberof BuildRow
     */
    commit?: string;
    /**
     * Duration is the wall time of a TERMINAL build; empty while it still runs.
     * @type {string}
     * @memberof BuildRow
     */
    duration?: string;
    /**
     * ID is the build record's id.
     * @type {string}
     * @memberof BuildRow
     */
    id?: string;
    /**
     * Repo is the repo the build built, or the image it produced.
     * @type {string}
     * @memberof BuildRow
     */
    repo?: string;
    /**
     * StartedAt is when the build was recorded, RFC3339 UTC.
     * @type {string}
     * @memberof BuildRow
     */
    startedAt?: string;
    /**
     * Status is the build's real state: queued, building, succeeded or failed.
     * @type {string}
     * @memberof BuildRow
     */
    status?: string;
}

/**
 * Check if a given object implements the BuildRow interface.
 */
export function instanceOfBuildRow(value: object): value is BuildRow {
    return true;
}

export function BuildRowFromJSON(json: any): BuildRow {
    return BuildRowFromJSONTyped(json, false);
}

export function BuildRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildRow {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': json['commit'] == null ? undefined : json['commit'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'id': json['id'] == null ? undefined : json['id'],
        'repo': json['repo'] == null ? undefined : json['repo'],
        'startedAt': json['startedAt'] == null ? undefined : json['startedAt'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function BuildRowToJSON(json: any): BuildRow {
    return BuildRowToJSONTyped(json, false);
}

export function BuildRowToJSONTyped(value?: BuildRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit': value['commit'],
        'duration': value['duration'],
        'id': value['id'],
        'repo': value['repo'],
        'startedAt': value['startedAt'],
        'status': value['status'],
    };
}

