/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Campaign
 */
export interface Campaign {
    /**
     * Budget is what the campaign is allowed to cost, in USD cents. A negative
     * value is clamped to 0; nothing enforces the ceiling here.
     * @type {number}
     * @memberof Campaign
     */
    budget?: number;
    /**
     * Channel is the delivery surface: email, sms, social, meta, google or
     * tiktok. Empty means email.
     * @type {string}
     * @memberof Campaign
     */
    channel?: string;
    /**
     * CreatedAt is unix seconds when the campaign was registered. Server-assigned
     * and never rewritten — an update leaves it as it was.
     * @type {number}
     * @memberof Campaign
     */
    createdAt?: number;
    /**
     * ID is the server-assigned campaign id ("camp_" + 128 random bits).
     * @type {string}
     * @memberof Campaign
     */
    id?: string;
    /**
     * Name is the campaign's label. Required, trimmed, capped at 1024 bytes.
     * @type {string}
     * @memberof Campaign
     */
    name?: string;
    /**
     * Objective is the free-text goal ("signups"), capped at 1024 bytes.
     * @type {string}
     * @memberof Campaign
     */
    objective?: string;
    /**
     * ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a
     * campaign with no explicit status makes that status "scheduled".
     * @type {number}
     * @memberof Campaign
     */
    scheduledAt?: number;
    /**
     * Spend is what the campaign has cost so far, in USD cents, clamped to >= 0.
     * The CALLER owns it: no send, ad buy or invoice moves it, so it changes only
     * when create or update carries a new value. It is summed across the org's
     * campaigns into GET /v1/marketing/summary.
     * @type {number}
     * @memberof Campaign
     */
    spend?: number;
    /**
     * Status is the lifecycle: draft, scheduled, active, paused or completed.
     * Empty means draft.
     * @type {string}
     * @memberof Campaign
     */
    status?: string;
    /**
     * UpdatedAt is unix seconds of the last write. Server-assigned on create and
     * on every update or schedule change, and the campaign list is ordered by it,
     * newest first.
     * @type {number}
     * @memberof Campaign
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the Campaign interface.
 */
export function instanceOfCampaign(value: object): value is Campaign {
    return true;
}

export function CampaignFromJSON(json: any): Campaign {
    return CampaignFromJSONTyped(json, false);
}

export function CampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): Campaign {
    if (json == null) {
        return json;
    }
    return {
        
        'budget': json['budget'] == null ? undefined : json['budget'],
        'channel': json['channel'] == null ? undefined : json['channel'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'objective': json['objective'] == null ? undefined : json['objective'],
        'scheduledAt': json['scheduledAt'] == null ? undefined : json['scheduledAt'],
        'spend': json['spend'] == null ? undefined : json['spend'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function CampaignToJSON(json: any): Campaign {
    return CampaignToJSONTyped(json, false);
}

export function CampaignToJSONTyped(value?: Campaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget': value['budget'],
        'channel': value['channel'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'objective': value['objective'],
        'scheduledAt': value['scheduledAt'],
        'spend': value['spend'],
        'status': value['status'],
        'updatedAt': value['updatedAt'],
    };
}

