/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CaptableEquityPlanIn
 */
export interface CaptableEquityPlanIn {
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    boardApprovalDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    comments?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    defaultCancellatonBehavior?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    initialSharesReserved?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    planEffectiveDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableEquityPlanIn
     */
    shareClassId?: any | null;
}

/**
 * Check if a given object implements the CaptableEquityPlanIn interface.
 */
export function instanceOfCaptableEquityPlanIn(value: object): value is CaptableEquityPlanIn {
    return true;
}

export function CaptableEquityPlanInFromJSON(json: any): CaptableEquityPlanIn {
    return CaptableEquityPlanInFromJSONTyped(json, false);
}

export function CaptableEquityPlanInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptableEquityPlanIn {
    if (json == null) {
        return json;
    }
    return {
        
        'boardApprovalDate': json['boardApprovalDate'] == null ? undefined : json['boardApprovalDate'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'defaultCancellatonBehavior': json['defaultCancellatonBehavior'] == null ? undefined : json['defaultCancellatonBehavior'],
        'initialSharesReserved': json['initialSharesReserved'] == null ? undefined : json['initialSharesReserved'],
        'name': json['name'] == null ? undefined : json['name'],
        'planEffectiveDate': json['planEffectiveDate'] == null ? undefined : json['planEffectiveDate'],
        'shareClassId': json['shareClassId'] == null ? undefined : json['shareClassId'],
    };
}

export function CaptableEquityPlanInToJSON(json: any): CaptableEquityPlanIn {
    return CaptableEquityPlanInToJSONTyped(json, false);
}

export function CaptableEquityPlanInToJSONTyped(value?: CaptableEquityPlanIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boardApprovalDate': value['boardApprovalDate'],
        'comments': value['comments'],
        'defaultCancellatonBehavior': value['defaultCancellatonBehavior'],
        'initialSharesReserved': value['initialSharesReserved'],
        'name': value['name'],
        'planEffectiveDate': value['planEffectiveDate'],
        'shareClassId': value['shareClassId'],
    };
}

