/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CaptableConvertibleIn
 */
export interface CaptableConvertibleIn {
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    additionalTerms?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    boardApprovalDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    capital?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    conversionCap?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    discountRate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    interestRate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    issueDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    publicId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    stakeholderId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    status?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableConvertibleIn
     */
    type?: any | null;
}

/**
 * Check if a given object implements the CaptableConvertibleIn interface.
 */
export function instanceOfCaptableConvertibleIn(value: object): value is CaptableConvertibleIn {
    return true;
}

export function CaptableConvertibleInFromJSON(json: any): CaptableConvertibleIn {
    return CaptableConvertibleInFromJSONTyped(json, false);
}

export function CaptableConvertibleInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptableConvertibleIn {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalTerms': json['additionalTerms'] == null ? undefined : json['additionalTerms'],
        'boardApprovalDate': json['boardApprovalDate'] == null ? undefined : json['boardApprovalDate'],
        'capital': json['capital'] == null ? undefined : json['capital'],
        'conversionCap': json['conversionCap'] == null ? undefined : json['conversionCap'],
        'discountRate': json['discountRate'] == null ? undefined : json['discountRate'],
        'interestRate': json['interestRate'] == null ? undefined : json['interestRate'],
        'issueDate': json['issueDate'] == null ? undefined : json['issueDate'],
        'publicId': json['publicId'] == null ? undefined : json['publicId'],
        'stakeholderId': json['stakeholderId'] == null ? undefined : json['stakeholderId'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CaptableConvertibleInToJSON(json: any): CaptableConvertibleIn {
    return CaptableConvertibleInToJSONTyped(json, false);
}

export function CaptableConvertibleInToJSONTyped(value?: CaptableConvertibleIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalTerms': value['additionalTerms'],
        'boardApprovalDate': value['boardApprovalDate'],
        'capital': value['capital'],
        'conversionCap': value['conversionCap'],
        'discountRate': value['discountRate'],
        'interestRate': value['interestRate'],
        'issueDate': value['issueDate'],
        'publicId': value['publicId'],
        'stakeholderId': value['stakeholderId'],
        'status': value['status'],
        'type': value['type'],
    };
}

