/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CaptableSafeIn
 */
export interface CaptableSafeIn {
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    additionalTerms?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    boardApprovalDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    capital?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    discountRate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    issueDate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    publicId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    stakeholderId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    status?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CaptableSafeIn
     */
    valuationCap?: any | null;
}

/**
 * Check if a given object implements the CaptableSafeIn interface.
 */
export function instanceOfCaptableSafeIn(value: object): value is CaptableSafeIn {
    return true;
}

export function CaptableSafeInFromJSON(json: any): CaptableSafeIn {
    return CaptableSafeInFromJSONTyped(json, false);
}

export function CaptableSafeInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptableSafeIn {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalTerms': json['additionalTerms'] == null ? undefined : json['additionalTerms'],
        'boardApprovalDate': json['boardApprovalDate'] == null ? undefined : json['boardApprovalDate'],
        'capital': json['capital'] == null ? undefined : json['capital'],
        'discountRate': json['discountRate'] == null ? undefined : json['discountRate'],
        'issueDate': json['issueDate'] == null ? undefined : json['issueDate'],
        'publicId': json['publicId'] == null ? undefined : json['publicId'],
        'stakeholderId': json['stakeholderId'] == null ? undefined : json['stakeholderId'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
        'valuationCap': json['valuationCap'] == null ? undefined : json['valuationCap'],
    };
}

export function CaptableSafeInToJSON(json: any): CaptableSafeIn {
    return CaptableSafeInToJSONTyped(json, false);
}

export function CaptableSafeInToJSONTyped(value?: CaptableSafeIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalTerms': value['additionalTerms'],
        'boardApprovalDate': value['boardApprovalDate'],
        'capital': value['capital'],
        'discountRate': value['discountRate'],
        'issueDate': value['issueDate'],
        'publicId': value['publicId'],
        'stakeholderId': value['stakeholderId'],
        'status': value['status'],
        'type': value['type'],
        'valuationCap': value['valuationCap'],
    };
}

