/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CategoryIn
 */
export interface CategoryIn {
    /**
     * Brands are the brands whose console shows it. Omit for every brand.
     * @type {Array<string>}
     * @memberof CategoryIn
     */
    brands?: Array<string>;
    /**
     * ID is the category slug to write, from the path.
     * @type {string}
     * @memberof CategoryIn
     */
    id?: string;
    /**
     * Label is the display name. Required.
     * @type {string}
     * @memberof CategoryIn
     */
    label?: string;
    /**
     * Order is where the category sits among its siblings, ascending.
     * @type {number}
     * @memberof CategoryIn
     */
    order?: number;
    /**
     * Summary is the one line describing what the category groups.
     * @type {string}
     * @memberof CategoryIn
     */
    summary?: string;
}

/**
 * Check if a given object implements the CategoryIn interface.
 */
export function instanceOfCategoryIn(value: object): value is CategoryIn {
    return true;
}

export function CategoryInFromJSON(json: any): CategoryIn {
    return CategoryInFromJSONTyped(json, false);
}

export function CategoryInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryIn {
    if (json == null) {
        return json;
    }
    return {
        
        'brands': json['brands'] == null ? undefined : json['brands'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'order': json['order'] == null ? undefined : json['order'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function CategoryInToJSON(json: any): CategoryIn {
    return CategoryInToJSONTyped(json, false);
}

export function CategoryInToJSONTyped(value?: CategoryIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brands': value['brands'],
        'id': value['id'],
        'label': value['label'],
        'order': value['order'],
        'summary': value['summary'],
    };
}

