/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CDApp
 */
export interface CDApp {
    /**
     * Automated is whether CD applies git without being asked. It is
     * cd.automated in the values file, rendered by the ApplicationSet's
     * templatePatch — false means the Application reports drift and nothing moves.
     * @type {boolean}
     * @memberof CDApp
     */
    automated?: boolean;
    /**
     * Health is the workload's verdict: Healthy, Progressing, Degraded, Missing.
     * @type {string}
     * @memberof CDApp
     */
    health?: string;
    /**
     * Message is why, when Health is not Healthy.
     * @type {string}
     * @memberof CDApp
     */
    message?: string;
    /**
     * Name is the Application name the generator mints: <namespace>-<app>. It is
     * the join key against a Declaration.
     * @type {string}
     * @memberof CDApp
     */
    name?: string;
    /**
     * Namespace is the DESTINATION namespace as the CR declares it — where the
     * workload lands. For a fleet Application that is the org, but this is the
     * OBSERVED field and not our model of it: the two can disagree, and a board
     * whose whole job is drift must be able to show that they do.
     * @type {string}
     * @memberof CDApp
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof CDApp
     */
    operationMessage?: string;
    /**
     * Path is the values file CD renders against, relative to the chart source.
     * @type {string}
     * @memberof CDApp
     */
    path?: string;
    /**
     * Phase is the last sync operation's phase (Running, Succeeded, Failed) and
     * OperationMessage is its message. A Failed phase with a Synced verdict is
     * the shape a stuck Application takes.
     * @type {string}
     * @memberof CDApp
     */
    phase?: string;
    /**
     * Project is the AppProject fence the sync is admitted under.
     * @type {string}
     * @memberof CDApp
     */
    project?: string;
    /**
     * ReconciledAt is when CD last compared this Application.
     * @type {string}
     * @memberof CDApp
     */
    reconciledAt?: string;
    /**
     * Revision is the universe commit CD last applied. Empty means it has not
     * applied one — never assume it means main.
     * @type {string}
     * @memberof CDApp
     */
    revision?: string;
    /**
     * SelfHeal is whether CD also corrects drift the cluster introduced.
     * @type {boolean}
     * @memberof CDApp
     */
    selfHeal?: boolean;
    /**
     * Sync is CD's verdict on git-versus-cluster: Synced, OutOfSync, or Unknown.
     * @type {string}
     * @memberof CDApp
     */
    sync?: string;
}

/**
 * Check if a given object implements the CDApp interface.
 */
export function instanceOfCDApp(value: object): value is CDApp {
    return true;
}

export function CDAppFromJSON(json: any): CDApp {
    return CDAppFromJSONTyped(json, false);
}

export function CDAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): CDApp {
    if (json == null) {
        return json;
    }
    return {
        
        'automated': json['automated'] == null ? undefined : json['automated'],
        'health': json['health'] == null ? undefined : json['health'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'] == null ? undefined : json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'operationMessage': json['operationMessage'] == null ? undefined : json['operationMessage'],
        'path': json['path'] == null ? undefined : json['path'],
        'phase': json['phase'] == null ? undefined : json['phase'],
        'project': json['project'] == null ? undefined : json['project'],
        'reconciledAt': json['reconciledAt'] == null ? undefined : json['reconciledAt'],
        'revision': json['revision'] == null ? undefined : json['revision'],
        'selfHeal': json['selfHeal'] == null ? undefined : json['selfHeal'],
        'sync': json['sync'] == null ? undefined : json['sync'],
    };
}

export function CDAppToJSON(json: any): CDApp {
    return CDAppToJSONTyped(json, false);
}

export function CDAppToJSONTyped(value?: CDApp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'automated': value['automated'],
        'health': value['health'],
        'message': value['message'],
        'name': value['name'],
        'namespace': value['namespace'],
        'operationMessage': value['operationMessage'],
        'path': value['path'],
        'phase': value['phase'],
        'project': value['project'],
        'reconciledAt': value['reconciledAt'],
        'revision': value['revision'],
        'selfHeal': value['selfHeal'],
        'sync': value['sync'],
    };
}

