/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ChallengeView
 */
export interface ChallengeView {
    /**
     * ExpiresAt is when the nonce stops being redeemable, as a Unix timestamp.
     * @type {number}
     * @memberof ChallengeView
     */
    expiresAt?: number;
    /**
     * Message is the EXACT text to personal_sign. It is reconstructed server-side
     * from the validated org, the slot and the nonce at redemption, so signing
     * anything else cannot claim the slot.
     * @type {string}
     * @memberof ChallengeView
     */
    message?: string;
    /**
     * Nonce is the single-use, org-bound challenge value to send back with the
     * signature.
     * @type {string}
     * @memberof ChallengeView
     */
    nonce?: string;
    /**
     * TokenID is the slot the challenge was issued for.
     * @type {number}
     * @memberof ChallengeView
     */
    tokenId?: number;
    /**
     * TTLSeconds is the challenge lifetime in seconds.
     * @type {number}
     * @memberof ChallengeView
     */
    ttlSeconds?: number;
}

/**
 * Check if a given object implements the ChallengeView interface.
 */
export function instanceOfChallengeView(value: object): value is ChallengeView {
    return true;
}

export function ChallengeViewFromJSON(json: any): ChallengeView {
    return ChallengeViewFromJSONTyped(json, false);
}

export function ChallengeViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeView {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expiresAt'] == null ? undefined : json['expiresAt'],
        'message': json['message'] == null ? undefined : json['message'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'tokenId': json['tokenId'] == null ? undefined : json['tokenId'],
        'ttlSeconds': json['ttlSeconds'] == null ? undefined : json['ttlSeconds'],
    };
}

export function ChallengeViewToJSON(json: any): ChallengeView {
    return ChallengeViewToJSONTyped(json, false);
}

export function ChallengeViewToJSONTyped(value?: ChallengeView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expiresAt': value['expiresAt'],
        'message': value['message'],
        'nonce': value['nonce'],
        'tokenId': value['tokenId'],
        'ttlSeconds': value['ttlSeconds'],
    };
}

