/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClusterView } from './ClusterView.js';
import {
    ClusterViewFromJSON,
    ClusterViewFromJSONTyped,
    ClusterViewToJSON,
    ClusterViewToJSONTyped,
} from './ClusterView.js';
import type { SourceFailure } from './SourceFailure.js';
import {
    SourceFailureFromJSON,
    SourceFailureFromJSONTyped,
    SourceFailureToJSON,
    SourceFailureToJSONTyped,
} from './SourceFailure.js';

/**
 * 
 * @export
 * @interface ClusterList
 */
export interface ClusterList {
    /**
     * Clusters is the merged fleet — kind "managed" for Visor-provisioned, "byo"
     * for an attached kubeconfig.
     * @type {Array<ClusterView>}
     * @memberof ClusterList
     */
    clusters?: Array<ClusterView>;
    /**
     * Degraded names any source that did not answer, so an empty Clusters means
     * "you have none" only when this is absent. Omitted when everything answered,
     * so a healthy response is unchanged. See degraded.go.
     * @type {Array<SourceFailure>}
     * @memberof ClusterList
     */
    degraded?: Array<SourceFailure>;
}

/**
 * Check if a given object implements the ClusterList interface.
 */
export function instanceOfClusterList(value: object): value is ClusterList {
    return true;
}

export function ClusterListFromJSON(json: any): ClusterList {
    return ClusterListFromJSONTyped(json, false);
}

export function ClusterListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterList {
    if (json == null) {
        return json;
    }
    return {
        
        'clusters': json['clusters'] == null ? undefined : ((json['clusters'] as Array<any>).map(ClusterViewFromJSON)),
        'degraded': json['degraded'] == null ? undefined : ((json['degraded'] as Array<any>).map(SourceFailureFromJSON)),
    };
}

export function ClusterListToJSON(json: any): ClusterList {
    return ClusterListToJSONTyped(json, false);
}

export function ClusterListToJSONTyped(value?: ClusterList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clusters': value['clusters'] == null ? undefined : ((value['clusters'] as Array<any>).map(ClusterViewToJSON)),
        'degraded': value['degraded'] == null ? undefined : ((value['degraded'] as Array<any>).map(SourceFailureToJSON)),
    };
}

