/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CodingStartIn
 */
export interface CodingStartIn {
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    after?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    agentRef?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    base?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CodingStartIn
     */
    desktop?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    project?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    prompt?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    replyChannel?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    replyThread?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    repo?: string;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    targetId?: string;
    /**
     * 
     * @type {number}
     * @memberof CodingStartIn
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof CodingStartIn
     */
    tool?: string;
}

/**
 * Check if a given object implements the CodingStartIn interface.
 */
export function instanceOfCodingStartIn(value: object): value is CodingStartIn {
    return true;
}

export function CodingStartInFromJSON(json: any): CodingStartIn {
    return CodingStartInFromJSONTyped(json, false);
}

export function CodingStartInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodingStartIn {
    if (json == null) {
        return json;
    }
    return {
        
        'after': json['after'] == null ? undefined : json['after'],
        'agentRef': json['agentRef'] == null ? undefined : json['agentRef'],
        'base': json['base'] == null ? undefined : json['base'],
        'desktop': json['desktop'] == null ? undefined : json['desktop'],
        'project': json['project'] == null ? undefined : json['project'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'replyChannel': json['replyChannel'] == null ? undefined : json['replyChannel'],
        'replyThread': json['replyThread'] == null ? undefined : json['replyThread'],
        'repo': json['repo'] == null ? undefined : json['repo'],
        'targetId': json['targetId'] == null ? undefined : json['targetId'],
        'timeoutSeconds': json['timeoutSeconds'] == null ? undefined : json['timeoutSeconds'],
        'tool': json['tool'] == null ? undefined : json['tool'],
    };
}

export function CodingStartInToJSON(json: any): CodingStartIn {
    return CodingStartInToJSONTyped(json, false);
}

export function CodingStartInToJSONTyped(value?: CodingStartIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'after': value['after'],
        'agentRef': value['agentRef'],
        'base': value['base'],
        'desktop': value['desktop'],
        'project': value['project'],
        'prompt': value['prompt'],
        'replyChannel': value['replyChannel'],
        'replyThread': value['replyThread'],
        'repo': value['repo'],
        'targetId': value['targetId'],
        'timeoutSeconds': value['timeoutSeconds'],
        'tool': value['tool'],
    };
}

