/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InvoiceOut } from './InvoiceOut.js';
import {
    InvoiceOutFromJSON,
    InvoiceOutFromJSONTyped,
    InvoiceOutToJSON,
    InvoiceOutToJSONTyped,
} from './InvoiceOut.js';

/**
 * 
 * @export
 * @interface CollectOut
 */
export interface CollectOut {
    /**
     * BalanceUsedCents is how much was covered by prepaid balance.
     * @type {number}
     * @memberof CollectOut
     */
    balanceUsedCents?: number;
    /**
     * CardChargedCents is how much was charged to the card on file.
     * @type {number}
     * @memberof CollectOut
     */
    cardChargedCents?: number;
    /**
     * CreditUsedCents is how much was covered by credit grants.
     * @type {number}
     * @memberof CollectOut
     */
    creditUsedCents?: number;
    /**
     * Invoice is the invoice AFTER the attempt — its status is the authority on
     * what happened, not this struct's other fields.
     * @type {InvoiceOut}
     * @memberof CollectOut
     */
    invoice?: InvoiceOut;
    /**
     * Paid reports whether the invoice is now settled in full. A false here with
     * no error is a DECLINE: the invoice stays open and may be collected again.
     * @type {boolean}
     * @memberof CollectOut
     */
    paid?: boolean;
    /**
     * ProcessorRef is the processor's reference for any card charge — the field
     * that proves money moved at the gateway rather than only in our ledger.
     * @type {string}
     * @memberof CollectOut
     */
    processorRef?: string;
    /**
     * Reason explains a decline or partial collection. Empty on success.
     * @type {string}
     * @memberof CollectOut
     */
    reason?: string;
}

/**
 * Check if a given object implements the CollectOut interface.
 */
export function instanceOfCollectOut(value: object): value is CollectOut {
    return true;
}

export function CollectOutFromJSON(json: any): CollectOut {
    return CollectOutFromJSONTyped(json, false);
}

export function CollectOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectOut {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceUsedCents': json['balanceUsedCents'] == null ? undefined : json['balanceUsedCents'],
        'cardChargedCents': json['cardChargedCents'] == null ? undefined : json['cardChargedCents'],
        'creditUsedCents': json['creditUsedCents'] == null ? undefined : json['creditUsedCents'],
        'invoice': json['invoice'] == null ? undefined : InvoiceOutFromJSON(json['invoice']),
        'paid': json['paid'] == null ? undefined : json['paid'],
        'processorRef': json['processorRef'] == null ? undefined : json['processorRef'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CollectOutToJSON(json: any): CollectOut {
    return CollectOutToJSONTyped(json, false);
}

export function CollectOutToJSONTyped(value?: CollectOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balanceUsedCents': value['balanceUsedCents'],
        'cardChargedCents': value['cardChargedCents'],
        'creditUsedCents': value['creditUsedCents'],
        'invoice': InvoiceOutToJSON(value['invoice']),
        'paid': value['paid'],
        'processorRef': value['processorRef'],
        'reason': value['reason'],
    };
}

