/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommitJSON } from './CommitJSON.js';
import {
    CommitJSONFromJSON,
    CommitJSONFromJSONTyped,
    CommitJSONToJSON,
    CommitJSONToJSONTyped,
} from './CommitJSON.js';

/**
 * 
 * @export
 * @interface CommitsJSON
 */
export interface CommitsJSON {
    /**
     * Commits are newest first.
     * @type {Array<CommitJSON>}
     * @memberof CommitsJSON
     */
    commits?: Array<CommitJSON>;
}

/**
 * Check if a given object implements the CommitsJSON interface.
 */
export function instanceOfCommitsJSON(value: object): value is CommitsJSON {
    return true;
}

export function CommitsJSONFromJSON(json: any): CommitsJSON {
    return CommitsJSONFromJSONTyped(json, false);
}

export function CommitsJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitsJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'commits': json['commits'] == null ? undefined : ((json['commits'] as Array<any>).map(CommitJSONFromJSON)),
    };
}

export function CommitsJSONToJSON(json: any): CommitsJSON {
    return CommitsJSONToJSONTyped(json, false);
}

export function CommitsJSONToJSONTyped(value?: CommitsJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commits': value['commits'] == null ? undefined : ((value['commits'] as Array<any>).map(CommitJSONToJSON)),
    };
}

