/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * ARR is annual recurring revenue in minor units (cents) of Currency.
     * @type {number}
     * @memberof Company
     */
    arr?: number;
    /**
     * City is the head-office city.
     * @type {string}
     * @memberof Company
     */
    city?: string;
    /**
     * Country is the head-office country.
     * @type {string}
     * @memberof Company
     */
    country?: string;
    /**
     * CreatedAt is the unix second the company was created. Server-owned.
     * @type {number}
     * @memberof Company
     */
    createdAt?: number;
    /**
     * Currency is the ISO code ARR is denominated in; a write that names none
     * stores USD.
     * @type {string}
     * @memberof Company
     */
    currency?: string;
    /**
     * DomainName is the company's primary domain, e.g. "acme.com".
     * @type {string}
     * @memberof Company
     */
    domainName?: string;
    /**
     * Employees is the headcount.
     * @type {number}
     * @memberof Company
     */
    employees?: number;
    /**
     * ID is the server-minted company id ("comp_" + 128 random bits).
     * @type {string}
     * @memberof Company
     */
    id?: string;
    /**
     * ICP marks the company as an ideal-customer-profile fit.
     * @type {boolean}
     * @memberof Company
     */
    idealCustomerProfile?: boolean;
    /**
     * Linkedin is the company's LinkedIn URL.
     * @type {string}
     * @memberof Company
     */
    linkedinLink?: string;
    /**
     * Name is the company name.
     * @type {string}
     * @memberof Company
     */
    name?: string;
    /**
     * UpdatedAt is the unix second of the last write. Server-owned.
     * @type {number}
     * @memberof Company
     */
    updatedAt?: number;
    /**
     * XLink is the company's X (Twitter) URL.
     * @type {string}
     * @memberof Company
     */
    xLink?: string;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): value is Company {
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'arr': json['arr'] == null ? undefined : json['arr'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'domainName': json['domainName'] == null ? undefined : json['domainName'],
        'employees': json['employees'] == null ? undefined : json['employees'],
        'id': json['id'] == null ? undefined : json['id'],
        'idealCustomerProfile': json['idealCustomerProfile'] == null ? undefined : json['idealCustomerProfile'],
        'linkedinLink': json['linkedinLink'] == null ? undefined : json['linkedinLink'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'xLink': json['xLink'] == null ? undefined : json['xLink'],
    };
}

export function CompanyToJSON(json: any): Company {
    return CompanyToJSONTyped(json, false);
}

export function CompanyToJSONTyped(value?: Company | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arr': value['arr'],
        'city': value['city'],
        'country': value['country'],
        'createdAt': value['createdAt'],
        'currency': value['currency'],
        'domainName': value['domainName'],
        'employees': value['employees'],
        'id': value['id'],
        'idealCustomerProfile': value['idealCustomerProfile'],
        'linkedinLink': value['linkedinLink'],
        'name': value['name'],
        'updatedAt': value['updatedAt'],
        'xLink': value['xLink'],
    };
}

