/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConsumerRecord } from './ConsumerRecord.js';
import {
    ConsumerRecordFromJSON,
    ConsumerRecordFromJSONTyped,
    ConsumerRecordToJSON,
    ConsumerRecordToJSONTyped,
} from './ConsumerRecord.js';

/**
 * 
 * @export
 * @interface ConsumerPage
 */
export interface ConsumerPage {
    /**
     * Data are the stream's consumers.
     * @type {Array<ConsumerRecord>}
     * @memberof ConsumerPage
     */
    data?: Array<ConsumerRecord>;
}

/**
 * Check if a given object implements the ConsumerPage interface.
 */
export function instanceOfConsumerPage(value: object): value is ConsumerPage {
    return true;
}

export function ConsumerPageFromJSON(json: any): ConsumerPage {
    return ConsumerPageFromJSONTyped(json, false);
}

export function ConsumerPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumerPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ConsumerRecordFromJSON)),
    };
}

export function ConsumerPageToJSON(json: any): ConsumerPage {
    return ConsumerPageToJSONTyped(json, false);
}

export function ConsumerPageToJSONTyped(value?: ConsumerPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ConsumerRecordToJSON)),
    };
}

