/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConnView } from './ConnView.js';
import {
    ConnViewFromJSON,
    ConnViewFromJSONTyped,
    ConnViewToJSON,
    ConnViewToJSONTyped,
} from './ConnView.js';

/**
 * 
 * @export
 * @interface CredentialOut
 */
export interface CredentialOut {
    /**
     * Connected is always true — a failed verification is a 400 and stores nothing.
     * @type {boolean}
     * @memberof CredentialOut
     */
    connected?: boolean;
    /**
     * Connection is the connector as it now stands.
     * @type {ConnView}
     * @memberof CredentialOut
     */
    connector?: ConnView;
}

/**
 * Check if a given object implements the CredentialOut interface.
 */
export function instanceOfCredentialOut(value: object): value is CredentialOut {
    return true;
}

export function CredentialOutFromJSON(json: any): CredentialOut {
    return CredentialOutFromJSONTyped(json, false);
}

export function CredentialOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialOut {
    if (json == null) {
        return json;
    }
    return {
        
        'connected': json['connected'] == null ? undefined : json['connected'],
        'connector': json['connector'] == null ? undefined : ConnViewFromJSON(json['connector']),
    };
}

export function CredentialOutToJSON(json: any): CredentialOut {
    return CredentialOutToJSONTyped(json, false);
}

export function CredentialOutToJSONTyped(value?: CredentialOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connected': value['connected'],
        'connector': ConnViewToJSON(value['connector']),
    };
}

