/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DocumentSummary } from './DocumentSummary.js';
import {
    DocumentSummaryFromJSON,
    DocumentSummaryFromJSONTyped,
    DocumentSummaryToJSON,
    DocumentSummaryToJSONTyped,
} from './DocumentSummary.js';

/**
 * 
 * @export
 * @interface DocumentPage
 */
export interface DocumentPage {
    /**
     * Data are the documents, WITHOUT their rendered content — fetch one to read it.
     * @type {Array<DocumentSummary>}
     * @memberof DocumentPage
     */
    data?: Array<DocumentSummary>;
    /**
     * Disclaimer is the boundary made visible on the wire.
     * @type {string}
     * @memberof DocumentPage
     */
    disclaimer?: string;
}

/**
 * Check if a given object implements the DocumentPage interface.
 */
export function instanceOfDocumentPage(value: object): value is DocumentPage {
    return true;
}

export function DocumentPageFromJSON(json: any): DocumentPage {
    return DocumentPageFromJSONTyped(json, false);
}

export function DocumentPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentPage {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DocumentSummaryFromJSON)),
        'disclaimer': json['disclaimer'] == null ? undefined : json['disclaimer'],
    };
}

export function DocumentPageToJSON(json: any): DocumentPage {
    return DocumentPageToJSONTyped(json, false);
}

export function DocumentPageToJSONTyped(value?: DocumentPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DocumentSummaryToJSON)),
        'disclaimer': value['disclaimer'],
    };
}

