/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DocumentSummary
 */
export interface DocumentSummary {
    /**
     * Category is the template's category: formation, equity, ops or sales.
     * @type {string}
     * @memberof DocumentSummary
     */
    category?: string;
    /**
     * CreatedAt is when the document was generated, in unix seconds.
     * @type {number}
     * @memberof DocumentSummary
     */
    createdAt?: number;
    /**
     * EsignProvider names the e-signature provider handling it, absent until a
     * signature has been requested.
     * @type {string}
     * @memberof DocumentSummary
     */
    esignProvider?: string;
    /**
     * ID is the document's server-minted handle, "doc_"-prefixed.
     * @type {string}
     * @memberof DocumentSummary
     */
    id?: string;
    /**
     * SignedAt is when the provider reported completion, in unix seconds. Absent
     * until then.
     * @type {number}
     * @memberof DocumentSummary
     */
    signedAt?: number;
    /**
     * Status is the lifecycle state: draft, out_for_signature, signed or voided.
     * There is deliberately no "legally valid" state — that is counsel's
     * determination, not the platform's.
     * @type {string}
     * @memberof DocumentSummary
     */
    status?: string;
    /**
     * TemplateID is the template it was rendered from.
     * @type {string}
     * @memberof DocumentSummary
     */
    templateId?: string;
    /**
     * TemplateVersion is WHICH version of that template rendered it, so the
     * document is reproducible and auditable.
     * @type {number}
     * @memberof DocumentSummary
     */
    templateVersion?: number;
    /**
     * Title is the document's title, inherited from the template.
     * @type {string}
     * @memberof DocumentSummary
     */
    title?: string;
    /**
     * UpdatedAt is when it last changed, in unix seconds.
     * @type {number}
     * @memberof DocumentSummary
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the DocumentSummary interface.
 */
export function instanceOfDocumentSummary(value: object): value is DocumentSummary {
    return true;
}

export function DocumentSummaryFromJSON(json: any): DocumentSummary {
    return DocumentSummaryFromJSONTyped(json, false);
}

export function DocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'esignProvider': json['esignProvider'] == null ? undefined : json['esignProvider'],
        'id': json['id'] == null ? undefined : json['id'],
        'signedAt': json['signedAt'] == null ? undefined : json['signedAt'],
        'status': json['status'] == null ? undefined : json['status'],
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'templateVersion': json['templateVersion'] == null ? undefined : json['templateVersion'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function DocumentSummaryToJSON(json: any): DocumentSummary {
    return DocumentSummaryToJSONTyped(json, false);
}

export function DocumentSummaryToJSONTyped(value?: DocumentSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'createdAt': value['createdAt'],
        'esignProvider': value['esignProvider'],
        'id': value['id'],
        'signedAt': value['signedAt'],
        'status': value['status'],
        'templateId': value['templateId'],
        'templateVersion': value['templateVersion'],
        'title': value['title'],
        'updatedAt': value['updatedAt'],
    };
}

