/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DropletIn
 */
export interface DropletIn {
    /**
     * Disk requests a PERMANENT resize that grows the disk. DO can never resize such a
     * droplet down again, so it defaults false — a CPU/RAM-only change, reversible.
     * @type {boolean}
     * @memberof DropletIn
     */
    disk?: boolean;
    /**
     * ID is the DO droplet id, from the path. Numeric.
     * @type {string}
     * @memberof DropletIn
     */
    id?: string;
    /**
     * Size is the target DigitalOcean size slug on resize, e.g. "s-4vcpu-8gb".
     * @type {string}
     * @memberof DropletIn
     */
    size?: string;
}

/**
 * Check if a given object implements the DropletIn interface.
 */
export function instanceOfDropletIn(value: object): value is DropletIn {
    return true;
}

export function DropletInFromJSON(json: any): DropletIn {
    return DropletInFromJSONTyped(json, false);
}

export function DropletInFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropletIn {
    if (json == null) {
        return json;
    }
    return {
        
        'disk': json['disk'] == null ? undefined : json['disk'],
        'id': json['id'] == null ? undefined : json['id'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function DropletInToJSON(json: any): DropletIn {
    return DropletInToJSONTyped(json, false);
}

export function DropletInToJSONTyped(value?: DropletIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disk': value['disk'],
        'id': value['id'],
        'size': value['size'],
    };
}

