/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EsignUploadIn
 */
export interface EsignUploadIn {
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    externalId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    message?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    pdfBase64?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    signingOrder?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    subject?: any | null;
    /**
     * 
     * @type {any}
     * @memberof EsignUploadIn
     */
    title?: any | null;
}

/**
 * Check if a given object implements the EsignUploadIn interface.
 */
export function instanceOfEsignUploadIn(value: object): value is EsignUploadIn {
    return true;
}

export function EsignUploadInFromJSON(json: any): EsignUploadIn {
    return EsignUploadInFromJSONTyped(json, false);
}

export function EsignUploadInFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsignUploadIn {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'message': json['message'] == null ? undefined : json['message'],
        'pdfBase64': json['pdfBase64'] == null ? undefined : json['pdfBase64'],
        'signingOrder': json['signingOrder'] == null ? undefined : json['signingOrder'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function EsignUploadInToJSON(json: any): EsignUploadIn {
    return EsignUploadInToJSONTyped(json, false);
}

export function EsignUploadInToJSONTyped(value?: EsignUploadIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
        'message': value['message'],
        'pdfBase64': value['pdfBase64'],
        'signingOrder': value['signingOrder'],
        'subject': value['subject'],
        'title': value['title'],
    };
}

