/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface FileInput
 */
export interface FileInput {
    /**
     * Content is the file's full text. Max 1 MiB per file; binary files should
     * simply be omitted rather than sent.
     * @type {string}
     * @memberof FileInput
     */
    content?: string;
    /**
     * Path is the file's repo-relative path, e.g. "internal/store/db.go".
     * @type {string}
     * @memberof FileInput
     */
    path?: string;
}

/**
 * Check if a given object implements the FileInput interface.
 */
export function instanceOfFileInput(value: object): value is FileInput {
    return true;
}

export function FileInputFromJSON(json: any): FileInput {
    return FileInputFromJSONTyped(json, false);
}

export function FileInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileInput {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function FileInputToJSON(json: any): FileInput {
    return FileInputToJSONTyped(json, false);
}

export function FileInputToJSONTyped(value?: FileInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'path': value['path'],
    };
}

