/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LegalFiling } from './LegalFiling.js';
import {
    LegalFilingFromJSON,
    LegalFilingFromJSONTyped,
    LegalFilingToJSON,
    LegalFilingToJSONTyped,
} from './LegalFiling.js';

/**
 * 
 * @export
 * @interface FilingReply
 */
export interface FilingReply {
    /**
     * Disclaimer is the boundary made visible on the wire.
     * @type {string}
     * @memberof FilingReply
     */
    disclaimer?: string;
    /**
     * Filing is the tracking record.
     * @type {LegalFiling}
     * @memberof FilingReply
     */
    filing?: LegalFiling;
}

/**
 * Check if a given object implements the FilingReply interface.
 */
export function instanceOfFilingReply(value: object): value is FilingReply {
    return true;
}

export function FilingReplyFromJSON(json: any): FilingReply {
    return FilingReplyFromJSONTyped(json, false);
}

export function FilingReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilingReply {
    if (json == null) {
        return json;
    }
    return {
        
        'disclaimer': json['disclaimer'] == null ? undefined : json['disclaimer'],
        'filing': json['filing'] == null ? undefined : LegalFilingFromJSON(json['filing']),
    };
}

export function FilingReplyToJSON(json: any): FilingReply {
    return FilingReplyToJSONTyped(json, false);
}

export function FilingReplyToJSONTyped(value?: FilingReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disclaimer': value['disclaimer'],
        'filing': LegalFilingToJSON(value['filing']),
    };
}

