/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface FinanceRevenue
 */
export interface FinanceRevenue {
    /**
     * 
     * @type {boolean}
     * @memberof FinanceRevenue
     */
    configured?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FinanceRevenue
     */
    creditsConsumedCents?: number;
    /**
     * 
     * @type {number}
     * @memberof FinanceRevenue
     */
    mrrCents?: number;
    /**
     * 
     * @type {number}
     * @memberof FinanceRevenue
     */
    totalRevenueCents?: number;
}

/**
 * Check if a given object implements the FinanceRevenue interface.
 */
export function instanceOfFinanceRevenue(value: object): value is FinanceRevenue {
    return true;
}

export function FinanceRevenueFromJSON(json: any): FinanceRevenue {
    return FinanceRevenueFromJSONTyped(json, false);
}

export function FinanceRevenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceRevenue {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'creditsConsumedCents': json['creditsConsumedCents'] == null ? undefined : json['creditsConsumedCents'],
        'mrrCents': json['mrrCents'] == null ? undefined : json['mrrCents'],
        'totalRevenueCents': json['totalRevenueCents'] == null ? undefined : json['totalRevenueCents'],
    };
}

export function FinanceRevenueToJSON(json: any): FinanceRevenue {
    return FinanceRevenueToJSONTyped(json, false);
}

export function FinanceRevenueToJSONTyped(value?: FinanceRevenue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'creditsConsumedCents': value['creditsConsumedCents'],
        'mrrCents': value['mrrCents'],
        'totalRevenueCents': value['totalRevenueCents'],
    };
}

