/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Session } from './Session.js';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
    SessionToJSONTyped,
} from './Session.js';

/**
 * 
 * @export
 * @interface GetAiSigninSessions200Response
 */
export interface GetAiSigninSessions200Response {
    /**
     * 
     * @type {Array<Session>}
     * @memberof GetAiSigninSessions200Response
     */
    data?: Array<Session>;
    /**
     * 
     * @type {any}
     * @memberof GetAiSigninSessions200Response
     */
    data2?: any | null;
    /**
     * Empty on success, the reason on failure.
     * @type {string}
     * @memberof GetAiSigninSessions200Response
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof GetAiSigninSessions200Response
     */
    status: GetAiSigninSessions200ResponseStatusEnum;
}


/**
 * @export
 */
export const GetAiSigninSessions200ResponseStatusEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type GetAiSigninSessions200ResponseStatusEnum = typeof GetAiSigninSessions200ResponseStatusEnum[keyof typeof GetAiSigninSessions200ResponseStatusEnum];


/**
 * Check if a given object implements the GetAiSigninSessions200Response interface.
 */
export function instanceOfGetAiSigninSessions200Response(value: object): value is GetAiSigninSessions200Response {
    if (!('msg' in value) || value['msg'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetAiSigninSessions200ResponseFromJSON(json: any): GetAiSigninSessions200Response {
    return GetAiSigninSessions200ResponseFromJSONTyped(json, false);
}

export function GetAiSigninSessions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAiSigninSessions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SessionFromJSON)),
        'data2': json['data2'] == null ? undefined : json['data2'],
        'msg': json['msg'],
        'status': json['status'],
    };
}

export function GetAiSigninSessions200ResponseToJSON(json: any): GetAiSigninSessions200Response {
    return GetAiSigninSessions200ResponseToJSONTyped(json, false);
}

export function GetAiSigninSessions200ResponseToJSONTyped(value?: GetAiSigninSessions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SessionToJSON)),
        'data2': value['data2'],
        'msg': value['msg'],
        'status': value['status'],
    };
}

