/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GithubForkOut
 */
export interface GithubForkOut {
    /**
     * 
     * @type {string}
     * @memberof GithubForkOut
     */
    cloneUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubForkOut
     */
    defaultBranch?: string;
    /**
     * Existing reports that the fork was already there. GitHub answers 202 either
     * way, so without this a caller cannot tell "made you one" from "you had one".
     * @type {boolean}
     * @memberof GithubForkOut
     */
    existing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GithubForkOut
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubForkOut
     */
    htmlUrl?: string;
}

/**
 * Check if a given object implements the GithubForkOut interface.
 */
export function instanceOfGithubForkOut(value: object): value is GithubForkOut {
    return true;
}

export function GithubForkOutFromJSON(json: any): GithubForkOut {
    return GithubForkOutFromJSONTyped(json, false);
}

export function GithubForkOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubForkOut {
    if (json == null) {
        return json;
    }
    return {
        
        'cloneUrl': json['clone_url'] == null ? undefined : json['clone_url'],
        'defaultBranch': json['default_branch'] == null ? undefined : json['default_branch'],
        'existing': json['existing'] == null ? undefined : json['existing'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'htmlUrl': json['html_url'] == null ? undefined : json['html_url'],
    };
}

export function GithubForkOutToJSON(json: any): GithubForkOut {
    return GithubForkOutToJSONTyped(json, false);
}

export function GithubForkOutToJSONTyped(value?: GithubForkOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clone_url': value['cloneUrl'],
        'default_branch': value['defaultBranch'],
        'existing': value['existing'],
        'full_name': value['fullName'],
        'html_url': value['htmlUrl'],
    };
}

