/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GithubRepoView } from './GithubRepoView.js';
import {
    GithubRepoViewFromJSON,
    GithubRepoViewFromJSONTyped,
    GithubRepoViewToJSON,
    GithubRepoViewToJSONTyped,
} from './GithubRepoView.js';

/**
 * 
 * @export
 * @interface GithubReposOut
 */
export interface GithubReposOut {
    /**
     * Repos is every repo the installation grants. Never null; [] when none.
     * @type {Array<GithubRepoView>}
     * @memberof GithubReposOut
     */
    repos?: Array<GithubRepoView>;
    /**
     * Unread names the connected accounts this answer could NOT read, so a short
     * list is distinguishable from a complete one. Absent when the answer is whole.
     * 
     * The fan-out is per installation, and one account failing used to be dropped
     * in silence: the response stayed 200 and simply carried fewer repositories,
     * erroring only when EVERY account failed. Measured, twice in a row, minutes
     * apart: 1475 repositories, then 1157 — a whole installation missing with
     * nothing in the answer to say so. Anything driven off the list then
     * under-covers and reports success, which is the failure this field ends.
     * @type {Array<string>}
     * @memberof GithubReposOut
     */
    unread?: Array<string>;
}

/**
 * Check if a given object implements the GithubReposOut interface.
 */
export function instanceOfGithubReposOut(value: object): value is GithubReposOut {
    return true;
}

export function GithubReposOutFromJSON(json: any): GithubReposOut {
    return GithubReposOutFromJSONTyped(json, false);
}

export function GithubReposOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubReposOut {
    if (json == null) {
        return json;
    }
    return {
        
        'repos': json['repos'] == null ? undefined : ((json['repos'] as Array<any>).map(GithubRepoViewFromJSON)),
        'unread': json['unread'] == null ? undefined : json['unread'],
    };
}

export function GithubReposOutToJSON(json: any): GithubReposOut {
    return GithubReposOutToJSONTyped(json, false);
}

export function GithubReposOutToJSONTyped(value?: GithubReposOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'repos': value['repos'] == null ? undefined : ((value['repos'] as Array<any>).map(GithubRepoViewToJSON)),
        'unread': value['unread'],
    };
}

