/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GitlabProjectView } from './GitlabProjectView.js';
import {
    GitlabProjectViewFromJSON,
    GitlabProjectViewFromJSONTyped,
    GitlabProjectViewToJSON,
    GitlabProjectViewToJSONTyped,
} from './GitlabProjectView.js';

/**
 * 
 * @export
 * @interface GitlabProjectsOut
 */
export interface GitlabProjectsOut {
    /**
     * Account is the connected GitLab username, so a client can label the list
     * without a second call. Empty when the connection recorded none.
     * @type {string}
     * @memberof GitlabProjectsOut
     */
    account?: string;
    /**
     * Projects is every project the token reaches, newest activity first. Never
     * null; [] when the account has none.
     * @type {Array<GitlabProjectView>}
     * @memberof GitlabProjectsOut
     */
    projects?: Array<GitlabProjectView>;
}

/**
 * Check if a given object implements the GitlabProjectsOut interface.
 */
export function instanceOfGitlabProjectsOut(value: object): value is GitlabProjectsOut {
    return true;
}

export function GitlabProjectsOutFromJSON(json: any): GitlabProjectsOut {
    return GitlabProjectsOutFromJSONTyped(json, false);
}

export function GitlabProjectsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitlabProjectsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(GitlabProjectViewFromJSON)),
    };
}

export function GitlabProjectsOutToJSON(json: any): GitlabProjectsOut {
    return GitlabProjectsOutToJSONTyped(json, false);
}

export function GitlabProjectsOutToJSONTyped(value?: GitlabProjectsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(GitlabProjectViewToJSON)),
    };
}

