/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GpuAlertList
 */
export interface GpuAlertList {
    /**
     * Alerts is always empty, and typed as a raw list because Visor exposes no
     * alert inventory for this surface to shape: there is nothing to describe
     * until there is something to return.
     * @type {Array<object>}
     * @memberof GpuAlertList
     */
    alerts?: Array<object>;
}

/**
 * Check if a given object implements the GpuAlertList interface.
 */
export function instanceOfGpuAlertList(value: object): value is GpuAlertList {
    return true;
}

export function GpuAlertListFromJSON(json: any): GpuAlertList {
    return GpuAlertListFromJSONTyped(json, false);
}

export function GpuAlertListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuAlertList {
    if (json == null) {
        return json;
    }
    return {
        
        'alerts': json['alerts'] == null ? undefined : json['alerts'],
    };
}

export function GpuAlertListToJSON(json: any): GpuAlertList {
    return GpuAlertListToJSONTyped(json, false);
}

export function GpuAlertListToJSONTyped(value?: GpuAlertList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alerts': value['alerts'],
    };
}

