/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GraphResolveIn
 */
export interface GraphResolveIn {
    /**
     * AsOf is the instant to answer at, RFC 3339. Absent means now.
     * @type {string}
     * @memberof GraphResolveIn
     */
    asOf?: string;
    /**
     * Entity is the thing to answer about. Required.
     * @type {string}
     * @memberof GraphResolveIn
     */
    entity?: string;
    /**
     * Relation is the one relation to settle. Required: this answers a single
     * (entity, relation) pair, never a whole entity at once.
     * @type {string}
     * @memberof GraphResolveIn
     */
    relation?: string;
}

/**
 * Check if a given object implements the GraphResolveIn interface.
 */
export function instanceOfGraphResolveIn(value: object): value is GraphResolveIn {
    return true;
}

export function GraphResolveInFromJSON(json: any): GraphResolveIn {
    return GraphResolveInFromJSONTyped(json, false);
}

export function GraphResolveInFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphResolveIn {
    if (json == null) {
        return json;
    }
    return {
        
        'asOf': json['as_of'] == null ? undefined : json['as_of'],
        'entity': json['entity'] == null ? undefined : json['entity'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function GraphResolveInToJSON(json: any): GraphResolveIn {
    return GraphResolveInToJSONTyped(json, false);
}

export function GraphResolveInToJSONTyped(value?: GraphResolveIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'as_of': value['asOf'],
        'entity': value['entity'],
        'relation': value['relation'],
    };
}

