/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HelpArticleCard
 */
export interface HelpArticleCard {
    /**
     * Category is the name of the knowledge-base section the article sits in, or
     * empty when it is filed under none.
     * @type {string}
     * @memberof HelpArticleCard
     */
    category?: string;
    /**
     * Excerpt is the short summary the author wrote for listings, or empty.
     * @type {string}
     * @memberof HelpArticleCard
     */
    excerpt?: string;
    /**
     * Slug is the article's stable public identifier and the path segment
     * /v1/help/articles/{slug} addresses it by.
     * @type {string}
     * @memberof HelpArticleCard
     */
    slug?: string;
    /**
     * Title is the article's headline.
     * @type {string}
     * @memberof HelpArticleCard
     */
    title?: string;
    /**
     * UpdatedAt is the unix second the article was last written, in the help
     * center's own store.
     * @type {number}
     * @memberof HelpArticleCard
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the HelpArticleCard interface.
 */
export function instanceOfHelpArticleCard(value: object): value is HelpArticleCard {
    return true;
}

export function HelpArticleCardFromJSON(json: any): HelpArticleCard {
    return HelpArticleCardFromJSONTyped(json, false);
}

export function HelpArticleCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelpArticleCard {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function HelpArticleCardToJSON(json: any): HelpArticleCard {
    return HelpArticleCardToJSONTyped(json, false);
}

export function HelpArticleCardToJSONTyped(value?: HelpArticleCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'excerpt': value['excerpt'],
        'slug': value['slug'],
        'title': value['title'],
        'updatedAt': value['updatedAt'],
    };
}

