/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HelpCategory
 */
export interface HelpCategory {
    /**
     * Description is the section's blurb, or empty.
     * @type {string}
     * @memberof HelpCategory
     */
    description?: string;
    /**
     * Name is the section's name, and the value an article's category matches.
     * @type {string}
     * @memberof HelpCategory
     */
    name?: string;
}

/**
 * Check if a given object implements the HelpCategory interface.
 */
export function instanceOfHelpCategory(value: object): value is HelpCategory {
    return true;
}

export function HelpCategoryFromJSON(json: any): HelpCategory {
    return HelpCategoryFromJSONTyped(json, false);
}

export function HelpCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelpCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function HelpCategoryToJSON(json: any): HelpCategory {
    return HelpCategoryToJSONTyped(json, false);
}

export function HelpCategoryToJSONTyped(value?: HelpCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
    };
}

