/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IamAuditlogsInput
 */
export interface IamAuditlogsInput {
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    clientIp?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    createdTime?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IamAuditlogsInput
     */
    isTriggered?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    requestUri?: string;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    response?: string;
    /**
     * 
     * @type {number}
     * @memberof IamAuditlogsInput
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof IamAuditlogsInput
     */
    user?: string;
}

/**
 * Check if a given object implements the IamAuditlogsInput interface.
 */
export function instanceOfIamAuditlogsInput(value: object): value is IamAuditlogsInput {
    return true;
}

export function IamAuditlogsInputFromJSON(json: any): IamAuditlogsInput {
    return IamAuditlogsInputFromJSONTyped(json, false);
}

export function IamAuditlogsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamAuditlogsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'clientIp': json['clientIp'] == null ? undefined : json['clientIp'],
        'createdTime': json['createdTime'] == null ? undefined : json['createdTime'],
        'isTriggered': json['isTriggered'] == null ? undefined : json['isTriggered'],
        'language': json['language'] == null ? undefined : json['language'],
        'method': json['method'] == null ? undefined : json['method'],
        'name': json['name'] == null ? undefined : json['name'],
        'object': json['object'] == null ? undefined : json['object'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'requestUri': json['requestUri'] == null ? undefined : json['requestUri'],
        'response': json['response'] == null ? undefined : json['response'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function IamAuditlogsInputToJSON(json: any): IamAuditlogsInput {
    return IamAuditlogsInputToJSONTyped(json, false);
}

export function IamAuditlogsInputToJSONTyped(value?: IamAuditlogsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'clientIp': value['clientIp'],
        'createdTime': value['createdTime'],
        'isTriggered': value['isTriggered'],
        'language': value['language'],
        'method': value['method'],
        'name': value['name'],
        'object': value['object'],
        'organization': value['organization'],
        'owner': value['owner'],
        'requestUri': value['requestUri'],
        'response': value['response'],
        'statusCode': value['statusCode'],
        'user': value['user'],
    };
}

