/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IamAssumeBody
 */
export interface IamAssumeBody {
    /**
     * 
     * @type {string}
     * @memberof IamAssumeBody
     */
    org?: string;
}

/**
 * Check if a given object implements the IamAssumeBody interface.
 */
export function instanceOfIamAssumeBody(value: object): value is IamAssumeBody {
    return true;
}

export function IamAssumeBodyFromJSON(json: any): IamAssumeBody {
    return IamAssumeBodyFromJSONTyped(json, false);
}

export function IamAssumeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamAssumeBody {
    if (json == null) {
        return json;
    }
    return {
        
        'org': json['org'] == null ? undefined : json['org'],
    };
}

export function IamAssumeBodyToJSON(json: any): IamAssumeBody {
    return IamAssumeBodyToJSONTyped(json, false);
}

export function IamAssumeBodyToJSONTyped(value?: IamAssumeBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org': value['org'],
    };
}

