/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IamPerson
 */
export interface IamPerson {
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IamPerson
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    passwordType?: string;
    /**
     * 
     * @type {string}
     * @memberof IamPerson
     */
    phone?: string;
}

/**
 * Check if a given object implements the IamPerson interface.
 */
export function instanceOfIamPerson(value: object): value is IamPerson {
    return true;
}

export function IamPersonFromJSON(json: any): IamPerson {
    return IamPersonFromJSONTyped(json, false);
}

export function IamPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'name': json['name'] == null ? undefined : json['name'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'password': json['password'] == null ? undefined : json['password'],
        'passwordType': json['passwordType'] == null ? undefined : json['passwordType'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function IamPersonToJSON(json: any): IamPerson {
    return IamPersonToJSONTyped(json, false);
}

export function IamPersonToJSONTyped(value?: IamPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'email': value['email'],
        'isAdmin': value['isAdmin'],
        'name': value['name'],
        'owner': value['owner'],
        'password': value['password'],
        'passwordType': value['passwordType'],
        'phone': value['phone'],
    };
}

