/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IamRole } from './IamRole.js';
import {
    IamRoleFromJSON,
    IamRoleFromJSONTyped,
    IamRoleToJSON,
    IamRoleToJSONTyped,
} from './IamRole.js';

/**
 * 
 * @export
 * @interface IamRolesListOutput
 */
export interface IamRolesListOutput {
    /**
     * 
     * @type {Array<IamRole>}
     * @memberof IamRolesListOutput
     */
    roles?: Array<IamRole>;
    /**
     * 
     * @type {number}
     * @memberof IamRolesListOutput
     */
    total?: number;
}

/**
 * Check if a given object implements the IamRolesListOutput interface.
 */
export function instanceOfIamRolesListOutput(value: object): value is IamRolesListOutput {
    return true;
}

export function IamRolesListOutputFromJSON(json: any): IamRolesListOutput {
    return IamRolesListOutputFromJSONTyped(json, false);
}

export function IamRolesListOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamRolesListOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(IamRoleFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function IamRolesListOutputToJSON(json: any): IamRolesListOutput {
    return IamRolesListOutputToJSONTyped(json, false);
}

export function IamRolesListOutputToJSONTyped(value?: IamRolesListOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(IamRoleToJSON)),
        'total': value['total'],
    };
}

