/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { IamWebauthnCredential } from './IamWebauthnCredential.js';
import {
    IamWebauthnCredentialFromJSON,
    IamWebauthnCredentialFromJSONTyped,
    IamWebauthnCredentialToJSON,
    IamWebauthnCredentialToJSONTyped,
} from './IamWebauthnCredential.js';

/**
 * 
 * @export
 * @interface IamWebauthnCredentialMutationResult
 */
export interface IamWebauthnCredentialMutationResult {
    /**
     * 
     * @type {boolean}
     * @memberof IamWebauthnCredentialMutationResult
     */
    affected?: boolean;
    /**
     * 
     * @type {IamWebauthnCredential}
     * @memberof IamWebauthnCredentialMutationResult
     */
    webauthnCredential?: IamWebauthnCredential;
}

/**
 * Check if a given object implements the IamWebauthnCredentialMutationResult interface.
 */
export function instanceOfIamWebauthnCredentialMutationResult(value: object): value is IamWebauthnCredentialMutationResult {
    return true;
}

export function IamWebauthnCredentialMutationResultFromJSON(json: any): IamWebauthnCredentialMutationResult {
    return IamWebauthnCredentialMutationResultFromJSONTyped(json, false);
}

export function IamWebauthnCredentialMutationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamWebauthnCredentialMutationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'affected': json['affected'] == null ? undefined : json['affected'],
        'webauthnCredential': json['webauthnCredential'] == null ? undefined : IamWebauthnCredentialFromJSON(json['webauthnCredential']),
    };
}

export function IamWebauthnCredentialMutationResultToJSON(json: any): IamWebauthnCredentialMutationResult {
    return IamWebauthnCredentialMutationResultToJSONTyped(json, false);
}

export function IamWebauthnCredentialMutationResultToJSONTyped(value?: IamWebauthnCredentialMutationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affected': value['affected'],
        'webauthnCredential': IamWebauthnCredentialToJSON(value['webauthnCredential']),
    };
}

