/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ImageOrigin
 */
export interface ImageOrigin {
    /**
     * Repository is the image repository. Required for source `image`.
     * @type {string}
     * @memberof ImageOrigin
     */
    repository?: string;
    /**
     * Tag is the image tag to deploy; `latest` when omitted.
     * @type {string}
     * @memberof ImageOrigin
     */
    tag?: string;
}

/**
 * Check if a given object implements the ImageOrigin interface.
 */
export function instanceOfImageOrigin(value: object): value is ImageOrigin {
    return true;
}

export function ImageOriginFromJSON(json: any): ImageOrigin {
    return ImageOriginFromJSONTyped(json, false);
}

export function ImageOriginFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageOrigin {
    if (json == null) {
        return json;
    }
    return {
        
        'repository': json['repository'] == null ? undefined : json['repository'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function ImageOriginToJSON(json: any): ImageOrigin {
    return ImageOriginToJSONTyped(json, false);
}

export function ImageOriginToJSONTyped(value?: ImageOrigin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'repository': value['repository'],
        'tag': value['tag'],
    };
}

