/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Extracted } from './Extracted.js';
import {
    ExtractedFromJSON,
    ExtractedFromJSONTyped,
    ExtractedToJSON,
    ExtractedToJSONTyped,
} from './Extracted.js';

/**
 * 
 * @export
 * @interface InboxItem
 */
export interface InboxItem {
    /**
     * Category is the expense account the scanner proposed, as a chart number — a
     * PROPOSAL, not a posting: nothing is booked until it is accepted.
     * @type {string}
     * @memberof InboxItem
     */
    category?: string;
    /**
     * Confidence is how sure the scanner is of that reading, and is the signal for
     * whether a person needs to check it before it is booked.
     * @type {string}
     * @memberof InboxItem
     */
    confidence?: string;
    /**
     * CreatedAt is when the document was uploaded.
     * @type {string}
     * @memberof InboxItem
     */
    createdAt?: string;
    /**
     * Extracted is what the scanner read off the document. Absent until it has been
     * scanned, so its absence is "not read yet", never "nothing on it".
     * @type {Extracted}
     * @memberof InboxItem
     */
    extracted?: Extracted;
    /**
     * Filename is the name the document was uploaded under, for a person to
     * recognise it by. It is not part of the item's identity.
     * @type {string}
     * @memberof InboxItem
     */
    filename?: string;
    /**
     * ID is the CONTENT HASH of the uploaded bytes, which is what makes the queue
     * idempotent: re-uploading the same document returns this item rather than
     * adding a second one. It is also the id the scan of this document carries.
     * @type {string}
     * @memberof InboxItem
     */
    id?: string;
    /**
     * Status is where the document is in the queue — unsorted until the scanner has
     * read it, and thereafter whether it is waiting on a person or has been booked.
     * @type {string}
     * @memberof InboxItem
     */
    status?: string;
    /**
     * Vendor is the supplier the scanner identified, surfaced beside the item so a
     * queue renders without opening each document.
     * @type {string}
     * @memberof InboxItem
     */
    vendor?: string;
}

/**
 * Check if a given object implements the InboxItem interface.
 */
export function instanceOfInboxItem(value: object): value is InboxItem {
    return true;
}

export function InboxItemFromJSON(json: any): InboxItem {
    return InboxItemFromJSONTyped(json, false);
}

export function InboxItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxItem {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'extracted': json['extracted'] == null ? undefined : ExtractedFromJSON(json['extracted']),
        'filename': json['filename'] == null ? undefined : json['filename'],
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
    };
}

export function InboxItemToJSON(json: any): InboxItem {
    return InboxItemToJSONTyped(json, false);
}

export function InboxItemToJSONTyped(value?: InboxItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'confidence': value['confidence'],
        'createdAt': value['createdAt'],
        'extracted': ExtractedToJSON(value['extracted']),
        'filename': value['filename'],
        'id': value['id'],
        'status': value['status'],
        'vendor': value['vendor'],
    };
}

