/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LeaderRow } from './LeaderRow.js';
import {
    LeaderRowFromJSON,
    LeaderRowFromJSONTyped,
    LeaderRowToJSON,
    LeaderRowToJSONTyped,
} from './LeaderRow.js';

/**
 * 
 * @export
 * @interface Leaderboard
 */
export interface Leaderboard {
    /**
     * Benchmark is the catalog id these rows are about.
     * @type {string}
     * @memberof Leaderboard
     */
    benchmark?: string;
    /**
     * Rows is one per model, ordered by measured accuracy descending.
     * @type {Array<LeaderRow>}
     * @memberof Leaderboard
     */
    rows?: Array<LeaderRow>;
}

/**
 * Check if a given object implements the Leaderboard interface.
 */
export function instanceOfLeaderboard(value: object): value is Leaderboard {
    return true;
}

export function LeaderboardFromJSON(json: any): Leaderboard {
    return LeaderboardFromJSONTyped(json, false);
}

export function LeaderboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Leaderboard {
    if (json == null) {
        return json;
    }
    return {
        
        'benchmark': json['benchmark'] == null ? undefined : json['benchmark'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(LeaderRowFromJSON)),
    };
}

export function LeaderboardToJSON(json: any): Leaderboard {
    return LeaderboardToJSONTyped(json, false);
}

export function LeaderboardToJSONTyped(value?: Leaderboard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'benchmark': value['benchmark'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(LeaderRowToJSON)),
    };
}

