/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LevelView
 */
export interface LevelView {
    /**
     * DownlineCount is how many orgs sit exactly this many hops below the caller. It
     * is 0 in the schedule quoted to a caller that has not applied, which has no
     * downline to count.
     * @type {number}
     * @memberof LevelView
     */
    downlineCount?: number;
    /**
     * Level is the upline distance from the org whose spend is being shared: 1 is
     * the direct referrer, 2 and 3 the referrers above it. Nothing accrues past 3.
     * @type {number}
     * @memberof LevelView
     */
    level?: number;
    /**
     * RateBps is the commission paid at this level, in basis points OF Hanzo's
     * margin (2000 = 20% of margin, never of the customer's bill). Level 1 is the
     * affiliate's own negotiated rate; 2 and 3 are platform switches read live, so
     * this is the schedule actually in force, not one compiled in.
     * @type {number}
     * @memberof LevelView
     */
    rateBps?: number;
}

/**
 * Check if a given object implements the LevelView interface.
 */
export function instanceOfLevelView(value: object): value is LevelView {
    return true;
}

export function LevelViewFromJSON(json: any): LevelView {
    return LevelViewFromJSONTyped(json, false);
}

export function LevelViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): LevelView {
    if (json == null) {
        return json;
    }
    return {
        
        'downlineCount': json['downlineCount'] == null ? undefined : json['downlineCount'],
        'level': json['level'] == null ? undefined : json['level'],
        'rateBps': json['rateBps'] == null ? undefined : json['rateBps'],
    };
}

export function LevelViewToJSON(json: any): LevelView {
    return LevelViewToJSONTyped(json, false);
}

export function LevelViewToJSONTyped(value?: LevelView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downlineCount': value['downlineCount'],
        'level': value['level'],
        'rateBps': value['rateBps'],
    };
}

