/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LicensingDeviceSignals } from './LicensingDeviceSignals.js';
import {
    LicensingDeviceSignalsFromJSON,
    LicensingDeviceSignalsFromJSONTyped,
    LicensingDeviceSignalsToJSON,
    LicensingDeviceSignalsToJSONTyped,
} from './LicensingDeviceSignals.js';

/**
 * 
 * @export
 * @interface LicensingFingerprintRequest
 */
export interface LicensingFingerprintRequest {
    /**
     * Signals is the host material the client agent collected. Which fields
     * actually participate in the binding is deliberately unspecified — send
     * everything available and let the server decide.
     * @type {LicensingDeviceSignals}
     * @memberof LicensingFingerprintRequest
     */
    signals?: LicensingDeviceSignals;
}

/**
 * Check if a given object implements the LicensingFingerprintRequest interface.
 */
export function instanceOfLicensingFingerprintRequest(value: object): value is LicensingFingerprintRequest {
    return true;
}

export function LicensingFingerprintRequestFromJSON(json: any): LicensingFingerprintRequest {
    return LicensingFingerprintRequestFromJSONTyped(json, false);
}

export function LicensingFingerprintRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LicensingFingerprintRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'signals': json['signals'] == null ? undefined : LicensingDeviceSignalsFromJSON(json['signals']),
    };
}

export function LicensingFingerprintRequestToJSON(json: any): LicensingFingerprintRequest {
    return LicensingFingerprintRequestToJSONTyped(json, false);
}

export function LicensingFingerprintRequestToJSONTyped(value?: LicensingFingerprintRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signals': LicensingDeviceSignalsToJSON(value['signals']),
    };
}

