/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LicensingRevocationEntry
 */
export interface LicensingRevocationEntry {
    /**
     * 
     * @type {number}
     * @memberof LicensingRevocationEntry
     */
    at?: number;
    /**
     * 
     * @type {string}
     * @memberof LicensingRevocationEntry
     */
    by?: string;
    /**
     * 
     * @type {string}
     * @memberof LicensingRevocationEntry
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof LicensingRevocationEntry
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof LicensingRevocationEntry
     */
    value?: string;
}

/**
 * Check if a given object implements the LicensingRevocationEntry interface.
 */
export function instanceOfLicensingRevocationEntry(value: object): value is LicensingRevocationEntry {
    return true;
}

export function LicensingRevocationEntryFromJSON(json: any): LicensingRevocationEntry {
    return LicensingRevocationEntryFromJSONTyped(json, false);
}

export function LicensingRevocationEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LicensingRevocationEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'at': json['at'] == null ? undefined : json['at'],
        'by': json['by'] == null ? undefined : json['by'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function LicensingRevocationEntryToJSON(json: any): LicensingRevocationEntry {
    return LicensingRevocationEntryToJSONTyped(json, false);
}

export function LicensingRevocationEntryToJSONTyped(value?: LicensingRevocationEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'at': value['at'],
        'by': value['by'],
        'reason': value['reason'],
        'scope': value['scope'],
        'value': value['value'],
    };
}

