/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MakeIn
 */
export interface MakeIn {
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    ackPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    ackWait?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    deliverPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    durableName?: string;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    filterSubject?: string;
    /**
     * 
     * @type {number}
     * @memberof MakeIn
     */
    maxAckPending?: number;
    /**
     * 
     * @type {number}
     * @memberof MakeIn
     */
    maxDeliver?: number;
    /**
     * 
     * @type {number}
     * @memberof MakeIn
     */
    optStartSeq?: number;
    /**
     * 
     * @type {Date}
     * @memberof MakeIn
     */
    optStartTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof MakeIn
     */
    replayPolicy?: string;
    /**
     * Stream is the stream name, from the path.
     * @type {string}
     * @memberof MakeIn
     */
    stream?: string;
}

/**
 * Check if a given object implements the MakeIn interface.
 */
export function instanceOfMakeIn(value: object): value is MakeIn {
    return true;
}

export function MakeInFromJSON(json: any): MakeIn {
    return MakeInFromJSONTyped(json, false);
}

export function MakeInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MakeIn {
    if (json == null) {
        return json;
    }
    return {
        
        'ackPolicy': json['ack_policy'] == null ? undefined : json['ack_policy'],
        'ackWait': json['ack_wait'] == null ? undefined : json['ack_wait'],
        'deliverPolicy': json['deliver_policy'] == null ? undefined : json['deliver_policy'],
        'description': json['description'] == null ? undefined : json['description'],
        'durableName': json['durable_name'] == null ? undefined : json['durable_name'],
        'filterSubject': json['filter_subject'] == null ? undefined : json['filter_subject'],
        'maxAckPending': json['max_ack_pending'] == null ? undefined : json['max_ack_pending'],
        'maxDeliver': json['max_deliver'] == null ? undefined : json['max_deliver'],
        'optStartSeq': json['opt_start_seq'] == null ? undefined : json['opt_start_seq'],
        'optStartTime': json['opt_start_time'] == null ? undefined : (new Date(json['opt_start_time'])),
        'replayPolicy': json['replay_policy'] == null ? undefined : json['replay_policy'],
        'stream': json['stream'] == null ? undefined : json['stream'],
    };
}

export function MakeInToJSON(json: any): MakeIn {
    return MakeInToJSONTyped(json, false);
}

export function MakeInToJSONTyped(value?: MakeIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ack_policy': value['ackPolicy'],
        'ack_wait': value['ackWait'],
        'deliver_policy': value['deliverPolicy'],
        'description': value['description'],
        'durable_name': value['durableName'],
        'filter_subject': value['filterSubject'],
        'max_ack_pending': value['maxAckPending'],
        'max_deliver': value['maxDeliver'],
        'opt_start_seq': value['optStartSeq'],
        'opt_start_time': value['optStartTime'] == null ? undefined : ((value['optStartTime']).toISOString()),
        'replay_policy': value['replayPolicy'],
        'stream': value['stream'],
    };
}

