/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MirrorTargetReq
 */
export interface MirrorTargetReq {
    /**
     * Host is an optional assertion of the target's hostname. The authoritative
     * host is the one in URL; a value that disagrees with it is refused.
     * @type {string}
     * @memberof MirrorTargetReq
     */
    host?: string;
    /**
     * Name is the repo whose advanced refs are pushed downstream, from the :name
     * path segment.
     * @type {string}
     * @memberof MirrorTargetReq
     */
    name?: string;
    /**
     * URL is the downstream https git remote. Must be https to an allowlisted
     * host (github.com / gitlab.com); any embedded credentials are stripped.
     * Required.
     * @type {string}
     * @memberof MirrorTargetReq
     */
    url?: string;
}

/**
 * Check if a given object implements the MirrorTargetReq interface.
 */
export function instanceOfMirrorTargetReq(value: object): value is MirrorTargetReq {
    return true;
}

export function MirrorTargetReqFromJSON(json: any): MirrorTargetReq {
    return MirrorTargetReqFromJSONTyped(json, false);
}

export function MirrorTargetReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): MirrorTargetReq {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'] == null ? undefined : json['host'],
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function MirrorTargetReqToJSON(json: any): MirrorTargetReq {
    return MirrorTargetReqToJSONTyped(json, false);
}

export function MirrorTargetReqToJSONTyped(value?: MirrorTargetReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'name': value['name'],
        'url': value['url'],
    };
}

