/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MyReferralView
 */
export interface MyReferralView {
    /**
     * CreatedAt is when the referral was recorded, as a Unix timestamp.
     * @type {number}
     * @memberof MyReferralView
     */
    createdAt?: number;
    /**
     * ID is the referral's handle.
     * @type {string}
     * @memberof MyReferralView
     */
    id?: string;
    /**
     * QualifiedAt is when the referee first made metered spend, as a Unix
     * timestamp; 0 while the referral is still pending.
     * @type {number}
     * @memberof MyReferralView
     */
    qualifiedAt?: number;
    /**
     * Referee is the org that signed up with my code.
     * @type {string}
     * @memberof MyReferralView
     */
    referee?: string;
    /**
     * Status is the referral's lifecycle state: "signup" until the referee makes
     * metered spend, then "qualified".
     * @type {string}
     * @memberof MyReferralView
     */
    status?: string;
}

/**
 * Check if a given object implements the MyReferralView interface.
 */
export function instanceOfMyReferralView(value: object): value is MyReferralView {
    return true;
}

export function MyReferralViewFromJSON(json: any): MyReferralView {
    return MyReferralViewFromJSONTyped(json, false);
}

export function MyReferralViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyReferralView {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'qualifiedAt': json['qualifiedAt'] == null ? undefined : json['qualifiedAt'],
        'referee': json['referee'] == null ? undefined : json['referee'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MyReferralViewToJSON(json: any): MyReferralView {
    return MyReferralViewToJSONTyped(json, false);
}

export function MyReferralViewToJSONTyped(value?: MyReferralView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'id': value['id'],
        'qualifiedAt': value['qualifiedAt'],
        'referee': value['referee'],
        'status': value['status'],
    };
}

