/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yToggle
 */
export interface O11yO11yToggle {
    /**
     * Enabled says whether the feature is on.
     * @type {boolean}
     * @memberof O11yO11yToggle
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the O11yO11yToggle interface.
 */
export function instanceOfO11yO11yToggle(value: object): value is O11yO11yToggle {
    return true;
}

export function O11yO11yToggleFromJSON(json: any): O11yO11yToggle {
    return O11yO11yToggleFromJSONTyped(json, false);
}

export function O11yO11yToggleFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yToggle {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function O11yO11yToggleToJSON(json: any): O11yO11yToggle {
    return O11yO11yToggleToJSONTyped(json, false);
}

export function O11yO11yToggleToJSONTyped(value?: O11yO11yToggle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

