/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yLLMAnnotation
 */
export interface O11yO11yLLMAnnotation {
    /**
     * Author is who wrote it.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    author?: string;
    /**
     * Content is the note itself.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    content?: string;
    /**
     * CreatedAt is when the annotation was stored.
     * @type {Date}
     * @memberof O11yO11yLLMAnnotation
     */
    createdAt?: Date;
    /**
     * ID is the annotation's id.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    id?: string;
    /**
     * ObservationID is the observation the annotation attaches to, when narrowed.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    observationId?: string;
    /**
     * Queue is the review queue the annotation sits in, when queued.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    queue?: string;
    /**
     * Status is the annotation's review status, e.g. PENDING.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    status?: string;
    /**
     * TraceID is the trace the annotation attaches to.
     * @type {string}
     * @memberof O11yO11yLLMAnnotation
     */
    traceId?: string;
    /**
     * UpdatedAt is when the annotation last changed.
     * @type {Date}
     * @memberof O11yO11yLLMAnnotation
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the O11yO11yLLMAnnotation interface.
 */
export function instanceOfO11yO11yLLMAnnotation(value: object): value is O11yO11yLLMAnnotation {
    return true;
}

export function O11yO11yLLMAnnotationFromJSON(json: any): O11yO11yLLMAnnotation {
    return O11yO11yLLMAnnotationFromJSONTyped(json, false);
}

export function O11yO11yLLMAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yLLMAnnotation {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : json['author'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'observationId': json['observationId'] == null ? undefined : json['observationId'],
        'queue': json['queue'] == null ? undefined : json['queue'],
        'status': json['status'] == null ? undefined : json['status'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function O11yO11yLLMAnnotationToJSON(json: any): O11yO11yLLMAnnotation {
    return O11yO11yLLMAnnotationToJSONTyped(json, false);
}

export function O11yO11yLLMAnnotationToJSONTyped(value?: O11yO11yLLMAnnotation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': value['author'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'id': value['id'],
        'observationId': value['observationId'],
        'queue': value['queue'],
        'status': value['status'],
        'traceId': value['traceId'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

