/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yAttributeMapping
 */
export interface O11yO11yAttributeMapping {
    /**
     * Email is the key carrying the email; defaults to "email".
     * @type {string}
     * @memberof O11yO11yAttributeMapping
     */
    email?: string;
    /**
     * Groups is the key carrying the group list; defaults to "groups".
     * @type {string}
     * @memberof O11yO11yAttributeMapping
     */
    groups?: string;
    /**
     * Name is the key carrying the display name; defaults to "name".
     * @type {string}
     * @memberof O11yO11yAttributeMapping
     */
    name?: string;
    /**
     * Role is the key carrying the role; defaults to "role".
     * @type {string}
     * @memberof O11yO11yAttributeMapping
     */
    role?: string;
}

/**
 * Check if a given object implements the O11yO11yAttributeMapping interface.
 */
export function instanceOfO11yO11yAttributeMapping(value: object): value is O11yO11yAttributeMapping {
    return true;
}

export function O11yO11yAttributeMappingFromJSON(json: any): O11yO11yAttributeMapping {
    return O11yO11yAttributeMappingFromJSONTyped(json, false);
}

export function O11yO11yAttributeMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yAttributeMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'groups': json['groups'] == null ? undefined : json['groups'],
        'name': json['name'] == null ? undefined : json['name'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function O11yO11yAttributeMappingToJSON(json: any): O11yO11yAttributeMapping {
    return O11yO11yAttributeMappingToJSONTyped(json, false);
}

export function O11yO11yAttributeMappingToJSONTyped(value?: O11yO11yAttributeMapping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'groups': value['groups'],
        'name': value['name'],
        'role': value['role'],
    };
}

