/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yFilterKey
 */
export interface O11yO11yFilterKey {
    /**
     * DataType is the attribute's value type — string, int64, float64 or bool.
     * @type {string}
     * @memberof O11yO11yFilterKey
     */
    dataType?: string;
    /**
     * IsColumn marks an attribute stored as its own column.
     * @type {boolean}
     * @memberof O11yO11yFilterKey
     */
    isColumn?: boolean;
    /**
     * IsJSON marks an attribute read out of a JSON body.
     * @type {boolean}
     * @memberof O11yO11yFilterKey
     */
    isJSON?: boolean;
    /**
     * Key is the attribute name.
     * @type {string}
     * @memberof O11yO11yFilterKey
     */
    key?: string;
    /**
     * Type says where the attribute lives — tag or resource.
     * @type {string}
     * @memberof O11yO11yFilterKey
     */
    type?: string;
}

/**
 * Check if a given object implements the O11yO11yFilterKey interface.
 */
export function instanceOfO11yO11yFilterKey(value: object): value is O11yO11yFilterKey {
    return true;
}

export function O11yO11yFilterKeyFromJSON(json: any): O11yO11yFilterKey {
    return O11yO11yFilterKeyFromJSONTyped(json, false);
}

export function O11yO11yFilterKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yFilterKey {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['dataType'] == null ? undefined : json['dataType'],
        'isColumn': json['isColumn'] == null ? undefined : json['isColumn'],
        'isJSON': json['isJSON'] == null ? undefined : json['isJSON'],
        'key': json['key'] == null ? undefined : json['key'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function O11yO11yFilterKeyToJSON(json: any): O11yO11yFilterKey {
    return O11yO11yFilterKeyToJSONTyped(json, false);
}

export function O11yO11yFilterKeyToJSONTyped(value?: O11yO11yFilterKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataType': value['dataType'],
        'isColumn': value['isColumn'],
        'isJSON': value['isJSON'],
        'key': value['key'],
        'type': value['type'],
    };
}

