/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yTraceSpanWindow
 */
export interface O11yO11yTraceSpanWindow {
    /**
     * Columns names the fields each row carries, in row order.
     * @type {Array<string>}
     * @memberof O11yO11yTraceSpanWindow
     */
    columns?: Array<string>;
    /**
     * EndTimestampMillis is when it closes.
     * @type {number}
     * @memberof O11yO11yTraceSpanWindow
     */
    endTimestampMillis?: number;
    /**
     * Events are the rows, each positionally matching Columns.
     * @type {Array<Array<object>>}
     * @memberof O11yO11yTraceSpanWindow
     */
    events?: Array<Array<object>>;
    /**
     * IsSubTree says the window is a subtree of the trace rather than the whole
     * of it.
     * @type {boolean}
     * @memberof O11yO11yTraceSpanWindow
     */
    isSubTree?: boolean;
    /**
     * StartTimestampMillis is when the window opens.
     * @type {number}
     * @memberof O11yO11yTraceSpanWindow
     */
    startTimestampMillis?: number;
}

/**
 * Check if a given object implements the O11yO11yTraceSpanWindow interface.
 */
export function instanceOfO11yO11yTraceSpanWindow(value: object): value is O11yO11yTraceSpanWindow {
    return true;
}

export function O11yO11yTraceSpanWindowFromJSON(json: any): O11yO11yTraceSpanWindow {
    return O11yO11yTraceSpanWindowFromJSONTyped(json, false);
}

export function O11yO11yTraceSpanWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yTraceSpanWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : json['columns'],
        'endTimestampMillis': json['endTimestampMillis'] == null ? undefined : json['endTimestampMillis'],
        'events': json['events'] == null ? undefined : json['events'],
        'isSubTree': json['isSubTree'] == null ? undefined : json['isSubTree'],
        'startTimestampMillis': json['startTimestampMillis'] == null ? undefined : json['startTimestampMillis'],
    };
}

export function O11yO11yTraceSpanWindowToJSON(json: any): O11yO11yTraceSpanWindow {
    return O11yO11yTraceSpanWindowToJSONTyped(json, false);
}

export function O11yO11yTraceSpanWindowToJSONTyped(value?: O11yO11yTraceSpanWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'endTimestampMillis': value['endTimestampMillis'],
        'events': value['events'],
        'isSubTree': value['isSubTree'],
        'startTimestampMillis': value['startTimestampMillis'],
    };
}

