/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yQuerybuildertypesv5OrderBy } from './O11yQuerybuildertypesv5OrderBy.js';
import {
    O11yQuerybuildertypesv5OrderByFromJSON,
    O11yQuerybuildertypesv5OrderByFromJSONTyped,
    O11yQuerybuildertypesv5OrderByToJSON,
    O11yQuerybuildertypesv5OrderByToJSONTyped,
} from './O11yQuerybuildertypesv5OrderBy.js';
import type { O11yGroupByKey } from './O11yGroupByKey.js';
import {
    O11yGroupByKeyFromJSON,
    O11yGroupByKeyFromJSONTyped,
    O11yGroupByKeyToJSON,
    O11yGroupByKeyToJSONTyped,
} from './O11yGroupByKey.js';
import type { O11yFilter } from './O11yFilter.js';
import {
    O11yFilterFromJSON,
    O11yFilterFromJSONTyped,
    O11yFilterToJSON,
    O11yFilterToJSONTyped,
} from './O11yFilter.js';

/**
 * 
 * @export
 * @interface O11yPostableVolumes
 */
export interface O11yPostableVolumes {
    /**
     * 
     * @type {number}
     * @memberof O11yPostableVolumes
     */
    end?: number;
    /**
     * 
     * @type {O11yFilter}
     * @memberof O11yPostableVolumes
     */
    filter?: O11yFilter;
    /**
     * 
     * @type {Array<O11yGroupByKey>}
     * @memberof O11yPostableVolumes
     */
    groupBy?: Array<O11yGroupByKey>;
    /**
     * 
     * @type {number}
     * @memberof O11yPostableVolumes
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPostableVolumes
     */
    offset?: number;
    /**
     * 
     * @type {O11yQuerybuildertypesv5OrderBy}
     * @memberof O11yPostableVolumes
     */
    orderBy?: O11yQuerybuildertypesv5OrderBy;
    /**
     * 
     * @type {number}
     * @memberof O11yPostableVolumes
     */
    start?: number;
}

/**
 * Check if a given object implements the O11yPostableVolumes interface.
 */
export function instanceOfO11yPostableVolumes(value: object): value is O11yPostableVolumes {
    return true;
}

export function O11yPostableVolumesFromJSON(json: any): O11yPostableVolumes {
    return O11yPostableVolumesFromJSONTyped(json, false);
}

export function O11yPostableVolumesFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yPostableVolumes {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'] == null ? undefined : json['end'],
        'filter': json['filter'] == null ? undefined : O11yFilterFromJSON(json['filter']),
        'groupBy': json['groupBy'] == null ? undefined : ((json['groupBy'] as Array<any>).map(O11yGroupByKeyFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'orderBy': json['orderBy'] == null ? undefined : O11yQuerybuildertypesv5OrderByFromJSON(json['orderBy']),
        'start': json['start'] == null ? undefined : json['start'],
    };
}

export function O11yPostableVolumesToJSON(json: any): O11yPostableVolumes {
    return O11yPostableVolumesToJSONTyped(json, false);
}

export function O11yPostableVolumesToJSONTyped(value?: O11yPostableVolumes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'],
        'filter': O11yFilterToJSON(value['filter']),
        'groupBy': value['groupBy'] == null ? undefined : ((value['groupBy'] as Array<any>).map(O11yGroupByKeyToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'orderBy': O11yQuerybuildertypesv5OrderByToJSON(value['orderBy']),
        'start': value['start'],
    };
}

