/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yAPIKey } from './O11yO11yAPIKey.js';
import {
    O11yO11yAPIKeyFromJSON,
    O11yO11yAPIKeyFromJSONTyped,
    O11yO11yAPIKeyToJSON,
    O11yO11yAPIKeyToJSONTyped,
} from './O11yO11yAPIKey.js';

/**
 * 
 * @export
 * @interface O11yO11yAPIKeysOut
 */
export interface O11yO11yAPIKeysOut {
    /**
     * Data holds the keys.
     * @type {Array<O11yO11yAPIKey>}
     * @memberof O11yO11yAPIKeysOut
     */
    data?: Array<O11yO11yAPIKey>;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yAPIKeysOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yAPIKeysOut interface.
 */
export function instanceOfO11yO11yAPIKeysOut(value: object): value is O11yO11yAPIKeysOut {
    return true;
}

export function O11yO11yAPIKeysOutFromJSON(json: any): O11yO11yAPIKeysOut {
    return O11yO11yAPIKeysOutFromJSONTyped(json, false);
}

export function O11yO11yAPIKeysOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yAPIKeysOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(O11yO11yAPIKeyFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yAPIKeysOutToJSON(json: any): O11yO11yAPIKeysOut {
    return O11yO11yAPIKeysOutToJSONTyped(json, false);
}

export function O11yO11yAPIKeysOutToJSONTyped(value?: O11yO11yAPIKeysOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(O11yO11yAPIKeyToJSON)),
        'status': value['status'],
    };
}

