/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11ySupportedSignals
 */
export interface O11ySupportedSignals {
    /**
     * 
     * @type {boolean}
     * @memberof O11ySupportedSignals
     */
    logs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof O11ySupportedSignals
     */
    metrics?: boolean;
}

/**
 * Check if a given object implements the O11ySupportedSignals interface.
 */
export function instanceOfO11ySupportedSignals(value: object): value is O11ySupportedSignals {
    return true;
}

export function O11ySupportedSignalsFromJSON(json: any): O11ySupportedSignals {
    return O11ySupportedSignalsFromJSONTyped(json, false);
}

export function O11ySupportedSignalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11ySupportedSignals {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'] == null ? undefined : json['logs'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
    };
}

export function O11ySupportedSignalsToJSON(json: any): O11ySupportedSignals {
    return O11ySupportedSignalsToJSONTyped(json, false);
}

export function O11ySupportedSignalsToJSONTyped(value?: O11ySupportedSignals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'],
        'metrics': value['metrics'],
    };
}

