/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yToggle } from './O11yO11yToggle.js';
import {
    O11yO11yToggleFromJSON,
    O11yO11yToggleFromJSONTyped,
    O11yO11yToggleToJSON,
    O11yO11yToggleToJSONTyped,
} from './O11yO11yToggle.js';

/**
 * 
 * @export
 * @interface O11yO11yIdentN
 */
export interface O11yO11yIdentN {
    /**
     * APIKey is the API-key provider.
     * @type {O11yO11yToggle}
     * @memberof O11yO11yIdentN
     */
    apikey?: O11yO11yToggle;
    /**
     * Impersonation is the impersonation provider.
     * @type {O11yO11yToggle}
     * @memberof O11yO11yIdentN
     */
    impersonation?: O11yO11yToggle;
    /**
     * Tokenizer is the token-based provider.
     * @type {O11yO11yToggle}
     * @memberof O11yO11yIdentN
     */
    tokenizer?: O11yO11yToggle;
}

/**
 * Check if a given object implements the O11yO11yIdentN interface.
 */
export function instanceOfO11yO11yIdentN(value: object): value is O11yO11yIdentN {
    return true;
}

export function O11yO11yIdentNFromJSON(json: any): O11yO11yIdentN {
    return O11yO11yIdentNFromJSONTyped(json, false);
}

export function O11yO11yIdentNFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yIdentN {
    if (json == null) {
        return json;
    }
    return {
        
        'apikey': json['apikey'] == null ? undefined : O11yO11yToggleFromJSON(json['apikey']),
        'impersonation': json['impersonation'] == null ? undefined : O11yO11yToggleFromJSON(json['impersonation']),
        'tokenizer': json['tokenizer'] == null ? undefined : O11yO11yToggleFromJSON(json['tokenizer']),
    };
}

export function O11yO11yIdentNToJSON(json: any): O11yO11yIdentN {
    return O11yO11yIdentNToJSONTyped(json, false);
}

export function O11yO11yIdentNToJSONTyped(value?: O11yO11yIdentN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apikey': O11yO11yToggleToJSON(value['apikey']),
        'impersonation': O11yO11yToggleToJSON(value['impersonation']),
        'tokenizer': O11yO11yToggleToJSON(value['tokenizer']),
    };
}

