/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInner } from './O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInner.js';
import {
    O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerFromJSON,
    O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerFromJSONTyped,
    O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerToJSON,
    O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerToJSONTyped,
} from './O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInner.js';

/**
 * 
 * @export
 * @interface O11yOldAWSLogsStrategy
 */
export interface O11yOldAWSLogsStrategy {
    /**
     * 
     * @type {Array<O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInner>}
     * @memberof O11yOldAWSLogsStrategy
     */
    cloudwatchLogsSubscriptions?: Array<O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInner>;
}

/**
 * Check if a given object implements the O11yOldAWSLogsStrategy interface.
 */
export function instanceOfO11yOldAWSLogsStrategy(value: object): value is O11yOldAWSLogsStrategy {
    return true;
}

export function O11yOldAWSLogsStrategyFromJSON(json: any): O11yOldAWSLogsStrategy {
    return O11yOldAWSLogsStrategyFromJSONTyped(json, false);
}

export function O11yOldAWSLogsStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yOldAWSLogsStrategy {
    if (json == null) {
        return json;
    }
    return {
        
        'cloudwatchLogsSubscriptions': json['cloudwatch_logs_subscriptions'] == null ? undefined : ((json['cloudwatch_logs_subscriptions'] as Array<any>).map(O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerFromJSON)),
    };
}

export function O11yOldAWSLogsStrategyToJSON(json: any): O11yOldAWSLogsStrategy {
    return O11yOldAWSLogsStrategyToJSONTyped(json, false);
}

export function O11yOldAWSLogsStrategyToJSONTyped(value?: O11yOldAWSLogsStrategy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloudwatch_logs_subscriptions': value['cloudwatchLogsSubscriptions'] == null ? undefined : ((value['cloudwatchLogsSubscriptions'] as Array<any>).map(O11yOldAWSLogsStrategyCloudwatchLogsSubscriptionsInnerToJSON)),
    };
}

