/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yErrorDetail } from './O11yO11yErrorDetail.js';
import {
    O11yO11yErrorDetailFromJSON,
    O11yO11yErrorDetailFromJSONTyped,
    O11yO11yErrorDetailToJSON,
    O11yO11yErrorDetailToJSONTyped,
} from './O11yO11yErrorDetail.js';
import type { O11yO11yAuthNSupport } from './O11yO11yAuthNSupport.js';
import {
    O11yO11yAuthNSupportFromJSON,
    O11yO11yAuthNSupportFromJSONTyped,
    O11yO11yAuthNSupportToJSON,
    O11yO11yAuthNSupportToJSONTyped,
} from './O11yO11yAuthNSupport.js';

/**
 * 
 * @export
 * @interface O11yO11ySessionOrg
 */
export interface O11yO11ySessionOrg {
    /**
     * AuthNSupport lists the org's open sign-in routes.
     * @type {O11yO11yAuthNSupport}
     * @memberof O11yO11ySessionOrg
     */
    authNSupport?: O11yO11yAuthNSupport;
    /**
     * ID is the org id.
     * @type {string}
     * @memberof O11yO11ySessionOrg
     */
    id?: string;
    /**
     * Name is the org's display name.
     * @type {string}
     * @memberof O11yO11ySessionOrg
     */
    name?: string;
    /**
     * Warning reports an org whose SSO is configured but not currently usable,
     * in the platform's error shape.
     * @type {O11yO11yErrorDetail}
     * @memberof O11yO11ySessionOrg
     */
    warning?: O11yO11yErrorDetail;
}

/**
 * Check if a given object implements the O11yO11ySessionOrg interface.
 */
export function instanceOfO11yO11ySessionOrg(value: object): value is O11yO11ySessionOrg {
    return true;
}

export function O11yO11ySessionOrgFromJSON(json: any): O11yO11ySessionOrg {
    return O11yO11ySessionOrgFromJSONTyped(json, false);
}

export function O11yO11ySessionOrgFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11ySessionOrg {
    if (json == null) {
        return json;
    }
    return {
        
        'authNSupport': json['authNSupport'] == null ? undefined : O11yO11yAuthNSupportFromJSON(json['authNSupport']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'warning': json['warning'] == null ? undefined : O11yO11yErrorDetailFromJSON(json['warning']),
    };
}

export function O11yO11ySessionOrgToJSON(json: any): O11yO11ySessionOrg {
    return O11yO11ySessionOrgToJSONTyped(json, false);
}

export function O11yO11ySessionOrgToJSONTyped(value?: O11yO11ySessionOrg | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authNSupport': O11yO11yAuthNSupportToJSON(value['authNSupport']),
        'id': value['id'],
        'name': value['name'],
        'warning': O11yO11yErrorDetailToJSON(value['warning']),
    };
}

