/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yDowntimeUpdateIn
 */
export interface O11yO11yDowntimeUpdateIn {
    /**
     * 
     * @type {Array<string>}
     * @memberof O11yO11yDowntimeUpdateIn
     */
    alertIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof O11yO11yDowntimeUpdateIn
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yO11yDowntimeUpdateIn
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof O11yO11yDowntimeUpdateIn
     */
    schedule?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yO11yDowntimeUpdateIn
     */
    scope?: string;
}

/**
 * Check if a given object implements the O11yO11yDowntimeUpdateIn interface.
 */
export function instanceOfO11yO11yDowntimeUpdateIn(value: object): value is O11yO11yDowntimeUpdateIn {
    return true;
}

export function O11yO11yDowntimeUpdateInFromJSON(json: any): O11yO11yDowntimeUpdateIn {
    return O11yO11yDowntimeUpdateInFromJSONTyped(json, false);
}

export function O11yO11yDowntimeUpdateInFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yDowntimeUpdateIn {
    if (json == null) {
        return json;
    }
    return {
        
        'alertIds': json['alertIds'] == null ? undefined : json['alertIds'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function O11yO11yDowntimeUpdateInToJSON(json: any): O11yO11yDowntimeUpdateIn {
    return O11yO11yDowntimeUpdateInToJSONTyped(json, false);
}

export function O11yO11yDowntimeUpdateInToJSONTyped(value?: O11yO11yDowntimeUpdateIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alertIds': value['alertIds'],
        'description': value['description'],
        'name': value['name'],
        'schedule': value['schedule'],
        'scope': value['scope'],
    };
}

