/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yIntegrationsListItem } from './O11yIntegrationsListItem.js';
import {
    O11yIntegrationsListItemFromJSON,
    O11yIntegrationsListItemFromJSONTyped,
    O11yIntegrationsListItemToJSON,
    O11yIntegrationsListItemToJSONTyped,
} from './O11yIntegrationsListItem.js';

/**
 * 
 * @export
 * @interface O11yO11yInstallOut
 */
export interface O11yO11yInstallOut {
    /**
     * Data holds the installed integration.
     * @type {O11yIntegrationsListItem}
     * @memberof O11yO11yInstallOut
     */
    data?: O11yIntegrationsListItem;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yInstallOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yInstallOut interface.
 */
export function instanceOfO11yO11yInstallOut(value: object): value is O11yO11yInstallOut {
    return true;
}

export function O11yO11yInstallOutFromJSON(json: any): O11yO11yInstallOut {
    return O11yO11yInstallOutFromJSONTyped(json, false);
}

export function O11yO11yInstallOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yInstallOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : O11yIntegrationsListItemFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yInstallOutToJSON(json: any): O11yO11yInstallOut {
    return O11yO11yInstallOutToJSONTyped(json, false);
}

export function O11yO11yInstallOutToJSONTyped(value?: O11yO11yInstallOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': O11yIntegrationsListItemToJSON(value['data']),
        'status': value['status'],
    };
}

