/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yAuthDomainConfig } from './O11yO11yAuthDomainConfig.js';
import {
    O11yO11yAuthDomainConfigFromJSON,
    O11yO11yAuthDomainConfigFromJSONTyped,
    O11yO11yAuthDomainConfigToJSON,
    O11yO11yAuthDomainConfigToJSONTyped,
} from './O11yO11yAuthDomainConfig.js';

/**
 * 
 * @export
 * @interface O11yO11yUpdatableAuthDomain
 */
export interface O11yO11yUpdatableAuthDomain {
    /**
     * Config is the SSO configuration to store.
     * @type {O11yO11yAuthDomainConfig}
     * @memberof O11yO11yUpdatableAuthDomain
     */
    config?: O11yO11yAuthDomainConfig;
}

/**
 * Check if a given object implements the O11yO11yUpdatableAuthDomain interface.
 */
export function instanceOfO11yO11yUpdatableAuthDomain(value: object): value is O11yO11yUpdatableAuthDomain {
    return true;
}

export function O11yO11yUpdatableAuthDomainFromJSON(json: any): O11yO11yUpdatableAuthDomain {
    return O11yO11yUpdatableAuthDomainFromJSONTyped(json, false);
}

export function O11yO11yUpdatableAuthDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yUpdatableAuthDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : O11yO11yAuthDomainConfigFromJSON(json['config']),
    };
}

export function O11yO11yUpdatableAuthDomainToJSON(json: any): O11yO11yUpdatableAuthDomain {
    return O11yO11yUpdatableAuthDomainToJSONTyped(json, false);
}

export function O11yO11yUpdatableAuthDomainToJSONTyped(value?: O11yO11yUpdatableAuthDomain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': O11yO11yAuthDomainConfigToJSON(value['config']),
    };
}

