/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yQueryRangeOut
 */
export interface O11yO11yQueryRangeOut {
    /**
     * 
     * @type {any}
     * @memberof O11yO11yQueryRangeOut
     */
    data?: any | null;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yQueryRangeOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yQueryRangeOut interface.
 */
export function instanceOfO11yO11yQueryRangeOut(value: object): value is O11yO11yQueryRangeOut {
    return true;
}

export function O11yO11yQueryRangeOutFromJSON(json: any): O11yO11yQueryRangeOut {
    return O11yO11yQueryRangeOutFromJSONTyped(json, false);
}

export function O11yO11yQueryRangeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yQueryRangeOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yQueryRangeOutToJSON(json: any): O11yO11yQueryRangeOut {
    return O11yO11yQueryRangeOutToJSONTyped(json, false);
}

export function O11yO11yQueryRangeOutToJSONTyped(value?: O11yO11yQueryRangeOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'status': value['status'],
    };
}

