/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yDashboardTag
 */
export interface O11yO11yDashboardTag {
    /**
     * Key is the tag key.
     * @type {string}
     * @memberof O11yO11yDashboardTag
     */
    key?: string;
    /**
     * Value is the tag value.
     * @type {string}
     * @memberof O11yO11yDashboardTag
     */
    value?: string;
}

/**
 * Check if a given object implements the O11yO11yDashboardTag interface.
 */
export function instanceOfO11yO11yDashboardTag(value: object): value is O11yO11yDashboardTag {
    return true;
}

export function O11yO11yDashboardTagFromJSON(json: any): O11yO11yDashboardTag {
    return O11yO11yDashboardTagFromJSONTyped(json, false);
}

export function O11yO11yDashboardTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yDashboardTag {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function O11yO11yDashboardTagToJSON(json: any): O11yO11yDashboardTag {
    return O11yO11yDashboardTagToJSONTyped(json, false);
}

export function O11yO11yDashboardTagToJSONTyped(value?: O11yO11yDashboardTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

