/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yTagFilter
 */
export interface O11yO11yTagFilter {
    /**
     * BoolValues are the values matched when the tag holds booleans.
     * @type {Array<boolean>}
     * @memberof O11yO11yTagFilter
     */
    boolValues?: Array<boolean>;
    /**
     * Key is the tag to test.
     * @type {string}
     * @memberof O11yO11yTagFilter
     */
    key?: string;
    /**
     * NumberValues are the values matched when the tag holds numbers.
     * @type {Array<number>}
     * @memberof O11yO11yTagFilter
     */
    numberValues?: Array<number>;
    /**
     * Operator is the comparison to apply — in, not_in, equals, contains and
     * the other operators the trace filter grammar names.
     * @type {string}
     * @memberof O11yO11yTagFilter
     */
    operator?: string;
    /**
     * StringValues are the values matched when the tag holds strings.
     * @type {Array<string>}
     * @memberof O11yO11yTagFilter
     */
    stringValues?: Array<string>;
    /**
     * TagType says which kind of value the tag holds: string, number or bool.
     * @type {string}
     * @memberof O11yO11yTagFilter
     */
    tagType?: string;
}

/**
 * Check if a given object implements the O11yO11yTagFilter interface.
 */
export function instanceOfO11yO11yTagFilter(value: object): value is O11yO11yTagFilter {
    return true;
}

export function O11yO11yTagFilterFromJSON(json: any): O11yO11yTagFilter {
    return O11yO11yTagFilterFromJSONTyped(json, false);
}

export function O11yO11yTagFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yTagFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'boolValues': json['boolValues'] == null ? undefined : json['boolValues'],
        'key': json['key'] == null ? undefined : json['key'],
        'numberValues': json['numberValues'] == null ? undefined : json['numberValues'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'stringValues': json['stringValues'] == null ? undefined : json['stringValues'],
        'tagType': json['tagType'] == null ? undefined : json['tagType'],
    };
}

export function O11yO11yTagFilterToJSON(json: any): O11yO11yTagFilter {
    return O11yO11yTagFilterToJSONTyped(json, false);
}

export function O11yO11yTagFilterToJSONTyped(value?: O11yO11yTagFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boolValues': value['boolValues'],
        'key': value['key'],
        'numberValues': value['numberValues'],
        'operator': value['operator'],
        'stringValues': value['stringValues'],
        'tagType': value['tagType'],
    };
}

