/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yOrderByKey
 */
export interface O11yOrderByKey {
    /**
     * 
     * @type {string}
     * @memberof O11yOrderByKey
     */
    description?: string;
    /**
     * 
     * @type {any}
     * @memberof O11yOrderByKey
     */
    fieldContext?: any | null;
    /**
     * 
     * @type {any}
     * @memberof O11yOrderByKey
     */
    fieldDataType?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yOrderByKey
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof O11yOrderByKey
     */
    signal?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yOrderByKey
     */
    unit?: string;
}

/**
 * Check if a given object implements the O11yOrderByKey interface.
 */
export function instanceOfO11yOrderByKey(value: object): value is O11yOrderByKey {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function O11yOrderByKeyFromJSON(json: any): O11yOrderByKey {
    return O11yOrderByKeyFromJSONTyped(json, false);
}

export function O11yOrderByKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yOrderByKey {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'fieldContext': json['fieldContext'] == null ? undefined : json['fieldContext'],
        'fieldDataType': json['fieldDataType'] == null ? undefined : json['fieldDataType'],
        'name': json['name'],
        'signal': json['signal'] == null ? undefined : json['signal'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function O11yOrderByKeyToJSON(json: any): O11yOrderByKey {
    return O11yOrderByKeyToJSONTyped(json, false);
}

export function O11yOrderByKeyToJSONTyped(value?: O11yOrderByKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'fieldContext': value['fieldContext'],
        'fieldDataType': value['fieldDataType'],
        'name': value['name'],
        'signal': value['signal'],
        'unit': value['unit'],
    };
}

