/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yAuthDomainConfig } from './O11yO11yAuthDomainConfig.js';
import {
    O11yO11yAuthDomainConfigFromJSON,
    O11yO11yAuthDomainConfigFromJSONTyped,
    O11yO11yAuthDomainConfigToJSON,
    O11yO11yAuthDomainConfigToJSONTyped,
} from './O11yO11yAuthDomainConfig.js';

/**
 * 
 * @export
 * @interface O11yO11yPostableAuthDomain
 */
export interface O11yO11yPostableAuthDomain {
    /**
     * Config is the domain's SSO configuration.
     * @type {O11yO11yAuthDomainConfig}
     * @memberof O11yO11yPostableAuthDomain
     */
    config?: O11yO11yAuthDomainConfig;
    /**
     * Name is the email domain being claimed, e.g. example.com.
     * @type {string}
     * @memberof O11yO11yPostableAuthDomain
     */
    name?: string;
}

/**
 * Check if a given object implements the O11yO11yPostableAuthDomain interface.
 */
export function instanceOfO11yO11yPostableAuthDomain(value: object): value is O11yO11yPostableAuthDomain {
    return true;
}

export function O11yO11yPostableAuthDomainFromJSON(json: any): O11yO11yPostableAuthDomain {
    return O11yO11yPostableAuthDomainFromJSONTyped(json, false);
}

export function O11yO11yPostableAuthDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yPostableAuthDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : O11yO11yAuthDomainConfigFromJSON(json['config']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function O11yO11yPostableAuthDomainToJSON(json: any): O11yO11yPostableAuthDomain {
    return O11yO11yPostableAuthDomainToJSONTyped(json, false);
}

export function O11yO11yPostableAuthDomainToJSONTyped(value?: O11yO11yPostableAuthDomain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': O11yO11yAuthDomainConfigToJSON(value['config']),
        'name': value['name'],
    };
}

