/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yUpdateIngestionKeyIn
 */
export interface O11yO11yUpdateIngestionKeyIn {
    /**
     * 
     * @type {Date}
     * @memberof O11yO11yUpdateIngestionKeyIn
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof O11yO11yUpdateIngestionKeyIn
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof O11yO11yUpdateIngestionKeyIn
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the O11yO11yUpdateIngestionKeyIn interface.
 */
export function instanceOfO11yO11yUpdateIngestionKeyIn(value: object): value is O11yO11yUpdateIngestionKeyIn {
    return true;
}

export function O11yO11yUpdateIngestionKeyInFromJSON(json: any): O11yO11yUpdateIngestionKeyIn {
    return O11yO11yUpdateIngestionKeyInFromJSONTyped(json, false);
}

export function O11yO11yUpdateIngestionKeyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yUpdateIngestionKeyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function O11yO11yUpdateIngestionKeyInToJSON(json: any): O11yO11yUpdateIngestionKeyIn {
    return O11yO11yUpdateIngestionKeyInToJSONTyped(json, false);
}

export function O11yO11yUpdateIngestionKeyInToJSONTyped(value?: O11yO11yUpdateIngestionKeyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'name': value['name'],
        'tags': value['tags'],
    };
}

