/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yBasicAuth
 */
export interface O11yBasicAuth {
    /**
     * 
     * @type {any}
     * @memberof O11yBasicAuth
     */
    password?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yBasicAuth
     */
    passwordFile?: string;
    /**
     * PasswordRef is the name of the secret within the secret manager to use as the password.
     * @type {string}
     * @memberof O11yBasicAuth
     */
    passwordRef?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yBasicAuth
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yBasicAuth
     */
    usernameFile?: string;
    /**
     * UsernameRef is the name of the secret within the secret manager to use as the username.
     * @type {string}
     * @memberof O11yBasicAuth
     */
    usernameRef?: string;
}

/**
 * Check if a given object implements the O11yBasicAuth interface.
 */
export function instanceOfO11yBasicAuth(value: object): value is O11yBasicAuth {
    return true;
}

export function O11yBasicAuthFromJSON(json: any): O11yBasicAuth {
    return O11yBasicAuthFromJSONTyped(json, false);
}

export function O11yBasicAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yBasicAuth {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'passwordFile': json['password_file'] == null ? undefined : json['password_file'],
        'passwordRef': json['password_ref'] == null ? undefined : json['password_ref'],
        'username': json['username'] == null ? undefined : json['username'],
        'usernameFile': json['username_file'] == null ? undefined : json['username_file'],
        'usernameRef': json['username_ref'] == null ? undefined : json['username_ref'],
    };
}

export function O11yBasicAuthToJSON(json: any): O11yBasicAuth {
    return O11yBasicAuthToJSONTyped(json, false);
}

export function O11yBasicAuthToJSONTyped(value?: O11yBasicAuth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'password_file': value['passwordFile'],
        'password_ref': value['passwordRef'],
        'username': value['username'],
        'username_file': value['usernameFile'],
        'username_ref': value['usernameRef'],
    };
}

