/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yAggregationMeta
 */
export interface O11yO11yAggregationMeta {
    /**
     * Unit is the aggregation's unit.
     * @type {string}
     * @memberof O11yO11yAggregationMeta
     */
    unit?: string;
}

/**
 * Check if a given object implements the O11yO11yAggregationMeta interface.
 */
export function instanceOfO11yO11yAggregationMeta(value: object): value is O11yO11yAggregationMeta {
    return true;
}

export function O11yO11yAggregationMetaFromJSON(json: any): O11yO11yAggregationMeta {
    return O11yO11yAggregationMetaFromJSONTyped(json, false);
}

export function O11yO11yAggregationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yAggregationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function O11yO11yAggregationMetaToJSON(json: any): O11yO11yAggregationMeta {
    return O11yO11yAggregationMetaToJSONTyped(json, false);
}

export function O11yO11yAggregationMetaToJSONTyped(value?: O11yO11yAggregationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unit': value['unit'],
    };
}

