/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yCollectedMetric
 */
export interface O11yCollectedMetric {
    /**
     * 
     * @type {string}
     * @memberof O11yCollectedMetric
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yCollectedMetric
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yCollectedMetric
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yCollectedMetric
     */
    unit?: string;
}

/**
 * Check if a given object implements the O11yCollectedMetric interface.
 */
export function instanceOfO11yCollectedMetric(value: object): value is O11yCollectedMetric {
    return true;
}

export function O11yCollectedMetricFromJSON(json: any): O11yCollectedMetric {
    return O11yCollectedMetricFromJSONTyped(json, false);
}

export function O11yCollectedMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yCollectedMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function O11yCollectedMetricToJSON(json: any): O11yCollectedMetric {
    return O11yCollectedMetricToJSONTyped(json, false);
}

export function O11yCollectedMetricToJSONTyped(value?: O11yCollectedMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'type': value['type'],
        'unit': value['unit'],
    };
}

