/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yUserRole } from './O11yO11yUserRole.js';
import {
    O11yO11yUserRoleFromJSON,
    O11yO11yUserRoleFromJSONTyped,
    O11yO11yUserRoleToJSON,
    O11yO11yUserRoleToJSONTyped,
} from './O11yO11yUserRole.js';

/**
 * 
 * @export
 * @interface O11yO11yUserWithRoles
 */
export interface O11yO11yUserWithRoles {
    /**
     * CreatedAt is when they joined.
     * @type {Date}
     * @memberof O11yO11yUserWithRoles
     */
    createdAt?: Date;
    /**
     * DisplayName is what the console shows for them.
     * @type {string}
     * @memberof O11yO11yUserWithRoles
     */
    displayName?: string;
    /**
     * Email is their address.
     * @type {string}
     * @memberof O11yO11yUserWithRoles
     */
    email?: string;
    /**
     * ID is the user id.
     * @type {string}
     * @memberof O11yO11yUserWithRoles
     */
    id?: string;
    /**
     * IsRoot marks the org's root user.
     * @type {boolean}
     * @memberof O11yO11yUserWithRoles
     */
    isRoot?: boolean;
    /**
     * OrgID is the org they belong to.
     * @type {string}
     * @memberof O11yO11yUserWithRoles
     */
    orgId?: string;
    /**
     * Status is their lifecycle state — active, pending_invite or deleted.
     * @type {string}
     * @memberof O11yO11yUserWithRoles
     */
    status?: string;
    /**
     * UpdatedAt is when their record last changed.
     * @type {Date}
     * @memberof O11yO11yUserWithRoles
     */
    updatedAt?: Date;
    /**
     * UserRoles are their role assignments.
     * @type {Array<O11yO11yUserRole>}
     * @memberof O11yO11yUserWithRoles
     */
    userRoles?: Array<O11yO11yUserRole>;
}

/**
 * Check if a given object implements the O11yO11yUserWithRoles interface.
 */
export function instanceOfO11yO11yUserWithRoles(value: object): value is O11yO11yUserWithRoles {
    return true;
}

export function O11yO11yUserWithRolesFromJSON(json: any): O11yO11yUserWithRoles {
    return O11yO11yUserWithRolesFromJSONTyped(json, false);
}

export function O11yO11yUserWithRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yUserWithRoles {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'isRoot': json['isRoot'] == null ? undefined : json['isRoot'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userRoles': json['userRoles'] == null ? undefined : ((json['userRoles'] as Array<any>).map(O11yO11yUserRoleFromJSON)),
    };
}

export function O11yO11yUserWithRolesToJSON(json: any): O11yO11yUserWithRoles {
    return O11yO11yUserWithRolesToJSONTyped(json, false);
}

export function O11yO11yUserWithRolesToJSONTyped(value?: O11yO11yUserWithRoles | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'displayName': value['displayName'],
        'email': value['email'],
        'id': value['id'],
        'isRoot': value['isRoot'],
        'orgId': value['orgId'],
        'status': value['status'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userRoles': value['userRoles'] == null ? undefined : ((value['userRoles'] as Array<any>).map(O11yO11yUserRoleToJSON)),
    };
}

