/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yLogRecord } from './O11yO11yLogRecord.js';
import {
    O11yO11yLogRecordFromJSON,
    O11yO11yLogRecordFromJSONTyped,
    O11yO11yLogRecordToJSON,
    O11yO11yLogRecordToJSONTyped,
} from './O11yO11yLogRecord.js';
import type { O11yO11yLogPipeline } from './O11yO11yLogPipeline.js';
import {
    O11yO11yLogPipelineFromJSON,
    O11yO11yLogPipelineFromJSONTyped,
    O11yO11yLogPipelineToJSON,
    O11yO11yLogPipelineToJSONTyped,
} from './O11yO11yLogPipeline.js';

/**
 * 
 * @export
 * @interface O11yO11yLogPipelinePreviewIn
 */
export interface O11yO11yLogPipelinePreviewIn {
    /**
     * Logs are the sample records to transform.
     * @type {Array<O11yO11yLogRecord>}
     * @memberof O11yO11yLogPipelinePreviewIn
     */
    logs?: Array<O11yO11yLogRecord>;
    /**
     * Pipelines are the pipelines to simulate, in order.
     * @type {Array<O11yO11yLogPipeline>}
     * @memberof O11yO11yLogPipelinePreviewIn
     */
    pipelines?: Array<O11yO11yLogPipeline>;
}

/**
 * Check if a given object implements the O11yO11yLogPipelinePreviewIn interface.
 */
export function instanceOfO11yO11yLogPipelinePreviewIn(value: object): value is O11yO11yLogPipelinePreviewIn {
    return true;
}

export function O11yO11yLogPipelinePreviewInFromJSON(json: any): O11yO11yLogPipelinePreviewIn {
    return O11yO11yLogPipelinePreviewInFromJSONTyped(json, false);
}

export function O11yO11yLogPipelinePreviewInFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yLogPipelinePreviewIn {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'] == null ? undefined : ((json['logs'] as Array<any>).map(O11yO11yLogRecordFromJSON)),
        'pipelines': json['pipelines'] == null ? undefined : ((json['pipelines'] as Array<any>).map(O11yO11yLogPipelineFromJSON)),
    };
}

export function O11yO11yLogPipelinePreviewInToJSON(json: any): O11yO11yLogPipelinePreviewIn {
    return O11yO11yLogPipelinePreviewInToJSONTyped(json, false);
}

export function O11yO11yLogPipelinePreviewInToJSONTyped(value?: O11yO11yLogPipelinePreviewIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'] == null ? undefined : ((value['logs'] as Array<any>).map(O11yO11yLogRecordToJSON)),
        'pipelines': value['pipelines'] == null ? undefined : ((value['pipelines'] as Array<any>).map(O11yO11yLogPipelineToJSON)),
    };
}

