/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yPodCountsByPhase } from './O11yPodCountsByPhase.js';
import {
    O11yPodCountsByPhaseFromJSON,
    O11yPodCountsByPhaseFromJSONTyped,
    O11yPodCountsByPhaseToJSON,
    O11yPodCountsByPhaseToJSONTyped,
} from './O11yPodCountsByPhase.js';

/**
 * 
 * @export
 * @interface O11yPodRecord
 */
export interface O11yPodRecord {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof O11yPodRecord
     */
    meta?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podAge?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podCPU?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podCPULimit?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podCPURequest?: number;
    /**
     * 
     * @type {O11yPodCountsByPhase}
     * @memberof O11yPodRecord
     */
    podCountsByPhase?: O11yPodCountsByPhase;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podMemory?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podMemoryLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof O11yPodRecord
     */
    podMemoryRequest?: number;
    /**
     * 
     * @type {any}
     * @memberof O11yPodRecord
     */
    podPhase?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yPodRecord
     */
    podUID?: string;
}

/**
 * Check if a given object implements the O11yPodRecord interface.
 */
export function instanceOfO11yPodRecord(value: object): value is O11yPodRecord {
    return true;
}

export function O11yPodRecordFromJSON(json: any): O11yPodRecord {
    return O11yPodRecordFromJSONTyped(json, false);
}

export function O11yPodRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yPodRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : json['meta'],
        'podAge': json['podAge'] == null ? undefined : json['podAge'],
        'podCPU': json['podCPU'] == null ? undefined : json['podCPU'],
        'podCPULimit': json['podCPULimit'] == null ? undefined : json['podCPULimit'],
        'podCPURequest': json['podCPURequest'] == null ? undefined : json['podCPURequest'],
        'podCountsByPhase': json['podCountsByPhase'] == null ? undefined : O11yPodCountsByPhaseFromJSON(json['podCountsByPhase']),
        'podMemory': json['podMemory'] == null ? undefined : json['podMemory'],
        'podMemoryLimit': json['podMemoryLimit'] == null ? undefined : json['podMemoryLimit'],
        'podMemoryRequest': json['podMemoryRequest'] == null ? undefined : json['podMemoryRequest'],
        'podPhase': json['podPhase'] == null ? undefined : json['podPhase'],
        'podUID': json['podUID'] == null ? undefined : json['podUID'],
    };
}

export function O11yPodRecordToJSON(json: any): O11yPodRecord {
    return O11yPodRecordToJSONTyped(json, false);
}

export function O11yPodRecordToJSONTyped(value?: O11yPodRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': value['meta'],
        'podAge': value['podAge'],
        'podCPU': value['podCPU'],
        'podCPULimit': value['podCPULimit'],
        'podCPURequest': value['podCPURequest'],
        'podCountsByPhase': O11yPodCountsByPhaseToJSON(value['podCountsByPhase']),
        'podMemory': value['podMemory'],
        'podMemoryLimit': value['podMemoryLimit'],
        'podMemoryRequest': value['podMemoryRequest'],
        'podPhase': value['podPhase'],
        'podUID': value['podUID'],
    };
}

