/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yGettableFunnel } from './O11yGettableFunnel.js';
import {
    O11yGettableFunnelFromJSON,
    O11yGettableFunnelFromJSONTyped,
    O11yGettableFunnelToJSON,
    O11yGettableFunnelToJSONTyped,
} from './O11yGettableFunnel.js';

/**
 * 
 * @export
 * @interface O11yO11yFunnelsOut
 */
export interface O11yO11yFunnelsOut {
    /**
     * Data are the funnels.
     * @type {Array<O11yGettableFunnel>}
     * @memberof O11yO11yFunnelsOut
     */
    data?: Array<O11yGettableFunnel>;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yFunnelsOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yFunnelsOut interface.
 */
export function instanceOfO11yO11yFunnelsOut(value: object): value is O11yO11yFunnelsOut {
    return true;
}

export function O11yO11yFunnelsOutFromJSON(json: any): O11yO11yFunnelsOut {
    return O11yO11yFunnelsOutFromJSONTyped(json, false);
}

export function O11yO11yFunnelsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yFunnelsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(O11yGettableFunnelFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yFunnelsOutToJSON(json: any): O11yO11yFunnelsOut {
    return O11yO11yFunnelsOutToJSONTyped(json, false);
}

export function O11yO11yFunnelsOutToJSONTyped(value?: O11yO11yFunnelsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(O11yGettableFunnelToJSON)),
        'status': value['status'],
    };
}

