/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yJobListRecord } from './O11yJobListRecord.js';
import {
    O11yJobListRecordFromJSON,
    O11yJobListRecordFromJSONTyped,
    O11yJobListRecordToJSON,
    O11yJobListRecordToJSONTyped,
} from './O11yJobListRecord.js';

/**
 * 
 * @export
 * @interface O11yJobListResponse
 */
export interface O11yJobListResponse {
    /**
     * 
     * @type {Array<O11yJobListRecord>}
     * @memberof O11yJobListResponse
     */
    records?: Array<O11yJobListRecord>;
    /**
     * 
     * @type {number}
     * @memberof O11yJobListResponse
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof O11yJobListResponse
     */
    type?: string;
}

/**
 * Check if a given object implements the O11yJobListResponse interface.
 */
export function instanceOfO11yJobListResponse(value: object): value is O11yJobListResponse {
    return true;
}

export function O11yJobListResponseFromJSON(json: any): O11yJobListResponse {
    return O11yJobListResponseFromJSONTyped(json, false);
}

export function O11yJobListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yJobListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(O11yJobListRecordFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function O11yJobListResponseToJSON(json: any): O11yJobListResponse {
    return O11yJobListResponseToJSONTyped(json, false);
}

export function O11yJobListResponseToJSONTyped(value?: O11yJobListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(O11yJobListRecordToJSON)),
        'total': value['total'],
        'type': value['type'],
    };
}

