/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yTrace } from './O11yO11yTrace.js';
import {
    O11yO11yTraceFromJSON,
    O11yO11yTraceFromJSONTyped,
    O11yO11yTraceToJSON,
    O11yO11yTraceToJSONTyped,
} from './O11yO11yTrace.js';

/**
 * 
 * @export
 * @interface O11yO11yTraces
 */
export interface O11yO11yTraces {
    /**
     * Items are the traces, most recent first.
     * @type {Array<O11yO11yTrace>}
     * @memberof O11yO11yTraces
     */
    items?: Array<O11yO11yTrace>;
}

/**
 * Check if a given object implements the O11yO11yTraces interface.
 */
export function instanceOfO11yO11yTraces(value: object): value is O11yO11yTraces {
    return true;
}

export function O11yO11yTracesFromJSON(json: any): O11yO11yTraces {
    return O11yO11yTracesFromJSONTyped(json, false);
}

export function O11yO11yTracesFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yTraces {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(O11yO11yTraceFromJSON)),
    };
}

export function O11yO11yTracesToJSON(json: any): O11yO11yTraces {
    return O11yO11yTracesToJSONTyped(json, false);
}

export function O11yO11yTracesToJSONTyped(value?: O11yO11yTraces | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(O11yO11yTraceToJSON)),
    };
}

