/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yTLSConfig } from './O11yTLSConfig.js';
import {
    O11yTLSConfigFromJSON,
    O11yTLSConfigFromJSONTyped,
    O11yTLSConfigToJSON,
    O11yTLSConfigToJSONTyped,
} from './O11yTLSConfig.js';
import type { O11yBasicAuth } from './O11yBasicAuth.js';
import {
    O11yBasicAuthFromJSON,
    O11yBasicAuthFromJSONTyped,
    O11yBasicAuthToJSON,
    O11yBasicAuthToJSONTyped,
} from './O11yBasicAuth.js';
import type { O11yAuthorization } from './O11yAuthorization.js';
import {
    O11yAuthorizationFromJSON,
    O11yAuthorizationFromJSONTyped,
    O11yAuthorizationToJSON,
    O11yAuthorizationToJSONTyped,
} from './O11yAuthorization.js';
import type { O11yOAuth2 } from './O11yOAuth2.js';
import {
    O11yOAuth2FromJSON,
    O11yOAuth2FromJSONTyped,
    O11yOAuth2ToJSON,
    O11yOAuth2ToJSONTyped,
} from './O11yOAuth2.js';

/**
 * 
 * @export
 * @interface O11yHTTPClientConfig
 */
export interface O11yHTTPClientConfig {
    /**
     * The HTTP authorization credentials for the targets.
     * @type {O11yAuthorization}
     * @memberof O11yHTTPClientConfig
     */
    authorization?: O11yAuthorization;
    /**
     * The HTTP basic authentication credentials for the targets.
     * @type {O11yBasicAuth}
     * @memberof O11yHTTPClientConfig
     */
    basicAuth?: O11yBasicAuth;
    /**
     * 
     * @type {any}
     * @memberof O11yHTTPClientConfig
     */
    bearerToken?: any | null;
    /**
     * The bearer token file for the targets. Deprecated in favour of
     * Authorization.CredentialsFile.
     * @type {string}
     * @memberof O11yHTTPClientConfig
     */
    bearerTokenFile?: string;
    /**
     * EnableHTTP2 specifies whether the client should configure HTTP2.
     * The omitempty flag is not set, because it would be hidden from the
     * marshalled configuration when set to false.
     * @type {boolean}
     * @memberof O11yHTTPClientConfig
     */
    enableHttp2?: boolean;
    /**
     * FollowRedirects specifies whether the client should follow HTTP 3xx redirects.
     * The omitempty flag is not set, because it would be hidden from the
     * marshalled configuration when set to false.
     * @type {boolean}
     * @memberof O11yHTTPClientConfig
     */
    followRedirects?: boolean;
    /**
     * 
     * @type {any}
     * @memberof O11yHTTPClientConfig
     */
    httpHeaders?: any | null;
    /**
     * 
     * @type {string}
     * @memberof O11yHTTPClientConfig
     */
    noProxy?: string;
    /**
     * The OAuth2 client credentials used to fetch a token for the targets.
     * @type {O11yOAuth2}
     * @memberof O11yHTTPClientConfig
     */
    oauth2?: O11yOAuth2;
    /**
     * 
     * @type {{ [key: string]: Array<any>; }}
     * @memberof O11yHTTPClientConfig
     */
    proxyConnectHeader?: { [key: string]: Array<any>; };
    /**
     * 
     * @type {boolean}
     * @memberof O11yHTTPClientConfig
     */
    proxyFromEnvironment?: boolean;
    /**
     * 
     * @type {any}
     * @memberof O11yHTTPClientConfig
     */
    proxyUrl?: any | null;
    /**
     * TLSConfig to use to connect to the targets.
     * @type {O11yTLSConfig}
     * @memberof O11yHTTPClientConfig
     */
    tlsConfig?: O11yTLSConfig;
}

/**
 * Check if a given object implements the O11yHTTPClientConfig interface.
 */
export function instanceOfO11yHTTPClientConfig(value: object): value is O11yHTTPClientConfig {
    return true;
}

export function O11yHTTPClientConfigFromJSON(json: any): O11yHTTPClientConfig {
    return O11yHTTPClientConfigFromJSONTyped(json, false);
}

export function O11yHTTPClientConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yHTTPClientConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'authorization': json['authorization'] == null ? undefined : O11yAuthorizationFromJSON(json['authorization']),
        'basicAuth': json['basic_auth'] == null ? undefined : O11yBasicAuthFromJSON(json['basic_auth']),
        'bearerToken': json['bearer_token'] == null ? undefined : json['bearer_token'],
        'bearerTokenFile': json['bearer_token_file'] == null ? undefined : json['bearer_token_file'],
        'enableHttp2': json['enable_http2'] == null ? undefined : json['enable_http2'],
        'followRedirects': json['follow_redirects'] == null ? undefined : json['follow_redirects'],
        'httpHeaders': json['http_headers'] == null ? undefined : json['http_headers'],
        'noProxy': json['no_proxy'] == null ? undefined : json['no_proxy'],
        'oauth2': json['oauth2'] == null ? undefined : O11yOAuth2FromJSON(json['oauth2']),
        'proxyConnectHeader': json['proxy_connect_header'] == null ? undefined : json['proxy_connect_header'],
        'proxyFromEnvironment': json['proxy_from_environment'] == null ? undefined : json['proxy_from_environment'],
        'proxyUrl': json['proxy_url'] == null ? undefined : json['proxy_url'],
        'tlsConfig': json['tls_config'] == null ? undefined : O11yTLSConfigFromJSON(json['tls_config']),
    };
}

export function O11yHTTPClientConfigToJSON(json: any): O11yHTTPClientConfig {
    return O11yHTTPClientConfigToJSONTyped(json, false);
}

export function O11yHTTPClientConfigToJSONTyped(value?: O11yHTTPClientConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization': O11yAuthorizationToJSON(value['authorization']),
        'basic_auth': O11yBasicAuthToJSON(value['basicAuth']),
        'bearer_token': value['bearerToken'],
        'bearer_token_file': value['bearerTokenFile'],
        'enable_http2': value['enableHttp2'],
        'follow_redirects': value['followRedirects'],
        'http_headers': value['httpHeaders'],
        'no_proxy': value['noProxy'],
        'oauth2': O11yOAuth2ToJSON(value['oauth2']),
        'proxy_connect_header': value['proxyConnectHeader'],
        'proxy_from_environment': value['proxyFromEnvironment'],
        'proxy_url': value['proxyUrl'],
        'tls_config': O11yTLSConfigToJSON(value['tlsConfig']),
    };
}

