/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yLLMTrace } from './O11yO11yLLMTrace.js';
import {
    O11yO11yLLMTraceFromJSON,
    O11yO11yLLMTraceFromJSONTyped,
    O11yO11yLLMTraceToJSON,
    O11yO11yLLMTraceToJSONTyped,
} from './O11yO11yLLMTrace.js';

/**
 * 
 * @export
 * @interface O11yO11yLLMTracesPage
 */
export interface O11yO11yLLMTracesPage {
    /**
     * Items are the traces, newest first.
     * @type {Array<O11yO11yLLMTrace>}
     * @memberof O11yO11yLLMTracesPage
     */
    items?: Array<O11yO11yLLMTrace>;
    /**
     * Limit is the page cap the read ran with.
     * @type {number}
     * @memberof O11yO11yLLMTracesPage
     */
    limit?: number;
    /**
     * Offset is the row offset this page started at.
     * @type {number}
     * @memberof O11yO11yLLMTracesPage
     */
    offset?: number;
}

/**
 * Check if a given object implements the O11yO11yLLMTracesPage interface.
 */
export function instanceOfO11yO11yLLMTracesPage(value: object): value is O11yO11yLLMTracesPage {
    return true;
}

export function O11yO11yLLMTracesPageFromJSON(json: any): O11yO11yLLMTracesPage {
    return O11yO11yLLMTracesPageFromJSONTyped(json, false);
}

export function O11yO11yLLMTracesPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yLLMTracesPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(O11yO11yLLMTraceFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function O11yO11yLLMTracesPageToJSON(json: any): O11yO11yLLMTracesPage {
    return O11yO11yLLMTracesPageToJSONTyped(json, false);
}

export function O11yO11yLLMTracesPageToJSONTyped(value?: O11yO11yLLMTracesPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(O11yO11yLLMTraceToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

