/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yGettableFunnel } from './O11yGettableFunnel.js';
import {
    O11yGettableFunnelFromJSON,
    O11yGettableFunnelFromJSONTyped,
    O11yGettableFunnelToJSON,
    O11yGettableFunnelToJSONTyped,
} from './O11yGettableFunnel.js';

/**
 * 
 * @export
 * @interface O11yO11yFunnelOut
 */
export interface O11yO11yFunnelOut {
    /**
     * Data is the funnel with its steps.
     * @type {O11yGettableFunnel}
     * @memberof O11yO11yFunnelOut
     */
    data?: O11yGettableFunnel;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yFunnelOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yFunnelOut interface.
 */
export function instanceOfO11yO11yFunnelOut(value: object): value is O11yO11yFunnelOut {
    return true;
}

export function O11yO11yFunnelOutFromJSON(json: any): O11yO11yFunnelOut {
    return O11yO11yFunnelOutFromJSONTyped(json, false);
}

export function O11yO11yFunnelOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yFunnelOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : O11yGettableFunnelFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yFunnelOutToJSON(json: any): O11yO11yFunnelOut {
    return O11yO11yFunnelOutToJSONTyped(json, false);
}

export function O11yO11yFunnelOutToJSONTyped(value?: O11yO11yFunnelOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': O11yGettableFunnelToJSON(value['data']),
        'status': value['status'],
    };
}

