/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yO11yObject } from './O11yO11yObject.js';
import {
    O11yO11yObjectFromJSON,
    O11yO11yObjectFromJSONTyped,
    O11yO11yObjectToJSON,
    O11yO11yObjectToJSONTyped,
} from './O11yO11yObject.js';

/**
 * 
 * @export
 * @interface O11yO11yTransactionResult
 */
export interface O11yO11yTransactionResult {
    /**
     * Authorized says whether the caller may do it.
     * @type {boolean}
     * @memberof O11yO11yTransactionResult
     */
    authorized?: boolean;
    /**
     * Object is the resource it would act on.
     * @type {O11yO11yObject}
     * @memberof O11yO11yTransactionResult
     */
    object?: O11yO11yObject;
    /**
     * Relation is the verb that was asked about.
     * @type {string}
     * @memberof O11yO11yTransactionResult
     */
    relation?: string;
}

/**
 * Check if a given object implements the O11yO11yTransactionResult interface.
 */
export function instanceOfO11yO11yTransactionResult(value: object): value is O11yO11yTransactionResult {
    return true;
}

export function O11yO11yTransactionResultFromJSON(json: any): O11yO11yTransactionResult {
    return O11yO11yTransactionResultFromJSONTyped(json, false);
}

export function O11yO11yTransactionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yTransactionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'authorized': json['authorized'] == null ? undefined : json['authorized'],
        'object': json['object'] == null ? undefined : O11yO11yObjectFromJSON(json['object']),
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function O11yO11yTransactionResultToJSON(json: any): O11yO11yTransactionResult {
    return O11yO11yTransactionResultToJSONTyped(json, false);
}

export function O11yO11yTransactionResultToJSONTyped(value?: O11yO11yTransactionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorized': value['authorized'],
        'object': O11yO11yObjectToJSON(value['object']),
        'relation': value['relation'],
    };
}

