/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yDomainFilter
 */
export interface O11yO11yDomainFilter {
    /**
     * Expression is the predicate, e.g. `http.status_code >= 500`.
     * @type {string}
     * @memberof O11yO11yDomainFilter
     */
    expression?: string;
}

/**
 * Check if a given object implements the O11yO11yDomainFilter interface.
 */
export function instanceOfO11yO11yDomainFilter(value: object): value is O11yO11yDomainFilter {
    return true;
}

export function O11yO11yDomainFilterFromJSON(json: any): O11yO11yDomainFilter {
    return O11yO11yDomainFilterFromJSONTyped(json, false);
}

export function O11yO11yDomainFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yDomainFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'] == null ? undefined : json['expression'],
    };
}

export function O11yO11yDomainFilterToJSON(json: any): O11yO11yDomainFilter {
    return O11yO11yDomainFilterToJSONTyped(json, false);
}

export function O11yO11yDomainFilterToJSONTyped(value?: O11yO11yDomainFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
    };
}

