/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yFilterSet } from './O11yFilterSet.js';
import {
    O11yFilterSetFromJSON,
    O11yFilterSetFromJSONTyped,
    O11yFilterSetToJSON,
    O11yFilterSetToJSONTyped,
} from './O11yFilterSet.js';

/**
 * 
 * @export
 * @interface O11yPostablePipeline
 */
export interface O11yPostablePipeline {
    /**
     * 
     * @type {string}
     * @memberof O11yPostablePipeline
     */
    alias?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof O11yPostablePipeline
     */
    config?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof O11yPostablePipeline
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof O11yPostablePipeline
     */
    enabled?: boolean;
    /**
     * 
     * @type {O11yFilterSet}
     * @memberof O11yPostablePipeline
     */
    filter?: O11yFilterSet;
    /**
     * 
     * @type {string}
     * @memberof O11yPostablePipeline
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof O11yPostablePipeline
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof O11yPostablePipeline
     */
    orderId?: number;
}

/**
 * Check if a given object implements the O11yPostablePipeline interface.
 */
export function instanceOfO11yPostablePipeline(value: object): value is O11yPostablePipeline {
    return true;
}

export function O11yPostablePipelineFromJSON(json: any): O11yPostablePipeline {
    return O11yPostablePipelineFromJSONTyped(json, false);
}

export function O11yPostablePipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yPostablePipeline {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
        'config': json['config'] == null ? undefined : json['config'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'filter': json['filter'] == null ? undefined : O11yFilterSetFromJSON(json['filter']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
    };
}

export function O11yPostablePipelineToJSON(json: any): O11yPostablePipeline {
    return O11yPostablePipelineToJSONTyped(json, false);
}

export function O11yPostablePipelineToJSONTyped(value?: O11yPostablePipeline | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'config': value['config'],
        'description': value['description'],
        'enabled': value['enabled'],
        'filter': O11yFilterSetToJSON(value['filter']),
        'id': value['id'],
        'name': value['name'],
        'orderId': value['orderId'],
    };
}

