/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { O11yDeprecatedGettableAlert } from './O11yDeprecatedGettableAlert.js';
import {
    O11yDeprecatedGettableAlertFromJSON,
    O11yDeprecatedGettableAlertFromJSONTyped,
    O11yDeprecatedGettableAlertToJSON,
    O11yDeprecatedGettableAlertToJSONTyped,
} from './O11yDeprecatedGettableAlert.js';

/**
 * 
 * @export
 * @interface O11yO11yAlertsOut
 */
export interface O11yO11yAlertsOut {
    /**
     * Data holds the alerts.
     * @type {Array<O11yDeprecatedGettableAlert>}
     * @memberof O11yO11yAlertsOut
     */
    data?: Array<O11yDeprecatedGettableAlert>;
    /**
     * Status is "success".
     * @type {string}
     * @memberof O11yO11yAlertsOut
     */
    status?: string;
}

/**
 * Check if a given object implements the O11yO11yAlertsOut interface.
 */
export function instanceOfO11yO11yAlertsOut(value: object): value is O11yO11yAlertsOut {
    return true;
}

export function O11yO11yAlertsOutFromJSON(json: any): O11yO11yAlertsOut {
    return O11yO11yAlertsOutFromJSONTyped(json, false);
}

export function O11yO11yAlertsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yAlertsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(O11yDeprecatedGettableAlertFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function O11yO11yAlertsOutToJSON(json: any): O11yO11yAlertsOut {
    return O11yO11yAlertsOutToJSONTyped(json, false);
}

export function O11yO11yAlertsOutToJSONTyped(value?: O11yO11yAlertsOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(O11yDeprecatedGettableAlertToJSON)),
        'status': value['status'],
    };
}

