/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface O11yO11yMetricMetadata
 */
export interface O11yO11yMetricMetadata {
    /**
     * Description describes the metric.
     * @type {string}
     * @memberof O11yO11yMetricMetadata
     */
    description?: string;
    /**
     * IsMonotonic marks a sum that only ever increases.
     * @type {boolean}
     * @memberof O11yO11yMetricMetadata
     */
    isMonotonic?: boolean;
    /**
     * Temporality is delta or cumulative.
     * @type {string}
     * @memberof O11yO11yMetricMetadata
     */
    temporality?: string;
    /**
     * Type is the metric type, e.g. gauge, sum, histogram.
     * @type {string}
     * @memberof O11yO11yMetricMetadata
     */
    type?: string;
    /**
     * Unit is the metric's unit.
     * @type {string}
     * @memberof O11yO11yMetricMetadata
     */
    unit?: string;
}

/**
 * Check if a given object implements the O11yO11yMetricMetadata interface.
 */
export function instanceOfO11yO11yMetricMetadata(value: object): value is O11yO11yMetricMetadata {
    return true;
}

export function O11yO11yMetricMetadataFromJSON(json: any): O11yO11yMetricMetadata {
    return O11yO11yMetricMetadataFromJSONTyped(json, false);
}

export function O11yO11yMetricMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): O11yO11yMetricMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'isMonotonic': json['isMonotonic'] == null ? undefined : json['isMonotonic'],
        'temporality': json['temporality'] == null ? undefined : json['temporality'],
        'type': json['type'] == null ? undefined : json['type'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function O11yO11yMetricMetadataToJSON(json: any): O11yO11yMetricMetadata {
    return O11yO11yMetricMetadataToJSONTyped(json, false);
}

export function O11yO11yMetricMetadataToJSONTyped(value?: O11yO11yMetricMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'isMonotonic': value['isMonotonic'],
        'temporality': value['temporality'],
        'type': value['type'],
        'unit': value['unit'],
    };
}

