/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OperatorUser
 */
export interface OperatorUser {
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OperatorUser
     */
    forbidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperatorUser
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OperatorUser
     */
    isSuperAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    lastSignin?: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof OperatorUser
     */
    tag?: string;
}

/**
 * Check if a given object implements the OperatorUser interface.
 */
export function instanceOfOperatorUser(value: object): value is OperatorUser {
    return true;
}

export function OperatorUserFromJSON(json: any): OperatorUser {
    return OperatorUserFromJSONTyped(json, false);
}

export function OperatorUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorUser {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
        'forbidden': json['forbidden'] == null ? undefined : json['forbidden'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'isSuperAdmin': json['isSuperAdmin'] == null ? undefined : json['isSuperAdmin'],
        'lastSignin': json['lastSignin'] == null ? undefined : json['lastSignin'],
        'name': json['name'] == null ? undefined : json['name'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function OperatorUserToJSON(json: any): OperatorUser {
    return OperatorUserToJSONTyped(json, false);
}

export function OperatorUserToJSONTyped(value?: OperatorUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'displayName': value['displayName'],
        'email': value['email'],
        'forbidden': value['forbidden'],
        'isAdmin': value['isAdmin'],
        'isSuperAdmin': value['isSuperAdmin'],
        'lastSignin': value['lastSignin'],
        'name': value['name'],
        'owner': value['owner'],
        'tag': value['tag'],
    };
}

