/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { PagesBuildConfig } from './PagesBuildConfig.js';
import {
    PagesBuildConfigFromJSON,
    PagesBuildConfigFromJSONTyped,
    PagesBuildConfigToJSON,
    PagesBuildConfigToJSONTyped,
} from './PagesBuildConfig.js';
import type { PagesDeploymentConfigs } from './PagesDeploymentConfigs.js';
import {
    PagesDeploymentConfigsFromJSON,
    PagesDeploymentConfigsFromJSONTyped,
    PagesDeploymentConfigsToJSON,
    PagesDeploymentConfigsToJSONTyped,
} from './PagesDeploymentConfigs.js';

/**
 * 
 * @export
 * @interface PagesProjectCreate
 */
export interface PagesProjectCreate {
    /**
     * 
     * @type {PagesBuildConfig}
     * @memberof PagesProjectCreate
     */
    buildConfig?: PagesBuildConfig;
    /**
     * 
     * @type {PagesDeploymentConfigs}
     * @memberof PagesProjectCreate
     */
    deploymentConfigs?: PagesDeploymentConfigs;
    /**
     * 
     * @type {string}
     * @memberof PagesProjectCreate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PagesProjectCreate
     */
    productionBranch?: string;
}

/**
 * Check if a given object implements the PagesProjectCreate interface.
 */
export function instanceOfPagesProjectCreate(value: object): value is PagesProjectCreate {
    return true;
}

export function PagesProjectCreateFromJSON(json: any): PagesProjectCreate {
    return PagesProjectCreateFromJSONTyped(json, false);
}

export function PagesProjectCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagesProjectCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'buildConfig': json['build_config'] == null ? undefined : PagesBuildConfigFromJSON(json['build_config']),
        'deploymentConfigs': json['deployment_configs'] == null ? undefined : PagesDeploymentConfigsFromJSON(json['deployment_configs']),
        'name': json['name'] == null ? undefined : json['name'],
        'productionBranch': json['production_branch'] == null ? undefined : json['production_branch'],
    };
}

export function PagesProjectCreateToJSON(json: any): PagesProjectCreate {
    return PagesProjectCreateToJSONTyped(json, false);
}

export function PagesProjectCreateToJSONTyped(value?: PagesProjectCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_config': PagesBuildConfigToJSON(value['buildConfig']),
        'deployment_configs': PagesDeploymentConfigsToJSON(value['deploymentConfigs']),
        'name': value['name'],
        'production_branch': value['productionBranch'],
    };
}

