/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Metrics } from './Metrics.js';
import {
    MetricsFromJSON,
    MetricsFromJSONTyped,
    MetricsToJSON,
    MetricsToJSONTyped,
} from './Metrics.js';
import type { Spec } from './Spec.js';
import {
    SpecFromJSON,
    SpecFromJSONTyped,
    SpecToJSON,
    SpecToJSONTyped,
} from './Spec.js';

/**
 * 
 * @export
 * @interface PatchTargetIn
 */
export interface PatchTargetIn {
    /**
     * 
     * @type {string}
     * @memberof PatchTargetIn
     */
    capacity?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchTargetIn
     */
    host?: string;
    /**
     * ID is the target to update, from the path.
     * @type {string}
     * @memberof PatchTargetIn
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchTargetIn
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchTargetIn
     */
    label?: string;
    /**
     * present => a heartbeat; the server stamps its time
     * @type {Metrics}
     * @memberof PatchTargetIn
     */
    metrics?: Metrics;
    /**
     * 
     * @type {Spec}
     * @memberof PatchTargetIn
     */
    spec?: Spec;
    /**
     * 
     * @type {string}
     * @memberof PatchTargetIn
     */
    status?: string;
}

/**
 * Check if a given object implements the PatchTargetIn interface.
 */
export function instanceOfPatchTargetIn(value: object): value is PatchTargetIn {
    return true;
}

export function PatchTargetInFromJSON(json: any): PatchTargetIn {
    return PatchTargetInFromJSONTyped(json, false);
}

export function PatchTargetInFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchTargetIn {
    if (json == null) {
        return json;
    }
    return {
        
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'host': json['host'] == null ? undefined : json['host'],
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'label': json['label'] == null ? undefined : json['label'],
        'metrics': json['metrics'] == null ? undefined : MetricsFromJSON(json['metrics']),
        'spec': json['spec'] == null ? undefined : SpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PatchTargetInToJSON(json: any): PatchTargetIn {
    return PatchTargetInToJSONTyped(json, false);
}

export function PatchTargetInToJSONTyped(value?: PatchTargetIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capacity': value['capacity'],
        'host': value['host'],
        'id': value['id'],
        'kind': value['kind'],
        'label': value['label'],
        'metrics': MetricsToJSON(value['metrics']),
        'spec': SpecToJSON(value['spec']),
        'status': value['status'],
    };
}

