/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PathIn
 */
export interface PathIn {
    /**
     * ID is the sandbox to read from, from an earlier lease.
     * @type {string}
     * @memberof PathIn
     */
    id?: string;
    /**
     * Path is read relative to the sandbox's working directory unless it is
     * absolute, and a path that climbs out of it is refused rather than rewritten.
     * Empty names the working directory itself, which lists it.
     * @type {string}
     * @memberof PathIn
     */
    path?: string;
}

/**
 * Check if a given object implements the PathIn interface.
 */
export function instanceOfPathIn(value: object): value is PathIn {
    return true;
}

export function PathInFromJSON(json: any): PathIn {
    return PathInFromJSONTyped(json, false);
}

export function PathInFromJSONTyped(json: any, ignoreDiscriminator: boolean): PathIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function PathInToJSON(json: any): PathIn {
    return PathInToJSONTyped(json, false);
}

export function PathInToJSONTyped(value?: PathIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'path': value['path'],
    };
}

