/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PlanToolList
 */
export interface PlanToolList {
    /**
     * Tools are the metered tools, each an opaque object exactly as the catalog
     * emits it — typically name, billing unit and price.
     * @type {Array<any>}
     * @memberof PlanToolList
     */
    tools?: Array<any>;
}

/**
 * Check if a given object implements the PlanToolList interface.
 */
export function instanceOfPlanToolList(value: object): value is PlanToolList {
    return true;
}

export function PlanToolListFromJSON(json: any): PlanToolList {
    return PlanToolListFromJSONTyped(json, false);
}

export function PlanToolListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanToolList {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : json['tools'],
    };
}

export function PlanToolListToJSON(json: any): PlanToolList {
    return PlanToolListToJSONTyped(json, false);
}

export function PlanToolListToJSONTyped(value?: PlanToolList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': value['tools'],
    };
}

