/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Graph } from './Graph.js';
import {
    GraphFromJSON,
    GraphFromJSONTyped,
    GraphToJSON,
    GraphToJSONTyped,
} from './Graph.js';

/**
 * 
 * @export
 * @interface PostAiGraphs200Response
 */
export interface PostAiGraphs200Response {
    /**
     * 
     * @type {Graph}
     * @memberof PostAiGraphs200Response
     */
    data?: Graph;
    /**
     * 
     * @type {any}
     * @memberof PostAiGraphs200Response
     */
    data2?: any | null;
    /**
     * Empty on success, the reason on failure.
     * @type {string}
     * @memberof PostAiGraphs200Response
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof PostAiGraphs200Response
     */
    status: PostAiGraphs200ResponseStatusEnum;
}


/**
 * @export
 */
export const PostAiGraphs200ResponseStatusEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type PostAiGraphs200ResponseStatusEnum = typeof PostAiGraphs200ResponseStatusEnum[keyof typeof PostAiGraphs200ResponseStatusEnum];


/**
 * Check if a given object implements the PostAiGraphs200Response interface.
 */
export function instanceOfPostAiGraphs200Response(value: object): value is PostAiGraphs200Response {
    if (!('msg' in value) || value['msg'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PostAiGraphs200ResponseFromJSON(json: any): PostAiGraphs200Response {
    return PostAiGraphs200ResponseFromJSONTyped(json, false);
}

export function PostAiGraphs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAiGraphs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GraphFromJSON(json['data']),
        'data2': json['data2'] == null ? undefined : json['data2'],
        'msg': json['msg'],
        'status': json['status'],
    };
}

export function PostAiGraphs200ResponseToJSON(json: any): PostAiGraphs200Response {
    return PostAiGraphs200ResponseToJSONTyped(json, false);
}

export function PostAiGraphs200ResponseToJSONTyped(value?: PostAiGraphs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GraphToJSON(value['data']),
        'data2': value['data2'],
        'msg': value['msg'],
        'status': value['status'],
    };
}

