/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DeploymentView } from './DeploymentView.js';
import {
    DeploymentViewFromJSON,
    DeploymentViewFromJSONTyped,
    DeploymentViewToJSON,
    DeploymentViewToJSONTyped,
} from './DeploymentView.js';

/**
 * 
 * @export
 * @interface PreviewView
 */
export interface PreviewView {
    /**
     * App is the preview application's own slug, `<app>-<branch>`.
     * @type {string}
     * @memberof PreviewView
     */
    app?: string;
    /**
     * Branch is the branch this preview maps.
     * @type {string}
     * @memberof PreviewView
     */
    branch?: string;
    /**
     * Deployment is the deployment the preview recorded.
     * @type {DeploymentView}
     * @memberof PreviewView
     */
    deployment?: DeploymentView;
    /**
     * URL is the preview's live HTTPS address.
     * @type {string}
     * @memberof PreviewView
     */
    url?: string;
}

/**
 * Check if a given object implements the PreviewView interface.
 */
export function instanceOfPreviewView(value: object): value is PreviewView {
    return true;
}

export function PreviewViewFromJSON(json: any): PreviewView {
    return PreviewViewFromJSONTyped(json, false);
}

export function PreviewViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewView {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'deployment': json['deployment'] == null ? undefined : DeploymentViewFromJSON(json['deployment']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PreviewViewToJSON(json: any): PreviewView {
    return PreviewViewToJSONTyped(json, false);
}

export function PreviewViewToJSONTyped(value?: PreviewView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'branch': value['branch'],
        'deployment': DeploymentViewToJSON(value['deployment']),
        'url': value['url'],
    };
}

