/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PricingRegionList
 */
export interface PricingRegionList {
    /**
     * Regions are the regions cloud instances can be placed in, each an opaque
     * object exactly as the pricing source emits it — typically id, name and
     * location.
     * @type {Array<{ [key: string]: object; }>}
     * @memberof PricingRegionList
     */
    regions?: Array<{ [key: string]: object; }>;
}

/**
 * Check if a given object implements the PricingRegionList interface.
 */
export function instanceOfPricingRegionList(value: object): value is PricingRegionList {
    return true;
}

export function PricingRegionListFromJSON(json: any): PricingRegionList {
    return PricingRegionListFromJSONTyped(json, false);
}

export function PricingRegionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingRegionList {
    if (json == null) {
        return json;
    }
    return {
        
        'regions': json['regions'] == null ? undefined : json['regions'],
    };
}

export function PricingRegionListToJSON(json: any): PricingRegionList {
    return PricingRegionListToJSONTyped(json, false);
}

export function PricingRegionListToJSONTyped(value?: PricingRegionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'regions': value['regions'],
    };
}

