/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PricingProviderList
 */
export interface PricingProviderList {
    /**
     * Providers maps a provider name to its opaque info object. A provider
     * hidden for the caller's org is absent entirely.
     * @type {{ [key: string]: object; }}
     * @memberof PricingProviderList
     */
    providers?: { [key: string]: object; };
    /**
     * Updated is when the catalog was last refreshed, as the pricing source
     * recorded it.
     * @type {object}
     * @memberof PricingProviderList
     */
    updated?: object;
}

/**
 * Check if a given object implements the PricingProviderList interface.
 */
export function instanceOfPricingProviderList(value: object): value is PricingProviderList {
    return true;
}

export function PricingProviderListFromJSON(json: any): PricingProviderList {
    return PricingProviderListFromJSONTyped(json, false);
}

export function PricingProviderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingProviderList {
    if (json == null) {
        return json;
    }
    return {
        
        'providers': json['providers'] == null ? undefined : json['providers'],
        'updated': json['updated'] == null ? undefined : json['updated'],
    };
}

export function PricingProviderListToJSON(json: any): PricingProviderList {
    return PricingProviderListToJSONTyped(json, false);
}

export function PricingProviderListToJSONTyped(value?: PricingProviderList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providers': value['providers'],
        'updated': value['updated'],
    };
}

