/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ProjectsSiteDeploy
 */
export interface ProjectsSiteDeploy {
    /**
     * DeploymentID is the deployment this publish recorded, for the history.
     * @type {string}
     * @memberof ProjectsSiteDeploy
     */
    deploymentId?: string;
    /**
     * Files are the site-relative paths that were uploaded, sorted.
     * @type {Array<string>}
     * @memberof ProjectsSiteDeploy
     */
    files?: Array<string>;
    /**
     * Name is the project's display name.
     * @type {string}
     * @memberof ProjectsSiteDeploy
     */
    name?: string;
    /**
     * Slug is the project the site was published into, created on the fly when
     * the slug was free.
     * @type {string}
     * @memberof ProjectsSiteDeploy
     */
    slug?: string;
    /**
     * Status is the deployment status, "live" on success.
     * @type {string}
     * @memberof ProjectsSiteDeploy
     */
    status?: string;
    /**
     * URL is the canonical live URL, https://<slug>.<apex> — empty when the
     * subdomain belongs to another tenant and this site has none.
     * @type {string}
     * @memberof ProjectsSiteDeploy
     */
    url?: string;
}

/**
 * Check if a given object implements the ProjectsSiteDeploy interface.
 */
export function instanceOfProjectsSiteDeploy(value: object): value is ProjectsSiteDeploy {
    return true;
}

export function ProjectsSiteDeployFromJSON(json: any): ProjectsSiteDeploy {
    return ProjectsSiteDeployFromJSONTyped(json, false);
}

export function ProjectsSiteDeployFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsSiteDeploy {
    if (json == null) {
        return json;
    }
    return {
        
        'deploymentId': json['deploymentId'] == null ? undefined : json['deploymentId'],
        'files': json['files'] == null ? undefined : json['files'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ProjectsSiteDeployToJSON(json: any): ProjectsSiteDeploy {
    return ProjectsSiteDeployToJSONTyped(json, false);
}

export function ProjectsSiteDeployToJSONTyped(value?: ProjectsSiteDeploy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deploymentId': value['deploymentId'],
        'files': value['files'],
        'name': value['name'],
        'slug': value['slug'],
        'status': value['status'],
        'url': value['url'],
    };
}

