/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Promo } from './Promo.js';
import {
    PromoFromJSON,
    PromoFromJSONTyped,
    PromoToJSON,
    PromoToJSONTyped,
} from './Promo.js';

/**
 * 
 * @export
 * @interface PromoStatus
 */
export interface PromoStatus {
    /**
     * Promo is the offer itself. It is fleet-wide, identical for every org — only
     * the two counters beside it move.
     * @type {Promo}
     * @memberof PromoStatus
     */
    promo?: Promo;
    /**
     * Redeemed is how many orgs have taken it, Remaining how many are left under
     * the fleet-wide cap.
     * @type {number}
     * @memberof PromoStatus
     */
    redeemed?: number;
    /**
     * Remaining is MaxRedemptions minus Redeemed, floored at 0. At 0 the next
     * redeem is declined, and a quote reports ineligible rather than pricing an
     * offer that cannot be taken.
     * @type {number}
     * @memberof PromoStatus
     */
    remaining?: number;
}

/**
 * Check if a given object implements the PromoStatus interface.
 */
export function instanceOfPromoStatus(value: object): value is PromoStatus {
    return true;
}

export function PromoStatusFromJSON(json: any): PromoStatus {
    return PromoStatusFromJSONTyped(json, false);
}

export function PromoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'promo': json['promo'] == null ? undefined : PromoFromJSON(json['promo']),
        'redeemed': json['redeemed'] == null ? undefined : json['redeemed'],
        'remaining': json['remaining'] == null ? undefined : json['remaining'],
    };
}

export function PromoStatusToJSON(json: any): PromoStatus {
    return PromoStatusToJSONTyped(json, false);
}

export function PromoStatusToJSONTyped(value?: PromoStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promo': PromoToJSON(value['promo']),
        'redeemed': value['redeemed'],
        'remaining': value['remaining'],
    };
}

