/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AgentMcpTools } from './AgentMcpTools.js';
import {
    AgentMcpToolsFromJSON,
    AgentMcpToolsFromJSONTyped,
    AgentMcpToolsToJSON,
    AgentMcpToolsToJSONTyped,
} from './AgentMcpTools.js';

/**
 * 
 * @export
 * @interface Provider
 */
export interface Provider {
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    apiVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    asset?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    browserUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    chain?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    compatibleProvider?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    configText?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    contractMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    contractName?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    createdTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    displayName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Provider
     */
    enableThinking?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    errorText?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    flavor?: string;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    frequencyPenalty?: number;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    inputPricePerThousandTokens?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Provider
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Provider
     */
    isRemote?: boolean;
    /**
     * 
     * @type {Array<AgentMcpTools>}
     * @memberof Provider
     */
    mcpTools?: Array<AgentMcpTools>;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    network?: string;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    outputPricePerThousandTokens?: number;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    owner?: string;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    presencePenalty?: number;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    providerKey?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    providerUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    rawText?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    resultSummary?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    runner?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    signCert?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    signKey?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    subType?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    target?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    targetMode?: string;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    testContent?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    topK?: number;
    /**
     * 
     * @type {number}
     * @memberof Provider
     */
    topP?: number;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    userCert?: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    userKey?: string;
}

/**
 * Check if a given object implements the Provider interface.
 */
export function instanceOfProvider(value: object): value is Provider {
    return true;
}

export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'asset': json['asset'] == null ? undefined : json['asset'],
        'browserUrl': json['browserUrl'] == null ? undefined : json['browserUrl'],
        'category': json['category'] == null ? undefined : json['category'],
        'chain': json['chain'] == null ? undefined : json['chain'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
        'compatibleProvider': json['compatibleProvider'] == null ? undefined : json['compatibleProvider'],
        'configText': json['configText'] == null ? undefined : json['configText'],
        'contractMethod': json['contractMethod'] == null ? undefined : json['contractMethod'],
        'contractName': json['contractName'] == null ? undefined : json['contractName'],
        'createdTime': json['createdTime'] == null ? undefined : json['createdTime'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'enableThinking': json['enableThinking'] == null ? undefined : json['enableThinking'],
        'errorText': json['errorText'] == null ? undefined : json['errorText'],
        'flavor': json['flavor'] == null ? undefined : json['flavor'],
        'frequencyPenalty': json['frequencyPenalty'] == null ? undefined : json['frequencyPenalty'],
        'inputPricePerThousandTokens': json['inputPricePerThousandTokens'] == null ? undefined : json['inputPricePerThousandTokens'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'isRemote': json['isRemote'] == null ? undefined : json['isRemote'],
        'mcpTools': json['mcpTools'] == null ? undefined : ((json['mcpTools'] as Array<any>).map(AgentMcpToolsFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'network': json['network'] == null ? undefined : json['network'],
        'outputPricePerThousandTokens': json['outputPricePerThousandTokens'] == null ? undefined : json['outputPricePerThousandTokens'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'presencePenalty': json['presencePenalty'] == null ? undefined : json['presencePenalty'],
        'providerKey': json['providerKey'] == null ? undefined : json['providerKey'],
        'providerUrl': json['providerUrl'] == null ? undefined : json['providerUrl'],
        'rawText': json['rawText'] == null ? undefined : json['rawText'],
        'region': json['region'] == null ? undefined : json['region'],
        'resultSummary': json['resultSummary'] == null ? undefined : json['resultSummary'],
        'runner': json['runner'] == null ? undefined : json['runner'],
        'signCert': json['signCert'] == null ? undefined : json['signCert'],
        'signKey': json['signKey'] == null ? undefined : json['signKey'],
        'state': json['state'] == null ? undefined : json['state'],
        'subType': json['subType'] == null ? undefined : json['subType'],
        'target': json['target'] == null ? undefined : json['target'],
        'targetMode': json['targetMode'] == null ? undefined : json['targetMode'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'testContent': json['testContent'] == null ? undefined : json['testContent'],
        'text': json['text'] == null ? undefined : json['text'],
        'topK': json['topK'] == null ? undefined : json['topK'],
        'topP': json['topP'] == null ? undefined : json['topP'],
        'type': json['type'] == null ? undefined : json['type'],
        'userCert': json['userCert'] == null ? undefined : json['userCert'],
        'userKey': json['userKey'] == null ? undefined : json['userKey'],
    };
}

export function ProviderToJSON(json: any): Provider {
    return ProviderToJSONTyped(json, false);
}

export function ProviderToJSONTyped(value?: Provider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiVersion': value['apiVersion'],
        'asset': value['asset'],
        'browserUrl': value['browserUrl'],
        'category': value['category'],
        'chain': value['chain'],
        'clientId': value['clientId'],
        'clientSecret': value['clientSecret'],
        'compatibleProvider': value['compatibleProvider'],
        'configText': value['configText'],
        'contractMethod': value['contractMethod'],
        'contractName': value['contractName'],
        'createdTime': value['createdTime'],
        'currency': value['currency'],
        'displayName': value['displayName'],
        'enableThinking': value['enableThinking'],
        'errorText': value['errorText'],
        'flavor': value['flavor'],
        'frequencyPenalty': value['frequencyPenalty'],
        'inputPricePerThousandTokens': value['inputPricePerThousandTokens'],
        'isDefault': value['isDefault'],
        'isRemote': value['isRemote'],
        'mcpTools': value['mcpTools'] == null ? undefined : ((value['mcpTools'] as Array<any>).map(AgentMcpToolsToJSON)),
        'name': value['name'],
        'network': value['network'],
        'outputPricePerThousandTokens': value['outputPricePerThousandTokens'],
        'owner': value['owner'],
        'presencePenalty': value['presencePenalty'],
        'providerKey': value['providerKey'],
        'providerUrl': value['providerUrl'],
        'rawText': value['rawText'],
        'region': value['region'],
        'resultSummary': value['resultSummary'],
        'runner': value['runner'],
        'signCert': value['signCert'],
        'signKey': value['signKey'],
        'state': value['state'],
        'subType': value['subType'],
        'target': value['target'],
        'targetMode': value['targetMode'],
        'temperature': value['temperature'],
        'testContent': value['testContent'],
        'text': value['text'],
        'topK': value['topK'],
        'topP': value['topP'],
        'type': value['type'],
        'userCert': value['userCert'],
        'userKey': value['userKey'],
    };
}

