/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Variant } from './Variant.js';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
    VariantToJSONTyped,
} from './Variant.js';

/**
 * 
 * @export
 * @interface PublishKitIn
 */
export interface PublishKitIn {
    /**
     * Category groups the kit in the gallery browser.
     * @type {string}
     * @memberof PublishKitIn
     */
    category?: string;
    /**
     * Demo is the deployed site itself, when there is one.
     * @type {string}
     * @memberof PublishKitIn
     */
    demo?: string;
    /**
     * Description is the browse-card blurb, max 4096 characters.
     * @type {string}
     * @memberof PublishKitIn
     */
    description?: string;
    /**
     * Features are the highlights the card lists, at most 32.
     * @type {Array<string>}
     * @memberof PublishKitIn
     */
    features?: Array<string>;
    /**
     * Framework is the stack the kit is built on ("Next.js 14").
     * @type {string}
     * @memberof PublishKitIn
     */
    framework?: string;
    /**
     * Preview is the still image the browse card renders, max 4096 characters.
     * @type {string}
     * @memberof PublishKitIn
     */
    preview?: string;
    /**
     * Slug is the kit's identity — lowercase alphanumeric with dashes, max 40.
     * @type {string}
     * @memberof PublishKitIn
     */
    slug?: string;
    /**
     * Source is the repository the kit is forked from, max 4096 characters.
     * @type {string}
     * @memberof PublishKitIn
     */
    source?: string;
    /**
     * Title is the display name. Required, max 200 characters.
     * @type {string}
     * @memberof PublishKitIn
     */
    title?: string;
    /**
     * UseCase is what the kit is for, in a phrase.
     * @type {string}
     * @memberof PublishKitIn
     */
    useCase?: string;
    /**
     * Variants are the shapes this kit ships in, at most 32; the fork picks one.
     * @type {Array<Variant>}
     * @memberof PublishKitIn
     */
    variants?: Array<Variant>;
}

/**
 * Check if a given object implements the PublishKitIn interface.
 */
export function instanceOfPublishKitIn(value: object): value is PublishKitIn {
    return true;
}

export function PublishKitInFromJSON(json: any): PublishKitIn {
    return PublishKitInFromJSONTyped(json, false);
}

export function PublishKitInFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishKitIn {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'demo': json['demo'] == null ? undefined : json['demo'],
        'description': json['description'] == null ? undefined : json['description'],
        'features': json['features'] == null ? undefined : json['features'],
        'framework': json['framework'] == null ? undefined : json['framework'],
        'preview': json['preview'] == null ? undefined : json['preview'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'source': json['source'] == null ? undefined : json['source'],
        'title': json['title'] == null ? undefined : json['title'],
        'useCase': json['useCase'] == null ? undefined : json['useCase'],
        'variants': json['variants'] == null ? undefined : ((json['variants'] as Array<any>).map(VariantFromJSON)),
    };
}

export function PublishKitInToJSON(json: any): PublishKitIn {
    return PublishKitInToJSONTyped(json, false);
}

export function PublishKitInToJSONTyped(value?: PublishKitIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'demo': value['demo'],
        'description': value['description'],
        'features': value['features'],
        'framework': value['framework'],
        'preview': value['preview'],
        'slug': value['slug'],
        'source': value['source'],
        'title': value['title'],
        'useCase': value['useCase'],
        'variants': value['variants'] == null ? undefined : ((value['variants'] as Array<any>).map(VariantToJSON)),
    };
}

