/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PublishReq
 */
export interface PublishReq {
    /**
     * Category groups the listing in the shop window.
     * @type {string}
     * @memberof PublishReq
     */
    category?: string;
    /**
     * Currency denominates Price.
     * @type {string}
     * @memberof PublishReq
     */
    currency?: string;
    /**
     * Description is the long copy, clipped at 4096 characters.
     * @type {string}
     * @memberof PublishReq
     */
    description?: string;
    /**
     * Price is the per-call price as a decimal USD string, exact to 18 places —
     * "0.0025" is a quarter of a cent and stays one. Empty or "0" (the default)
     * publishes it free; any positive price makes the listing monetized and
     * requires Recipient.
     * @type {string}
     * @memberof PublishReq
     */
    price?: string;
    /**
     * Public makes the listing discoverable by other orgs. Private otherwise.
     * @type {boolean}
     * @memberof PublishReq
     */
    _public?: boolean;
    /**
     * Recipient is the seller's payout wallet ID, in the publishing org — the
     * wallet x402 pays. Required for a monetized listing.
     * @type {string}
     * @memberof PublishReq
     */
    recipient?: string;
    /**
     * Title is the shop-window name, 1-200 characters. Required.
     * @type {string}
     * @memberof PublishReq
     */
    title?: string;
    /**
     * Tool is the registry name of the capability being offered. It must already
     * resolve in the publisher's own scope — there are no phantom listings.
     * @type {string}
     * @memberof PublishReq
     */
    tool?: string;
}

/**
 * Check if a given object implements the PublishReq interface.
 */
export function instanceOfPublishReq(value: object): value is PublishReq {
    return true;
}

export function PublishReqFromJSON(json: any): PublishReq {
    return PublishReqFromJSONTyped(json, false);
}

export function PublishReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishReq {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        '_public': json['public'] == null ? undefined : json['public'],
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
        'title': json['title'] == null ? undefined : json['title'],
        'tool': json['tool'] == null ? undefined : json['tool'],
    };
}

export function PublishReqToJSON(json: any): PublishReq {
    return PublishReqToJSONTyped(json, false);
}

export function PublishReqToJSONTyped(value?: PublishReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'currency': value['currency'],
        'description': value['description'],
        'price': value['price'],
        'public': value['_public'],
        'recipient': value['recipient'],
        'title': value['title'],
        'tool': value['tool'],
    };
}

