/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RegistryToken
 */
export interface RegistryToken {
    /**
     * Expires is the token's lifetime in seconds.
     * @type {number}
     * @memberof RegistryToken
     */
    expires?: number;
    /**
     * Ref is the one repository reference the token can pull.
     * @type {string}
     * @memberof RegistryToken
     */
    ref?: string;
    /**
     * Token is the bearer to present on the OCI wire
     * (`Authorization: Bearer …` against the host's /v2/ routes).
     * @type {string}
     * @memberof RegistryToken
     */
    token?: string;
}

/**
 * Check if a given object implements the RegistryToken interface.
 */
export function instanceOfRegistryToken(value: object): value is RegistryToken {
    return true;
}

export function RegistryTokenFromJSON(json: any): RegistryToken {
    return RegistryTokenFromJSONTyped(json, false);
}

export function RegistryTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistryToken {
    if (json == null) {
        return json;
    }
    return {
        
        'expires': json['expires'] == null ? undefined : json['expires'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function RegistryTokenToJSON(json: any): RegistryToken {
    return RegistryTokenToJSONTyped(json, false);
}

export function RegistryTokenToJSONTyped(value?: RegistryToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires': value['expires'],
        'ref': value['ref'],
        'token': value['token'],
    };
}

