/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Restarted
 */
export interface Restarted {
    /**
     * App is the service that was restarted.
     * @type {string}
     * @memberof Restarted
     */
    app?: string;
    /**
     * Env is that namespace's lifecycle env.
     * @type {string}
     * @memberof Restarted
     */
    env?: string;
    /**
     * Namespace is the namespace its Deployment was patched in.
     * @type {string}
     * @memberof Restarted
     */
    namespace?: string;
    /**
     * OK is always true — a failure is an error, not a false here.
     * @type {boolean}
     * @memberof Restarted
     */
    ok?: boolean;
    /**
     * RestartedAt is the timestamp stamped onto the pod template, RFC3339 UTC.
     * @type {string}
     * @memberof Restarted
     */
    restartedAt?: string;
}

/**
 * Check if a given object implements the Restarted interface.
 */
export function instanceOfRestarted(value: object): value is Restarted {
    return true;
}

export function RestartedFromJSON(json: any): Restarted {
    return RestartedFromJSONTyped(json, false);
}

export function RestartedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Restarted {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
        'env': json['env'] == null ? undefined : json['env'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'ok': json['ok'] == null ? undefined : json['ok'],
        'restartedAt': json['restartedAt'] == null ? undefined : json['restartedAt'],
    };
}

export function RestartedToJSON(json: any): Restarted {
    return RestartedToJSONTyped(json, false);
}

export function RestartedToJSONTyped(value?: Restarted | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'env': value['env'],
        'namespace': value['namespace'],
        'ok': value['ok'],
        'restartedAt': value['restartedAt'],
    };
}

