/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RunIn
 */
export interface RunIn {
    /**
     * Action is the name of the connector action to invoke.
     * @type {string}
     * @memberof RunIn
     */
    action?: string;
    /**
     * Auth is the caller's resolved credential for the connector, handed to the
     * action verbatim. Its shape is whatever the connector's auth descriptor
     * declares (a token string, an object), so it is opaque here.
     * @type {object}
     * @memberof RunIn
     */
    auth?: object;
    /**
     * ID is the connector to run, from the path.
     * @type {string}
     * @memberof RunIn
     */
    id?: string;
    /**
     * Props are the action's input properties, keyed by property name.
     * @type {{ [key: string]: object; }}
     * @memberof RunIn
     */
    props?: { [key: string]: object; };
}

/**
 * Check if a given object implements the RunIn interface.
 */
export function instanceOfRunIn(value: object): value is RunIn {
    return true;
}

export function RunInFromJSON(json: any): RunIn {
    return RunInFromJSONTyped(json, false);
}

export function RunInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunIn {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'auth': json['auth'] == null ? undefined : json['auth'],
        'id': json['id'] == null ? undefined : json['id'],
        'props': json['props'] == null ? undefined : json['props'],
    };
}

export function RunInToJSON(json: any): RunIn {
    return RunInToJSONTyped(json, false);
}

export function RunInToJSONTyped(value?: RunIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'auth': value['auth'],
        'id': value['id'],
        'props': value['props'],
    };
}

