/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RunRecord
 */
export interface RunRecord {
    /**
     * AvgScore is the mean over the scored examples.
     * @type {number}
     * @memberof RunRecord
     */
    avgScore?: number;
    /**
     * CreatedAt is when the run first landed.
     * @type {string}
     * @memberof RunRecord
     */
    createdAt?: string;
    /**
     * Dataset is the set that was scored.
     * @type {string}
     * @memberof RunRecord
     */
    dataset?: string;
    /**
     * Items is how many examples were attempted.
     * @type {number}
     * @memberof RunRecord
     */
    items?: number;
    /**
     * JudgeModel is the model that graded.
     * @type {string}
     * @memberof RunRecord
     */
    judgeModel?: string;
    /**
     * Model is the model under test.
     * @type {string}
     * @memberof RunRecord
     */
    model?: string;
    /**
     * RunName is the run's label.
     * @type {string}
     * @memberof RunRecord
     */
    runName?: string;
    /**
     * Scored is how many produced a real score.
     * @type {number}
     * @memberof RunRecord
     */
    scored?: number;
    /**
     * UpdatedAt is when the record last changed.
     * @type {string}
     * @memberof RunRecord
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the RunRecord interface.
 */
export function instanceOfRunRecord(value: object): value is RunRecord {
    return true;
}

export function RunRecordFromJSON(json: any): RunRecord {
    return RunRecordFromJSONTyped(json, false);
}

export function RunRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'avgScore': json['avgScore'] == null ? undefined : json['avgScore'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'dataset': json['dataset'] == null ? undefined : json['dataset'],
        'items': json['items'] == null ? undefined : json['items'],
        'judgeModel': json['judgeModel'] == null ? undefined : json['judgeModel'],
        'model': json['model'] == null ? undefined : json['model'],
        'runName': json['runName'] == null ? undefined : json['runName'],
        'scored': json['scored'] == null ? undefined : json['scored'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function RunRecordToJSON(json: any): RunRecord {
    return RunRecordToJSONTyped(json, false);
}

export function RunRecordToJSONTyped(value?: RunRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avgScore': value['avgScore'],
        'createdAt': value['createdAt'],
        'dataset': value['dataset'],
        'items': value['items'],
        'judgeModel': value['judgeModel'],
        'model': value['model'],
        'runName': value['runName'],
        'scored': value['scored'],
        'updatedAt': value['updatedAt'],
    };
}

