/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Scale
 */
export interface Scale {
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    createdTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Scale
     */
    text?: string;
}

/**
 * Check if a given object implements the Scale interface.
 */
export function instanceOfScale(value: object): value is Scale {
    return true;
}

export function ScaleFromJSON(json: any): Scale {
    return ScaleFromJSONTyped(json, false);
}

export function ScaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scale {
    if (json == null) {
        return json;
    }
    return {
        
        'createdTime': json['createdTime'] == null ? undefined : json['createdTime'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'name': json['name'] == null ? undefined : json['name'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'state': json['state'] == null ? undefined : json['state'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function ScaleToJSON(json: any): Scale {
    return ScaleToJSONTyped(json, false);
}

export function ScaleToJSONTyped(value?: Scale | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdTime': value['createdTime'],
        'displayName': value['displayName'],
        'name': value['name'],
        'owner': value['owner'],
        'state': value['state'],
        'text': value['text'],
    };
}

