/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Span } from './Span.js';
import {
    SpanFromJSON,
    SpanFromJSONTyped,
    SpanToJSON,
    SpanToJSONTyped,
} from './Span.js';

/**
 * 
 * @export
 * @interface SearchResults
 */
export interface SearchResults {
    /**
     * Degraded is true when retrieval failed and the empty result set is an
     * outage rather than a real absence of matches. Absent on a healthy answer.
     * @type {boolean}
     * @memberof SearchResults
     */
    degraded?: boolean;
    /**
     * Query echoes the query that was run.
     * @type {string}
     * @memberof SearchResults
     */
    query?: string;
    /**
     * Results are the matching spans, best first. Never null — an empty search is
     * an empty array.
     * @type {Array<Span>}
     * @memberof SearchResults
     */
    results?: Array<Span>;
    /**
     * Type echoes the retrieval tier that ran, after defaulting.
     * @type {string}
     * @memberof SearchResults
     */
    type?: string;
}

/**
 * Check if a given object implements the SearchResults interface.
 */
export function instanceOfSearchResults(value: object): value is SearchResults {
    return true;
}

export function SearchResultsFromJSON(json: any): SearchResults {
    return SearchResultsFromJSONTyped(json, false);
}

export function SearchResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResults {
    if (json == null) {
        return json;
    }
    return {
        
        'degraded': json['degraded'] == null ? undefined : json['degraded'],
        'query': json['query'] == null ? undefined : json['query'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SpanFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SearchResultsToJSON(json: any): SearchResults {
    return SearchResultsToJSONTyped(json, false);
}

export function SearchResultsToJSONTyped(value?: SearchResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'degraded': value['degraded'],
        'query': value['query'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SpanToJSON)),
        'type': value['type'],
    };
}

