/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SeoAuditOut
 */
export interface SeoAuditOut {
    /**
     * Checks is every named finding, each a yes or no — "is_https", "no_h1_tag",
     * "high_loading_time", around fifty of them. It is an OPEN set the upstream adds
     * to, so it is published as an object of booleans rather than as fifty declared
     * fields that would be wrong the next time they name a fifty-first.
     * @type {{ [key: string]: boolean; }}
     * @memberof SeoAuditOut
     */
    checks?: { [key: string]: boolean; };
    /**
     * Cost is what this call cost, in USD, as an exact decimal string.
     * @type {string}
     * @memberof SeoAuditOut
     */
    cost?: string;
    /**
     * Description is its meta description.
     * @type {string}
     * @memberof SeoAuditOut
     */
    description?: string;
    /**
     * Score is the upstream's on-page score, 0 to 100.
     * @type {number}
     * @memberof SeoAuditOut
     */
    score?: number;
    /**
     * Status is the HTTP status the page answered with.
     * @type {number}
     * @memberof SeoAuditOut
     */
    status?: number;
    /**
     * Title is the page's title.
     * @type {string}
     * @memberof SeoAuditOut
     */
    title?: string;
    /**
     * URL is the address actually read, after redirects.
     * @type {string}
     * @memberof SeoAuditOut
     */
    url?: string;
    /**
     * Words is how many words of readable text the page carries.
     * @type {number}
     * @memberof SeoAuditOut
     */
    words?: number;
}

/**
 * Check if a given object implements the SeoAuditOut interface.
 */
export function instanceOfSeoAuditOut(value: object): value is SeoAuditOut {
    return true;
}

export function SeoAuditOutFromJSON(json: any): SeoAuditOut {
    return SeoAuditOutFromJSONTyped(json, false);
}

export function SeoAuditOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeoAuditOut {
    if (json == null) {
        return json;
    }
    return {
        
        'checks': json['checks'] == null ? undefined : json['checks'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'description': json['description'] == null ? undefined : json['description'],
        'score': json['score'] == null ? undefined : json['score'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'words': json['words'] == null ? undefined : json['words'],
    };
}

export function SeoAuditOutToJSON(json: any): SeoAuditOut {
    return SeoAuditOutToJSONTyped(json, false);
}

export function SeoAuditOutToJSONTyped(value?: SeoAuditOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checks': value['checks'],
        'cost': value['cost'],
        'description': value['description'],
        'score': value['score'],
        'status': value['status'],
        'title': value['title'],
        'url': value['url'],
        'words': value['words'],
    };
}

