/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SessionView } from './SessionView.js';
import {
    SessionViewFromJSON,
    SessionViewFromJSONTyped,
    SessionViewToJSON,
    SessionViewToJSONTyped,
} from './SessionView.js';

/**
 * 
 * @export
 * @interface SessionList
 */
export interface SessionList {
    /**
     * Sessions is the matching sessions, each with its event and child counts and
     * a one-line preview of its latest event.
     * @type {Array<SessionView>}
     * @memberof SessionList
     */
    sessions?: Array<SessionView>;
}

/**
 * Check if a given object implements the SessionList interface.
 */
export function instanceOfSessionList(value: object): value is SessionList {
    return true;
}

export function SessionListFromJSON(json: any): SessionList {
    return SessionListFromJSONTyped(json, false);
}

export function SessionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionList {
    if (json == null) {
        return json;
    }
    return {
        
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(SessionViewFromJSON)),
    };
}

export function SessionListToJSON(json: any): SessionList {
    return SessionListToJSONTyped(json, false);
}

export function SessionListToJSONTyped(value?: SessionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(SessionViewToJSON)),
    };
}

