/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Signer
 */
export interface Signer {
    /**
     * Email is the address the signature request is sent to.
     * @type {string}
     * @memberof Signer
     */
    email?: string;
    /**
     * Name is the recipient's name, as it appears on the signature request.
     * @type {string}
     * @memberof Signer
     */
    name?: string;
}

/**
 * Check if a given object implements the Signer interface.
 */
export function instanceOfSigner(value: object): value is Signer {
    return true;
}

export function SignerFromJSON(json: any): Signer {
    return SignerFromJSONTyped(json, false);
}

export function SignerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Signer {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SignerToJSON(json: any): Signer {
    return SignerToJSONTyped(json, false);
}

export function SignerToJSONTyped(value?: Signer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

