/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SocialProvider
 */
export interface SocialProvider {
    /**
     * CredentialsConfigured is whether this deployment holds every OAuth
     * application credential the network needs. It is a statement about the
     * DEPLOYMENT, not about the caller: a connected account also needs its own
     * access token before a post can go out.
     * @type {boolean}
     * @memberof SocialProvider
     */
    credentialsConfigured?: boolean;
    /**
     * MissingCredentials names the environment variables still unset for this
     * network, so the answer is an installation instruction rather than a refusal.
     * Absent when the credentials are complete. Only the NAMES appear here; a
     * credential value is never reported.
     * @type {Array<string>}
     * @memberof SocialProvider
     */
    missingCredentials?: Array<string>;
    /**
     * Provider is the network: x, facebook, instagram, linkedin, tiktok, youtube
     * or threads.
     * 
     * Example: "x"
     * @type {string}
     * @memberof SocialProvider
     */
    provider?: string;
}

/**
 * Check if a given object implements the SocialProvider interface.
 */
export function instanceOfSocialProvider(value: object): value is SocialProvider {
    return true;
}

export function SocialProviderFromJSON(json: any): SocialProvider {
    return SocialProviderFromJSONTyped(json, false);
}

export function SocialProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'credentialsConfigured': json['credentialsConfigured'] == null ? undefined : json['credentialsConfigured'],
        'missingCredentials': json['missingCredentials'] == null ? undefined : json['missingCredentials'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function SocialProviderToJSON(json: any): SocialProvider {
    return SocialProviderToJSONTyped(json, false);
}

export function SocialProviderToJSONTyped(value?: SocialProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credentialsConfigured': value['credentialsConfigured'],
        'missingCredentials': value['missingCredentials'],
        'provider': value['provider'],
    };
}

