/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SyncTally
 */
export interface SyncTally {
    /**
     * Live is the number of vouchers newly posted to the live ledger.
     * @type {number}
     * @memberof SyncTally
     */
    live?: number;
    /**
     * Sandbox is the number newly posted to the sandbox ledger.
     * @type {number}
     * @memberof SyncTally
     */
    sandbox?: number;
}

/**
 * Check if a given object implements the SyncTally interface.
 */
export function instanceOfSyncTally(value: object): value is SyncTally {
    return true;
}

export function SyncTallyFromJSON(json: any): SyncTally {
    return SyncTallyFromJSONTyped(json, false);
}

export function SyncTallyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncTally {
    if (json == null) {
        return json;
    }
    return {
        
        'live': json['live'] == null ? undefined : json['live'],
        'sandbox': json['sandbox'] == null ? undefined : json['sandbox'],
    };
}

export function SyncTallyToJSON(json: any): SyncTally {
    return SyncTallyToJSONTyped(json, false);
}

export function SyncTallyToJSONTyped(value?: SyncTally | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'live': value['live'],
        'sandbox': value['sandbox'],
    };
}

