/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SessionView } from './SessionView.js';
import {
    SessionViewFromJSON,
    SessionViewFromJSONTyped,
    SessionViewToJSON,
    SessionViewToJSONTyped,
} from './SessionView.js';

/**
 * 
 * @export
 * @interface TreeNode
 */
export interface TreeNode {
    /**
     * Children is this node's direct children, each a whole node, so the array nests
     * to the depth of the flow. A leaf carries null rather than an empty array. The
     * subtree is materialised in full, up to 10000 nodes, out of one indexed read of
     * the root; nothing is walked node by node.
     * @type {Array<TreeNode>}
     * @memberof TreeNode
     */
    children?: Array<TreeNode>;
    /**
     * Session is this node's own session, carrying its event count and its direct
     * fan-out. It is the same shape the list and detail reads answer with, minus the
     * last-event preview, which the tree does not fetch.
     * @type {SessionView}
     * @memberof TreeNode
     */
    session?: SessionView;
}

/**
 * Check if a given object implements the TreeNode interface.
 */
export function instanceOfTreeNode(value: object): value is TreeNode {
    return true;
}

export function TreeNodeFromJSON(json: any): TreeNode {
    return TreeNodeFromJSONTyped(json, false);
}

export function TreeNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeNode {
    if (json == null) {
        return json;
    }
    return {
        
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(TreeNodeFromJSON)),
        'session': json['session'] == null ? undefined : SessionViewFromJSON(json['session']),
    };
}

export function TreeNodeToJSON(json: any): TreeNode {
    return TreeNodeToJSONTyped(json, false);
}

export function TreeNodeToJSONTyped(value?: TreeNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(TreeNodeToJSON)),
        'session': SessionViewToJSON(value['session']),
    };
}

