/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateAgentIn
 */
export interface UpdateAgentIn {
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    computeRef?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    executionMode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    model?: string;
    /**
     * Ref is the agent to update — its public id or org-unique name, from the path.
     * @type {string}
     * @memberof UpdateAgentIn
     */
    ref?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgentIn
     */
    serviceAccountId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAgentIn
     */
    tools?: Array<string>;
}

/**
 * Check if a given object implements the UpdateAgentIn interface.
 */
export function instanceOfUpdateAgentIn(value: object): value is UpdateAgentIn {
    return true;
}

export function UpdateAgentInFromJSON(json: any): UpdateAgentIn {
    return UpdateAgentInFromJSONTyped(json, false);
}

export function UpdateAgentInFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentIn {
    if (json == null) {
        return json;
    }
    return {
        
        'computeRef': json['computeRef'] == null ? undefined : json['computeRef'],
        'description': json['description'] == null ? undefined : json['description'],
        'executionMode': json['executionMode'] == null ? undefined : json['executionMode'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'model': json['model'] == null ? undefined : json['model'],
        'ref': json['ref'] == null ? undefined : json['ref'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'serviceAccountId': json['serviceAccountId'] == null ? undefined : json['serviceAccountId'],
        'tools': json['tools'] == null ? undefined : json['tools'],
    };
}

export function UpdateAgentInToJSON(json: any): UpdateAgentIn {
    return UpdateAgentInToJSONTyped(json, false);
}

export function UpdateAgentInToJSONTyped(value?: UpdateAgentIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computeRef': value['computeRef'],
        'description': value['description'],
        'executionMode': value['executionMode'],
        'instructions': value['instructions'],
        'model': value['model'],
        'ref': value['ref'],
        'schedule': value['schedule'],
        'serviceAccountId': value['serviceAccountId'],
        'tools': value['tools'],
    };
}

