/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator\'s admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VectorScore
 */
export interface VectorScore {
    /**
     * 
     * @type {number}
     * @memberof VectorScore
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof VectorScore
     */
    vector?: string;
}

/**
 * Check if a given object implements the VectorScore interface.
 */
export function instanceOfVectorScore(value: object): value is VectorScore {
    return true;
}

export function VectorScoreFromJSON(json: any): VectorScore {
    return VectorScoreFromJSONTyped(json, false);
}

export function VectorScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorScore {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'vector': json['vector'] == null ? undefined : json['vector'],
    };
}

export function VectorScoreToJSON(json: any): VectorScore {
    return VectorScoreToJSONTyped(json, false);
}

export function VectorScoreToJSONTyped(value?: VectorScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'vector': value['vector'],
    };
}

