/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    agent?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    chain?: string;
    /**
     * 
     * @type {number}
     * @memberof Wallet
     */
    createdAt?: number;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    custody?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    financeAccount?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    org?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    project?: string;
    /**
     * 
     * @type {string}
     * @memberof Wallet
     */
    tier?: string;
}

/**
 * Check if a given object implements the Wallet interface.
 */
export function instanceOfWallet(value: object): value is Wallet {
    return true;
}

export function WalletFromJSON(json: any): Wallet {
    return WalletFromJSONTyped(json, false);
}

export function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'address': json['address'] == null ? undefined : json['address'],
        'agent': json['agent'] == null ? undefined : json['agent'],
        'chain': json['chain'] == null ? undefined : json['chain'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'custody': json['custody'] == null ? undefined : json['custody'],
        'financeAccount': json['financeAccount'] == null ? undefined : json['financeAccount'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'org': json['org'] == null ? undefined : json['org'],
        'project': json['project'] == null ? undefined : json['project'],
        'tier': json['tier'] == null ? undefined : json['tier'],
    };
}

export function WalletToJSON(json: any): Wallet {
    return WalletToJSONTyped(json, false);
}

export function WalletToJSONTyped(value?: Wallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'address': value['address'],
        'agent': value['agent'],
        'chain': value['chain'],
        'createdAt': value['createdAt'],
        'custody': value['custody'],
        'financeAccount': value['financeAccount'],
        'id': value['id'],
        'name': value['name'],
        'org': value['org'],
        'project': value['project'],
        'tier': value['tier'],
    };
}

