/* tslint:disable */
/* eslint-disable */
/**
 * Hanzo Cloud API
 * Composed from each subsystem\'s own projection of its router, in the fleet\'s mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface WebEngine
 */
export interface WebEngine {
    /**
     * Name is the engine, matching the `engine` stamped on each result.
     * @type {string}
     * @memberof WebEngine
     */
    name?: string;
    /**
     * Outcome is "answered", "blind" or "failed" — see outcome.go. "blind" means
     * the page came back and no results could be read out of it.
     * @type {string}
     * @memberof WebEngine
     */
    outcome?: string;
    /**
     * Results is how many hits this engine contributed, before the merge
     * deduplicated them against the others.
     * @type {number}
     * @memberof WebEngine
     */
    results?: number;
}

/**
 * Check if a given object implements the WebEngine interface.
 */
export function instanceOfWebEngine(value: object): value is WebEngine {
    return true;
}

export function WebEngineFromJSON(json: any): WebEngine {
    return WebEngineFromJSONTyped(json, false);
}

export function WebEngineFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebEngine {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'outcome': json['outcome'] == null ? undefined : json['outcome'],
        'results': json['results'] == null ? undefined : json['results'],
    };
}

export function WebEngineToJSON(json: any): WebEngine {
    return WebEngineToJSONTyped(json, false);
}

export function WebEngineToJSONTyped(value?: WebEngine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'outcome': value['outcome'],
        'results': value['results'],
    };
}

